<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin_login extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_login_model');
    } 

    /*
     * Listing of admin_login
     */
    function index()
    {
        $data['admin_login'] = $this->Admin_login_model->get_all_admin_login();
        
        $data['_view'] = 'admin_login/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new admin_login
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'admin_password' => $this->input->post('admin_password'),
				'admin_username' => $this->input->post('admin_username'),
				'first_name' => $this->input->post('first_name'),
				'last_name' => $this->input->post('last_name'),
				'admin_email' => $this->input->post('admin_email'),
				'admin_contactus' => $this->input->post('admin_contactus'),
				'admin_fax' => $this->input->post('admin_fax'),
				'site_status' => $this->input->post('site_status'),
				'admin_address2' => $this->input->post('admin_address2'),
				'admin_address3' => $this->input->post('admin_address3'),
				'admin_country' => $this->input->post('admin_country'),
				'admin_state' => $this->input->post('admin_state'),
				'admin_city' => $this->input->post('admin_city'),
				'admin_postcode' => $this->input->post('admin_postcode'),
				'profile_picture' => $this->input->post('profile_picture'),
				'admin_address' => $this->input->post('admin_address'),
            );
            
            $admin_login_id = $this->Admin_login_model->add_admin_login($params);
            redirect('admin_login/index');
        }
        else
        {            
            $data['_view'] = 'admin_login/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a admin_login
     */
    function edit($id)
    {   
        // check if the admin_login exists before trying to edit it
        $data['admin_login'] = $this->Admin_login_model->get_admin_login($id);
        
        if(isset($data['admin_login']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'admin_password' => $this->input->post('admin_password'),
					'admin_username' => $this->input->post('admin_username'),
					'first_name' => $this->input->post('first_name'),
					'last_name' => $this->input->post('last_name'),
					'admin_email' => $this->input->post('admin_email'),
					'admin_contactus' => $this->input->post('admin_contactus'),
					'admin_fax' => $this->input->post('admin_fax'),
					'site_status' => $this->input->post('site_status'),
					'admin_address2' => $this->input->post('admin_address2'),
					'admin_address3' => $this->input->post('admin_address3'),
					'admin_country' => $this->input->post('admin_country'),
					'admin_state' => $this->input->post('admin_state'),
					'admin_city' => $this->input->post('admin_city'),
					'admin_postcode' => $this->input->post('admin_postcode'),
					'profile_picture' => $this->input->post('profile_picture'),
					'admin_address' => $this->input->post('admin_address'),
                );

                $this->Admin_login_model->update_admin_login($id,$params);            
                redirect('admin_login/index');
            }
            else
            {
                $data['_view'] = 'admin_login/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The admin_login you are trying to edit does not exist.');
    } 

    /*
     * Deleting admin_login
     */
    function remove($id)
    {
        $admin_login = $this->Admin_login_model->get_admin_login($id);

        // check if the admin_login exists before trying to delete it
        if(isset($admin_login['id']))
        {
            $this->Admin_login_model->delete_admin_login($id);
            redirect('admin_login/index');
        }
        else
            show_error('The admin_login you are trying to delete does not exist.');
    }
    
}
