<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_faq extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_faq_model');
    } 

    /*
     * Listing of tbl_faq
     */
    function index()
    {
        $data['tbl_faq'] = $this->Tbl_faq_model->get_all_tbl_faq();
        
        $data['_view'] = 'tbl_faq/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_faq
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'faq_type' => $this->input->post('faq_type'),
				'fk_faq_category_id' => $this->input->post('fk_faq_category_id'),
				'faq_question' => $this->input->post('faq_question'),
				'faq_status' => $this->input->post('faq_status'),
				'faq_answer' => $this->input->post('faq_answer'),
            );
            
            $tbl_faq_id = $this->Tbl_faq_model->add_tbl_faq($params);
            redirect('tbl_faq/index');
        }
        else
        {            
            $data['_view'] = 'tbl_faq/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_faq
     */
    function edit($faq_id)
    {   
        // check if the tbl_faq exists before trying to edit it
        $data['tbl_faq'] = $this->Tbl_faq_model->get_tbl_faq($faq_id);
        
        if(isset($data['tbl_faq']['faq_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'faq_type' => $this->input->post('faq_type'),
					'fk_faq_category_id' => $this->input->post('fk_faq_category_id'),
					'faq_question' => $this->input->post('faq_question'),
					'faq_status' => $this->input->post('faq_status'),
					'faq_answer' => $this->input->post('faq_answer'),
                );

                $this->Tbl_faq_model->update_tbl_faq($faq_id,$params);            
                redirect('tbl_faq/index');
            }
            else
            {
                $data['_view'] = 'tbl_faq/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_faq you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_faq
     */
    function remove($faq_id)
    {
        $tbl_faq = $this->Tbl_faq_model->get_tbl_faq($faq_id);

        // check if the tbl_faq exists before trying to delete it
        if(isset($tbl_faq['faq_id']))
        {
            $this->Tbl_faq_model->delete_tbl_faq($faq_id);
            redirect('tbl_faq/index');
        }
        else
            show_error('The tbl_faq you are trying to delete does not exist.');
    }
    
}
