<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_booking extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_booking_model');
    } 

    /*
     * Listing of tbl_booking
     */
    function index()
    {
        $data['tbl_booking'] = $this->Tbl_booking_model->get_all_tbl_booking();
        
        $data['_view'] = 'tbl_booking/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_booking
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'payment_method' => $this->input->post('payment_method'),
				'admin_seen_status' => $this->input->post('admin_seen_status'),
				'incremental_value' => $this->input->post('incremental_value'),
				'db_insert_date' => $this->input->post('db_insert_date'),
				'txn_id' => $this->input->post('txn_id'),
				'balance_transaction' => $this->input->post('balance_transaction'),
				'user_id' => $this->input->post('user_id'),
				'walkin_id' => $this->input->post('walkin_id'),
				'booking_type' => $this->input->post('booking_type'),
				'business_id' => $this->input->post('business_id'),
				'service_id' => $this->input->post('service_id'),
				'tattoo_id' => $this->input->post('tattoo_id'),
				'start_time' => $this->input->post('start_time'),
				'end_time' => $this->input->post('end_time'),
				'availibility_id' => $this->input->post('availibility_id'),
				'booking_no' => $this->input->post('booking_no'),
				'booking_date' => $this->input->post('booking_date'),
				'staff_id' => $this->input->post('staff_id'),
				'service_name' => $this->input->post('service_name'),
				'service_price' => $this->input->post('service_price'),
				'esitmated_amount' => $this->input->post('esitmated_amount'),
				'booking_status' => $this->input->post('booking_status'),
				'is_refunded' => $this->input->post('is_refunded'),
				'walkin_status' => $this->input->post('walkin_status'),
				'reference_tattoo' => $this->input->post('reference_tattoo'),
				'previous_tattoo_img' => $this->input->post('previous_tattoo_img'),
				'cover_up' => $this->input->post('cover_up'),
				'booking_desc' => $this->input->post('booking_desc'),
				'medical_condition' => $this->input->post('medical_condition'),
				'medical_description' => $this->input->post('medical_description'),
				'stripeResponse' => $this->input->post('stripeResponse'),
				'cancellation_reason' => $this->input->post('cancellation_reason'),
				'reschedule_reason' => $this->input->post('reschedule_reason'),
            );
            
            $tbl_booking_id = $this->Tbl_booking_model->add_tbl_booking($params);
            redirect('tbl_booking/index');
        }
        else
        {            
            $data['_view'] = 'tbl_booking/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_booking
     */
    function edit($id)
    {   
        // check if the tbl_booking exists before trying to edit it
        $data['tbl_booking'] = $this->Tbl_booking_model->get_tbl_booking($id);
        
        if(isset($data['tbl_booking']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'payment_method' => $this->input->post('payment_method'),
					'admin_seen_status' => $this->input->post('admin_seen_status'),
					'incremental_value' => $this->input->post('incremental_value'),
					'db_insert_date' => $this->input->post('db_insert_date'),
					'txn_id' => $this->input->post('txn_id'),
					'balance_transaction' => $this->input->post('balance_transaction'),
					'user_id' => $this->input->post('user_id'),
					'walkin_id' => $this->input->post('walkin_id'),
					'booking_type' => $this->input->post('booking_type'),
					'business_id' => $this->input->post('business_id'),
					'service_id' => $this->input->post('service_id'),
					'tattoo_id' => $this->input->post('tattoo_id'),
					'start_time' => $this->input->post('start_time'),
					'end_time' => $this->input->post('end_time'),
					'availibility_id' => $this->input->post('availibility_id'),
					'booking_no' => $this->input->post('booking_no'),
					'booking_date' => $this->input->post('booking_date'),
					'staff_id' => $this->input->post('staff_id'),
					'service_name' => $this->input->post('service_name'),
					'service_price' => $this->input->post('service_price'),
					'esitmated_amount' => $this->input->post('esitmated_amount'),
					'booking_status' => $this->input->post('booking_status'),
					'is_refunded' => $this->input->post('is_refunded'),
					'walkin_status' => $this->input->post('walkin_status'),
					'reference_tattoo' => $this->input->post('reference_tattoo'),
					'previous_tattoo_img' => $this->input->post('previous_tattoo_img'),
					'cover_up' => $this->input->post('cover_up'),
					'booking_desc' => $this->input->post('booking_desc'),
					'medical_condition' => $this->input->post('medical_condition'),
					'medical_description' => $this->input->post('medical_description'),
					'stripeResponse' => $this->input->post('stripeResponse'),
					'cancellation_reason' => $this->input->post('cancellation_reason'),
					'reschedule_reason' => $this->input->post('reschedule_reason'),
                );

                $this->Tbl_booking_model->update_tbl_booking($id,$params);            
                redirect('tbl_booking/index');
            }
            else
            {
                $data['_view'] = 'tbl_booking/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_booking you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_booking
     */
    function remove($id)
    {
        $tbl_booking = $this->Tbl_booking_model->get_tbl_booking($id);

        // check if the tbl_booking exists before trying to delete it
        if(isset($tbl_booking['id']))
        {
            $this->Tbl_booking_model->delete_tbl_booking($id);
            redirect('tbl_booking/index');
        }
        else
            show_error('The tbl_booking you are trying to delete does not exist.');
    }
    
}
