<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_team_member extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_team_member_model');
    } 

    /*
     * Listing of tbl_team_members
     */
    function index()
    {
        $data['tbl_team_members'] = $this->Tbl_team_member_model->get_all_tbl_team_members();
        
        $data['_view'] = 'tbl_team_member/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_team_member
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'member_name' => $this->input->post('member_name'),
				'member_job_role' => $this->input->post('member_job_role'),
				'member_img' => $this->input->post('member_img'),
				'member_status' => $this->input->post('member_status'),
				'member_desc' => $this->input->post('member_desc'),
            );
            
            $tbl_team_member_id = $this->Tbl_team_member_model->add_tbl_team_member($params);
            redirect('tbl_team_member/index');
        }
        else
        {            
            $data['_view'] = 'tbl_team_member/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_team_member
     */
    function edit($member_id)
    {   
        // check if the tbl_team_member exists before trying to edit it
        $data['tbl_team_member'] = $this->Tbl_team_member_model->get_tbl_team_member($member_id);
        
        if(isset($data['tbl_team_member']['member_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'member_name' => $this->input->post('member_name'),
					'member_job_role' => $this->input->post('member_job_role'),
					'member_img' => $this->input->post('member_img'),
					'member_status' => $this->input->post('member_status'),
					'member_desc' => $this->input->post('member_desc'),
                );

                $this->Tbl_team_member_model->update_tbl_team_member($member_id,$params);            
                redirect('tbl_team_member/index');
            }
            else
            {
                $data['_view'] = 'tbl_team_member/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_team_member you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_team_member
     */
    function remove($member_id)
    {
        $tbl_team_member = $this->Tbl_team_member_model->get_tbl_team_member($member_id);

        // check if the tbl_team_member exists before trying to delete it
        if(isset($tbl_team_member['member_id']))
        {
            $this->Tbl_team_member_model->delete_tbl_team_member($member_id);
            redirect('tbl_team_member/index');
        }
        else
            show_error('The tbl_team_member you are trying to delete does not exist.');
    }
    
}
