<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_color extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_color_model');
    } 

    /*
     * Listing of tbl_color
     */
    function index()
    {
        $data['tbl_color'] = $this->Tbl_color_model->get_all_tbl_color();
        
        $data['_view'] = 'tbl_color/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_color
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'color_name' => $this->input->post('color_name'),
				'color_slug' => $this->input->post('color_slug'),
				'color_status' => $this->input->post('color_status'),
				'is_delete' => $this->input->post('is_delete'),
            );
            
            $tbl_color_id = $this->Tbl_color_model->add_tbl_color($params);
            redirect('tbl_color/index');
        }
        else
        {            
            $data['_view'] = 'tbl_color/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_color
     */
    function edit($color_id)
    {   
        // check if the tbl_color exists before trying to edit it
        $data['tbl_color'] = $this->Tbl_color_model->get_tbl_color($color_id);
        
        if(isset($data['tbl_color']['color_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'color_name' => $this->input->post('color_name'),
					'color_slug' => $this->input->post('color_slug'),
					'color_status' => $this->input->post('color_status'),
					'is_delete' => $this->input->post('is_delete'),
                );

                $this->Tbl_color_model->update_tbl_color($color_id,$params);            
                redirect('tbl_color/index');
            }
            else
            {
                $data['_view'] = 'tbl_color/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_color you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_color
     */
    function remove($color_id)
    {
        $tbl_color = $this->Tbl_color_model->get_tbl_color($color_id);

        // check if the tbl_color exists before trying to delete it
        if(isset($tbl_color['color_id']))
        {
            $this->Tbl_color_model->delete_tbl_color($color_id);
            redirect('tbl_color/index');
        }
        else
            show_error('The tbl_color you are trying to delete does not exist.');
    }
    
}
