<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_photo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_business_photo_model');
    } 

    /*
     * Listing of tbl_business_photos
     */
    function index()
    {
        $data['tbl_business_photos'] = $this->Tbl_business_photo_model->get_all_tbl_business_photos();
        
        $data['_view'] = 'tbl_business_photo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_business_photo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_business_id' => $this->input->post('fk_business_id'),
				'name' => $this->input->post('name'),
				'photo_name' => $this->input->post('photo_name'),
            );
            
            $tbl_business_photo_id = $this->Tbl_business_photo_model->add_tbl_business_photo($params);
            redirect('tbl_business_photo/index');
        }
        else
        {            
            $data['_view'] = 'tbl_business_photo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_business_photo
     */
    function edit($photo_id)
    {   
        // check if the tbl_business_photo exists before trying to edit it
        $data['tbl_business_photo'] = $this->Tbl_business_photo_model->get_tbl_business_photo($photo_id);
        
        if(isset($data['tbl_business_photo']['photo_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_business_id' => $this->input->post('fk_business_id'),
					'name' => $this->input->post('name'),
					'photo_name' => $this->input->post('photo_name'),
                );

                $this->Tbl_business_photo_model->update_tbl_business_photo($photo_id,$params);            
                redirect('tbl_business_photo/index');
            }
            else
            {
                $data['_view'] = 'tbl_business_photo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_business_photo you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_business_photo
     */
    function remove($photo_id)
    {
        $tbl_business_photo = $this->Tbl_business_photo_model->get_tbl_business_photo($photo_id);

        // check if the tbl_business_photo exists before trying to delete it
        if(isset($tbl_business_photo['photo_id']))
        {
            $this->Tbl_business_photo_model->delete_tbl_business_photo($photo_id);
            redirect('tbl_business_photo/index');
        }
        else
            show_error('The tbl_business_photo you are trying to delete does not exist.');
    }
    
}
