<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_banner_master extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_banner_master_model');
    } 

    /*
     * Listing of tbl_banner_master
     */
    function index()
    {
        $data['tbl_banner_master'] = $this->Tbl_banner_master_model->get_all_tbl_banner_master();
        
        $data['_view'] = 'tbl_banner_master/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_banner_master
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'banner_title' => $this->input->post('banner_title'),
				'banner_image' => $this->input->post('banner_image'),
				'banner_order' => $this->input->post('banner_order'),
            );
            
            $tbl_banner_master_id = $this->Tbl_banner_master_model->add_tbl_banner_master($params);
            redirect('tbl_banner_master/index');
        }
        else
        {            
            $data['_view'] = 'tbl_banner_master/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_banner_master
     */
    function edit($banner_id)
    {   
        // check if the tbl_banner_master exists before trying to edit it
        $data['tbl_banner_master'] = $this->Tbl_banner_master_model->get_tbl_banner_master($banner_id);
        
        if(isset($data['tbl_banner_master']['banner_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'banner_title' => $this->input->post('banner_title'),
					'banner_image' => $this->input->post('banner_image'),
					'banner_order' => $this->input->post('banner_order'),
                );

                $this->Tbl_banner_master_model->update_tbl_banner_master($banner_id,$params);            
                redirect('tbl_banner_master/index');
            }
            else
            {
                $data['_view'] = 'tbl_banner_master/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_banner_master you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_banner_master
     */
    function remove($banner_id)
    {
        $tbl_banner_master = $this->Tbl_banner_master_model->get_tbl_banner_master($banner_id);

        // check if the tbl_banner_master exists before trying to delete it
        if(isset($tbl_banner_master['banner_id']))
        {
            $this->Tbl_banner_master_model->delete_tbl_banner_master($banner_id);
            redirect('tbl_banner_master/index');
        }
        else
            show_error('The tbl_banner_master you are trying to delete does not exist.');
    }
    
}
