<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_newsletter_master extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_newsletter_master_model');
    } 

    /*
     * Listing of tbl_newsletter_master
     */
    function index()
    {
        $data['tbl_newsletter_master'] = $this->Tbl_newsletter_master_model->get_all_tbl_newsletter_master();
        
        $data['_view'] = 'tbl_newsletter_master/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_newsletter_master
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'news_title' => $this->input->post('news_title'),
				'newsletter_subject' => $this->input->post('newsletter_subject'),
				'news_status' => $this->input->post('news_status'),
				'news_description' => $this->input->post('news_description'),
            );
            
            $tbl_newsletter_master_id = $this->Tbl_newsletter_master_model->add_tbl_newsletter_master($params);
            redirect('tbl_newsletter_master/index');
        }
        else
        {            
            $data['_view'] = 'tbl_newsletter_master/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_newsletter_master
     */
    function edit($news_id)
    {   
        // check if the tbl_newsletter_master exists before trying to edit it
        $data['tbl_newsletter_master'] = $this->Tbl_newsletter_master_model->get_tbl_newsletter_master($news_id);
        
        if(isset($data['tbl_newsletter_master']['news_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'news_title' => $this->input->post('news_title'),
					'newsletter_subject' => $this->input->post('newsletter_subject'),
					'news_status' => $this->input->post('news_status'),
					'news_description' => $this->input->post('news_description'),
                );

                $this->Tbl_newsletter_master_model->update_tbl_newsletter_master($news_id,$params);            
                redirect('tbl_newsletter_master/index');
            }
            else
            {
                $data['_view'] = 'tbl_newsletter_master/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_newsletter_master you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_newsletter_master
     */
    function remove($news_id)
    {
        $tbl_newsletter_master = $this->Tbl_newsletter_master_model->get_tbl_newsletter_master($news_id);

        // check if the tbl_newsletter_master exists before trying to delete it
        if(isset($tbl_newsletter_master['news_id']))
        {
            $this->Tbl_newsletter_master_model->delete_tbl_newsletter_master($news_id);
            redirect('tbl_newsletter_master/index');
        }
        else
            show_error('The tbl_newsletter_master you are trying to delete does not exist.');
    }
    
}
