<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_my_style extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_my_style_model');
    } 

    /*
     * Listing of tbl_my_styles
     */
    function index()
    {
        $data['tbl_my_styles'] = $this->Tbl_my_style_model->get_all_tbl_my_styles();
        
        $data['_view'] = 'tbl_my_style/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_my_style
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'style_id' => $this->input->post('style_id'),
				'business_user_id' => $this->input->post('business_user_id'),
            );
            
            $tbl_my_style_id = $this->Tbl_my_style_model->add_tbl_my_style($params);
            redirect('tbl_my_style/index');
        }
        else
        {            
            $data['_view'] = 'tbl_my_style/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_my_style
     */
    function edit($id)
    {   
        // check if the tbl_my_style exists before trying to edit it
        $data['tbl_my_style'] = $this->Tbl_my_style_model->get_tbl_my_style($id);
        
        if(isset($data['tbl_my_style']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'style_id' => $this->input->post('style_id'),
					'business_user_id' => $this->input->post('business_user_id'),
                );

                $this->Tbl_my_style_model->update_tbl_my_style($id,$params);            
                redirect('tbl_my_style/index');
            }
            else
            {
                $data['_view'] = 'tbl_my_style/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_my_style you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_my_style
     */
    function remove($id)
    {
        $tbl_my_style = $this->Tbl_my_style_model->get_tbl_my_style($id);

        // check if the tbl_my_style exists before trying to delete it
        if(isset($tbl_my_style['id']))
        {
            $this->Tbl_my_style_model->delete_tbl_my_style($id);
            redirect('tbl_my_style/index');
        }
        else
            show_error('The tbl_my_style you are trying to delete does not exist.');
    }
    
}
