<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_staff_location_hour extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_staff_location_hour_model');
    } 

    /*
     * Listing of tbl_staff_location_hours
     */
    function index()
    {
        $data['tbl_staff_location_hours'] = $this->Tbl_staff_location_hour_model->get_all_tbl_staff_location_hours();
        
        $data['_view'] = 'tbl_staff_location_hour/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_staff_location_hour
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_location_id' => $this->input->post('fk_location_id'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'day_of_week' => $this->input->post('day_of_week'),
				'start_time' => $this->input->post('start_time'),
				'end_time' => $this->input->post('end_time'),
				'by_appointment' => $this->input->post('by_appointment'),
				'in_out' => $this->input->post('in_out'),
				'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
				'booked_count' => $this->input->post('booked_count'),
				'fk_staff_id' => $this->input->post('fk_staff_id'),
            );
            
            $tbl_staff_location_hour_id = $this->Tbl_staff_location_hour_model->add_tbl_staff_location_hour($params);
            redirect('tbl_staff_location_hour/index');
        }
        else
        {            
            $data['_view'] = 'tbl_staff_location_hour/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_staff_location_hour
     */
    function edit($location_hours_id)
    {   
        // check if the tbl_staff_location_hour exists before trying to edit it
        $data['tbl_staff_location_hour'] = $this->Tbl_staff_location_hour_model->get_tbl_staff_location_hour($location_hours_id);
        
        if(isset($data['tbl_staff_location_hour']['location_hours_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_location_id' => $this->input->post('fk_location_id'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'day_of_week' => $this->input->post('day_of_week'),
					'start_time' => $this->input->post('start_time'),
					'end_time' => $this->input->post('end_time'),
					'by_appointment' => $this->input->post('by_appointment'),
					'in_out' => $this->input->post('in_out'),
					'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
					'booked_count' => $this->input->post('booked_count'),
					'fk_staff_id' => $this->input->post('fk_staff_id'),
                );

                $this->Tbl_staff_location_hour_model->update_tbl_staff_location_hour($location_hours_id,$params);            
                redirect('tbl_staff_location_hour/index');
            }
            else
            {
                $data['_view'] = 'tbl_staff_location_hour/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_staff_location_hour you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_staff_location_hour
     */
    function remove($location_hours_id)
    {
        $tbl_staff_location_hour = $this->Tbl_staff_location_hour_model->get_tbl_staff_location_hour($location_hours_id);

        // check if the tbl_staff_location_hour exists before trying to delete it
        if(isset($tbl_staff_location_hour['location_hours_id']))
        {
            $this->Tbl_staff_location_hour_model->delete_tbl_staff_location_hour($location_hours_id);
            redirect('tbl_staff_location_hour/index');
        }
        else
            show_error('The tbl_staff_location_hour you are trying to delete does not exist.');
    }
    
}
