<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_promocode_master extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_promocode_master_model');
    } 

    /*
     * Listing of tbl_promocode_master
     */
    function index()
    {
        $data['tbl_promocode_master'] = $this->Tbl_promocode_master_model->get_all_tbl_promocode_master();
        
        $data['_view'] = 'tbl_promocode_master/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_promocode_master
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'promo_code' => $this->input->post('promo_code'),
				'promo_discount' => $this->input->post('promo_discount'),
				'promo_exp_date' => $this->input->post('promo_exp_date'),
            );
            
            $tbl_promocode_master_id = $this->Tbl_promocode_master_model->add_tbl_promocode_master($params);
            redirect('tbl_promocode_master/index');
        }
        else
        {            
            $data['_view'] = 'tbl_promocode_master/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_promocode_master
     */
    function edit($promo_id)
    {   
        // check if the tbl_promocode_master exists before trying to edit it
        $data['tbl_promocode_master'] = $this->Tbl_promocode_master_model->get_tbl_promocode_master($promo_id);
        
        if(isset($data['tbl_promocode_master']['promo_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'promo_code' => $this->input->post('promo_code'),
					'promo_discount' => $this->input->post('promo_discount'),
					'promo_exp_date' => $this->input->post('promo_exp_date'),
                );

                $this->Tbl_promocode_master_model->update_tbl_promocode_master($promo_id,$params);            
                redirect('tbl_promocode_master/index');
            }
            else
            {
                $data['_view'] = 'tbl_promocode_master/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_promocode_master you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_promocode_master
     */
    function remove($promo_id)
    {
        $tbl_promocode_master = $this->Tbl_promocode_master_model->get_tbl_promocode_master($promo_id);

        // check if the tbl_promocode_master exists before trying to delete it
        if(isset($tbl_promocode_master['promo_id']))
        {
            $this->Tbl_promocode_master_model->delete_tbl_promocode_master($promo_id);
            redirect('tbl_promocode_master/index');
        }
        else
            show_error('The tbl_promocode_master you are trying to delete does not exist.');
    }
    
}
