<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_service_time extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_service_time_model');
    } 

    /*
     * Listing of tbl_service_time
     */
    function index()
    {
        $data['tbl_service_time'] = $this->Tbl_service_time_model->get_all_tbl_service_time();
        
        $data['_view'] = 'tbl_service_time/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_service_time
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_business_id' => $this->input->post('fk_business_id'),
				'service_time_count' => $this->input->post('service_time_count'),
				'service_time' => $this->input->post('service_time'),
            );
            
            $tbl_service_time_id = $this->Tbl_service_time_model->add_tbl_service_time($params);
            redirect('tbl_service_time/index');
        }
        else
        {            
            $data['_view'] = 'tbl_service_time/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_service_time
     */
    function edit($time_id)
    {   
        // check if the tbl_service_time exists before trying to edit it
        $data['tbl_service_time'] = $this->Tbl_service_time_model->get_tbl_service_time($time_id);
        
        if(isset($data['tbl_service_time']['time_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_business_id' => $this->input->post('fk_business_id'),
					'service_time_count' => $this->input->post('service_time_count'),
					'service_time' => $this->input->post('service_time'),
                );

                $this->Tbl_service_time_model->update_tbl_service_time($time_id,$params);            
                redirect('tbl_service_time/index');
            }
            else
            {
                $data['_view'] = 'tbl_service_time/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_service_time you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_service_time
     */
    function remove($time_id)
    {
        $tbl_service_time = $this->Tbl_service_time_model->get_tbl_service_time($time_id);

        // check if the tbl_service_time exists before trying to delete it
        if(isset($tbl_service_time['time_id']))
        {
            $this->Tbl_service_time_model->delete_tbl_service_time($time_id);
            redirect('tbl_service_time/index');
        }
        else
            show_error('The tbl_service_time you are trying to delete does not exist.');
    }
    
}
