<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_review_rating extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_review_rating_model');
    } 

    /*
     * Listing of tbl_review_ratings
     */
    function index()
    {
        $data['tbl_review_ratings'] = $this->Tbl_review_rating_model->get_all_tbl_review_ratings();
        
        $data['_view'] = 'tbl_review_rating/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_review_rating
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'rating_user_id' => $this->input->post('rating_user_id'),
				'business_id' => $this->input->post('business_id'),
				'professional' => $this->input->post('professional'),
				'hard_worker' => $this->input->post('hard_worker'),
				'excellent_hire' => $this->input->post('excellent_hire'),
				'trust_worthy' => $this->input->post('trust_worthy'),
				'friendly' => $this->input->post('friendly'),
				'overall_rating' => $this->input->post('overall_rating'),
				'review_msg' => $this->input->post('review_msg'),
				'review_status' => $this->input->post('review_status'),
				'is_delete' => $this->input->post('is_delete'),
				'rating_date' => $this->input->post('rating_date'),
            );
            
            $tbl_review_rating_id = $this->Tbl_review_rating_model->add_tbl_review_rating($params);
            redirect('tbl_review_rating/index');
        }
        else
        {            
            $data['_view'] = 'tbl_review_rating/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_review_rating
     */
    function edit($id)
    {   
        // check if the tbl_review_rating exists before trying to edit it
        $data['tbl_review_rating'] = $this->Tbl_review_rating_model->get_tbl_review_rating($id);
        
        if(isset($data['tbl_review_rating']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'rating_user_id' => $this->input->post('rating_user_id'),
					'business_id' => $this->input->post('business_id'),
					'professional' => $this->input->post('professional'),
					'hard_worker' => $this->input->post('hard_worker'),
					'excellent_hire' => $this->input->post('excellent_hire'),
					'trust_worthy' => $this->input->post('trust_worthy'),
					'friendly' => $this->input->post('friendly'),
					'overall_rating' => $this->input->post('overall_rating'),
					'review_msg' => $this->input->post('review_msg'),
					'review_status' => $this->input->post('review_status'),
					'is_delete' => $this->input->post('is_delete'),
					'rating_date' => $this->input->post('rating_date'),
                );

                $this->Tbl_review_rating_model->update_tbl_review_rating($id,$params);            
                redirect('tbl_review_rating/index');
            }
            else
            {
                $data['_view'] = 'tbl_review_rating/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_review_rating you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_review_rating
     */
    function remove($id)
    {
        $tbl_review_rating = $this->Tbl_review_rating_model->get_tbl_review_rating($id);

        // check if the tbl_review_rating exists before trying to delete it
        if(isset($tbl_review_rating['id']))
        {
            $this->Tbl_review_rating_model->delete_tbl_review_rating($id);
            redirect('tbl_review_rating/index');
        }
        else
            show_error('The tbl_review_rating you are trying to delete does not exist.');
    }
    
}
