<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_tattoos_staff extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_tattoos_staff_model');
    } 

    /*
     * Listing of tbl_tattoos_staff
     */
    function index()
    {
        $data['tbl_tattoos_staff'] = $this->Tbl_tattoos_staff_model->get_all_tbl_tattoos_staff();
        
        $data['_view'] = 'tbl_tattoos_staff/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_tattoos_staff
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'studio_tattoos_id' => $this->input->post('studio_tattoos_id'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'fk_staff_id' => $this->input->post('fk_staff_id'),
            );
            
            $tbl_tattoos_staff_id = $this->Tbl_tattoos_staff_model->add_tbl_tattoos_staff($params);
            redirect('tbl_tattoos_staff/index');
        }
        else
        {            
            $data['_view'] = 'tbl_tattoos_staff/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_tattoos_staff
     */
    function edit($id)
    {   
        // check if the tbl_tattoos_staff exists before trying to edit it
        $data['tbl_tattoos_staff'] = $this->Tbl_tattoos_staff_model->get_tbl_tattoos_staff($id);
        
        if(isset($data['tbl_tattoos_staff']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'studio_tattoos_id' => $this->input->post('studio_tattoos_id'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'fk_staff_id' => $this->input->post('fk_staff_id'),
                );

                $this->Tbl_tattoos_staff_model->update_tbl_tattoos_staff($id,$params);            
                redirect('tbl_tattoos_staff/index');
            }
            else
            {
                $data['_view'] = 'tbl_tattoos_staff/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_tattoos_staff you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_tattoos_staff
     */
    function remove($id)
    {
        $tbl_tattoos_staff = $this->Tbl_tattoos_staff_model->get_tbl_tattoos_staff($id);

        // check if the tbl_tattoos_staff exists before trying to delete it
        if(isset($tbl_tattoos_staff['id']))
        {
            $this->Tbl_tattoos_staff_model->delete_tbl_tattoos_staff($id);
            redirect('tbl_tattoos_staff/index');
        }
        else
            show_error('The tbl_tattoos_staff you are trying to delete does not exist.');
    }
    
}
