<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_user_address_master extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_user_address_master_model');
    } 

    /*
     * Listing of tbl_user_address_master
     */
    function index()
    {
        $data['tbl_user_address_master'] = $this->Tbl_user_address_master_model->get_all_tbl_user_address_master();
        
        $data['_view'] = 'tbl_user_address_master/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_user_address_master
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_user_id' => $this->input->post('fk_user_id'),
				'street_1' => $this->input->post('street_1'),
				'street_2' => $this->input->post('street_2'),
				'street_3' => $this->input->post('street_3'),
				'country' => $this->input->post('country'),
				'district' => $this->input->post('district'),
				'city' => $this->input->post('city'),
				'zipcode' => $this->input->post('zipcode'),
				'is_active' => $this->input->post('is_active'),
            );
            
            $tbl_user_address_master_id = $this->Tbl_user_address_master_model->add_tbl_user_address_master($params);
            redirect('tbl_user_address_master/index');
        }
        else
        {            
            $data['_view'] = 'tbl_user_address_master/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_user_address_master
     */
    function edit($address_id)
    {   
        // check if the tbl_user_address_master exists before trying to edit it
        $data['tbl_user_address_master'] = $this->Tbl_user_address_master_model->get_tbl_user_address_master($address_id);
        
        if(isset($data['tbl_user_address_master']['address_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_user_id' => $this->input->post('fk_user_id'),
					'street_1' => $this->input->post('street_1'),
					'street_2' => $this->input->post('street_2'),
					'street_3' => $this->input->post('street_3'),
					'country' => $this->input->post('country'),
					'district' => $this->input->post('district'),
					'city' => $this->input->post('city'),
					'zipcode' => $this->input->post('zipcode'),
					'is_active' => $this->input->post('is_active'),
                );

                $this->Tbl_user_address_master_model->update_tbl_user_address_master($address_id,$params);            
                redirect('tbl_user_address_master/index');
            }
            else
            {
                $data['_view'] = 'tbl_user_address_master/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_user_address_master you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_user_address_master
     */
    function remove($address_id)
    {
        $tbl_user_address_master = $this->Tbl_user_address_master_model->get_tbl_user_address_master($address_id);

        // check if the tbl_user_address_master exists before trying to delete it
        if(isset($tbl_user_address_master['address_id']))
        {
            $this->Tbl_user_address_master_model->delete_tbl_user_address_master($address_id);
            redirect('tbl_user_address_master/index');
        }
        else
            show_error('The tbl_user_address_master you are trying to delete does not exist.');
    }
    
}
