<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_mailing_addres extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_business_mailing_addres_model');
    } 

    /*
     * Listing of tbl_business_mailing_address
     */
    function index()
    {
        $data['tbl_business_mailing_address'] = $this->Tbl_business_mailing_addres_model->get_all_tbl_business_mailing_address();
        
        $data['_view'] = 'tbl_business_mailing_addres/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_business_mailing_addres
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_business_id' => $this->input->post('fk_business_id'),
				'recipient_name' => $this->input->post('recipient_name'),
				'giolocation' => $this->input->post('giolocation'),
				'street_address' => $this->input->post('street_address'),
				'street_address2' => $this->input->post('street_address2'),
				'street_address3' => $this->input->post('street_address3'),
				'city' => $this->input->post('city'),
				'district' => $this->input->post('district'),
				'country' => $this->input->post('country'),
				'zip' => $this->input->post('zip'),
            );
            
            $tbl_business_mailing_addres_id = $this->Tbl_business_mailing_addres_model->add_tbl_business_mailing_addres($params);
            redirect('tbl_business_mailing_addres/index');
        }
        else
        {            
            $data['_view'] = 'tbl_business_mailing_addres/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_business_mailing_addres
     */
    function edit($mailing_id)
    {   
        // check if the tbl_business_mailing_addres exists before trying to edit it
        $data['tbl_business_mailing_addres'] = $this->Tbl_business_mailing_addres_model->get_tbl_business_mailing_addres($mailing_id);
        
        if(isset($data['tbl_business_mailing_addres']['mailing_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_business_id' => $this->input->post('fk_business_id'),
					'recipient_name' => $this->input->post('recipient_name'),
					'giolocation' => $this->input->post('giolocation'),
					'street_address' => $this->input->post('street_address'),
					'street_address2' => $this->input->post('street_address2'),
					'street_address3' => $this->input->post('street_address3'),
					'city' => $this->input->post('city'),
					'district' => $this->input->post('district'),
					'country' => $this->input->post('country'),
					'zip' => $this->input->post('zip'),
                );

                $this->Tbl_business_mailing_addres_model->update_tbl_business_mailing_addres($mailing_id,$params);            
                redirect('tbl_business_mailing_addres/index');
            }
            else
            {
                $data['_view'] = 'tbl_business_mailing_addres/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_business_mailing_addres you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_business_mailing_addres
     */
    function remove($mailing_id)
    {
        $tbl_business_mailing_addres = $this->Tbl_business_mailing_addres_model->get_tbl_business_mailing_addres($mailing_id);

        // check if the tbl_business_mailing_addres exists before trying to delete it
        if(isset($tbl_business_mailing_addres['mailing_id']))
        {
            $this->Tbl_business_mailing_addres_model->delete_tbl_business_mailing_addres($mailing_id);
            redirect('tbl_business_mailing_addres/index');
        }
        else
            show_error('The tbl_business_mailing_addres you are trying to delete does not exist.');
    }
    
}
