<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_newsletter_subscriber extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_newsletter_subscriber_model');
    } 

    /*
     * Listing of tbl_newsletter_subscriber
     */
    function index()
    {
        $data['tbl_newsletter_subscriber'] = $this->Tbl_newsletter_subscriber_model->get_all_tbl_newsletter_subscriber();
        
        $data['_view'] = 'tbl_newsletter_subscriber/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_newsletter_subscriber
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'sub_email' => $this->input->post('sub_email'),
				'sub_name' => $this->input->post('sub_name'),
				'sub_zipcode' => $this->input->post('sub_zipcode'),
				'sub_city' => $this->input->post('sub_city'),
				'sub_status' => $this->input->post('sub_status'),
            );
            
            $tbl_newsletter_subscriber_id = $this->Tbl_newsletter_subscriber_model->add_tbl_newsletter_subscriber($params);
            redirect('tbl_newsletter_subscriber/index');
        }
        else
        {            
            $data['_view'] = 'tbl_newsletter_subscriber/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_newsletter_subscriber
     */
    function edit($sub_id)
    {   
        // check if the tbl_newsletter_subscriber exists before trying to edit it
        $data['tbl_newsletter_subscriber'] = $this->Tbl_newsletter_subscriber_model->get_tbl_newsletter_subscriber($sub_id);
        
        if(isset($data['tbl_newsletter_subscriber']['sub_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'sub_email' => $this->input->post('sub_email'),
					'sub_name' => $this->input->post('sub_name'),
					'sub_zipcode' => $this->input->post('sub_zipcode'),
					'sub_city' => $this->input->post('sub_city'),
					'sub_status' => $this->input->post('sub_status'),
                );

                $this->Tbl_newsletter_subscriber_model->update_tbl_newsletter_subscriber($sub_id,$params);            
                redirect('tbl_newsletter_subscriber/index');
            }
            else
            {
                $data['_view'] = 'tbl_newsletter_subscriber/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_newsletter_subscriber you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_newsletter_subscriber
     */
    function remove($sub_id)
    {
        $tbl_newsletter_subscriber = $this->Tbl_newsletter_subscriber_model->get_tbl_newsletter_subscriber($sub_id);

        // check if the tbl_newsletter_subscriber exists before trying to delete it
        if(isset($tbl_newsletter_subscriber['sub_id']))
        {
            $this->Tbl_newsletter_subscriber_model->delete_tbl_newsletter_subscriber($sub_id);
            redirect('tbl_newsletter_subscriber/index');
        }
        else
            show_error('The tbl_newsletter_subscriber you are trying to delete does not exist.');
    }
    
}
