<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_home_slider extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_home_slider_model');
    } 

    /*
     * Listing of tbl_home_slider
     */
    function index()
    {
        $data['tbl_home_slider'] = $this->Tbl_home_slider_model->get_all_tbl_home_slider();
        
        $data['_view'] = 'tbl_home_slider/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_home_slider
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'slider_image' => $this->input->post('slider_image'),
				'slider_link' => $this->input->post('slider_link'),
				'status' => $this->input->post('status'),
            );
            
            $tbl_home_slider_id = $this->Tbl_home_slider_model->add_tbl_home_slider($params);
            redirect('tbl_home_slider/index');
        }
        else
        {            
            $data['_view'] = 'tbl_home_slider/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_home_slider
     */
    function edit($slider_id)
    {   
        // check if the tbl_home_slider exists before trying to edit it
        $data['tbl_home_slider'] = $this->Tbl_home_slider_model->get_tbl_home_slider($slider_id);
        
        if(isset($data['tbl_home_slider']['slider_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'slider_image' => $this->input->post('slider_image'),
					'slider_link' => $this->input->post('slider_link'),
					'status' => $this->input->post('status'),
                );

                $this->Tbl_home_slider_model->update_tbl_home_slider($slider_id,$params);            
                redirect('tbl_home_slider/index');
            }
            else
            {
                $data['_view'] = 'tbl_home_slider/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_home_slider you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_home_slider
     */
    function remove($slider_id)
    {
        $tbl_home_slider = $this->Tbl_home_slider_model->get_tbl_home_slider($slider_id);

        // check if the tbl_home_slider exists before trying to delete it
        if(isset($tbl_home_slider['slider_id']))
        {
            $this->Tbl_home_slider_model->delete_tbl_home_slider($slider_id);
            redirect('tbl_home_slider/index');
        }
        else
            show_error('The tbl_home_slider you are trying to delete does not exist.');
    }
    
}
