<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_waiting_list extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_waiting_list_model');
    } 

    /*
     * Listing of tbl_waiting_list
     */
    function index()
    {
        $data['tbl_waiting_list'] = $this->Tbl_waiting_list_model->get_all_tbl_waiting_list();
        
        $data['_view'] = 'tbl_waiting_list/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_waiting_list
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'selected_date' => $this->input->post('selected_date'),
				'fk_user_id' => $this->input->post('fk_user_id'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'fk_location_id' => $this->input->post('fk_location_id'),
				'fk_location_hours_id' => $this->input->post('fk_location_hours_id'),
				'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
				'serv_start_time' => $this->input->post('serv_start_time'),
				'serv_end_time' => $this->input->post('serv_end_time'),
				'created_date' => $this->input->post('created_date'),
				'status' => $this->input->post('status'),
				'url_status' => $this->input->post('url_status'),
				'fk_staff_id' => $this->input->post('fk_staff_id'),
            );
            
            $tbl_waiting_list_id = $this->Tbl_waiting_list_model->add_tbl_waiting_list($params);
            redirect('tbl_waiting_list/index');
        }
        else
        {            
            $data['_view'] = 'tbl_waiting_list/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_waiting_list
     */
    function edit($waiting_id)
    {   
        // check if the tbl_waiting_list exists before trying to edit it
        $data['tbl_waiting_list'] = $this->Tbl_waiting_list_model->get_tbl_waiting_list($waiting_id);
        
        if(isset($data['tbl_waiting_list']['waiting_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'selected_date' => $this->input->post('selected_date'),
					'fk_user_id' => $this->input->post('fk_user_id'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'fk_location_id' => $this->input->post('fk_location_id'),
					'fk_location_hours_id' => $this->input->post('fk_location_hours_id'),
					'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
					'serv_start_time' => $this->input->post('serv_start_time'),
					'serv_end_time' => $this->input->post('serv_end_time'),
					'created_date' => $this->input->post('created_date'),
					'status' => $this->input->post('status'),
					'url_status' => $this->input->post('url_status'),
					'fk_staff_id' => $this->input->post('fk_staff_id'),
                );

                $this->Tbl_waiting_list_model->update_tbl_waiting_list($waiting_id,$params);            
                redirect('tbl_waiting_list/index');
            }
            else
            {
                $data['_view'] = 'tbl_waiting_list/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_waiting_list you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_waiting_list
     */
    function remove($waiting_id)
    {
        $tbl_waiting_list = $this->Tbl_waiting_list_model->get_tbl_waiting_list($waiting_id);

        // check if the tbl_waiting_list exists before trying to delete it
        if(isset($tbl_waiting_list['waiting_id']))
        {
            $this->Tbl_waiting_list_model->delete_tbl_waiting_list($waiting_id);
            redirect('tbl_waiting_list/index');
        }
        else
            show_error('The tbl_waiting_list you are trying to delete does not exist.');
    }
    
}
