<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_staff extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_business_staff_model');
    } 

    /*
     * Listing of tbl_business_staff
     */
    function index()
    {
        $data['tbl_business_staff'] = $this->Tbl_business_staff_model->get_all_tbl_business_staff();
        
        $data['_view'] = 'tbl_business_staff/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_business_staff
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'staff_password' => $this->input->post('staff_password'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'staff_profile_img' => $this->input->post('staff_profile_img'),
				'staff_name' => $this->input->post('staff_name'),
				'staff_lname' => $this->input->post('staff_lname'),
				'staff_title' => $this->input->post('staff_title'),
				'staff_email' => $this->input->post('staff_email'),
				'available_days' => $this->input->post('available_days'),
				'staff_role' => $this->input->post('staff_role'),
				'staff_status' => $this->input->post('staff_status'),
				'track_compensation' => $this->input->post('track_compensation'),
				'regular_pay_per_hour_amt' => $this->input->post('regular_pay_per_hour_amt'),
				'regular_percent_revenue' => $this->input->post('regular_percent_revenue'),
				'overtime_pay_per_hour_amt' => $this->input->post('overtime_pay_per_hour_amt'),
				'overtime_percent_revenue' => $this->input->post('overtime_percent_revenue'),
				'email_me' => $this->input->post('email_me'),
				'call_me' => $this->input->post('call_me'),
				'text_me' => $this->input->post('text_me'),
				'is_delete' => $this->input->post('is_delete'),
				'staff_birthdate' => $this->input->post('staff_birthdate'),
				'staff_contact_number' => $this->input->post('staff_contact_number'),
				'confirm_code' => $this->input->post('confirm_code'),
				'staff_tattoo_img' => $this->input->post('staff_tattoo_img'),
				'managed_location' => $this->input->post('managed_location'),
				'served_locations' => $this->input->post('served_locations'),
				'about_me_point_1' => $this->input->post('about_me_point_1'),
				'about_me_point_2' => $this->input->post('about_me_point_2'),
				'services_served' => $this->input->post('services_served'),
				'events_served' => $this->input->post('events_served'),
            );
            
            $tbl_business_staff_id = $this->Tbl_business_staff_model->add_tbl_business_staff($params);
            redirect('tbl_business_staff/index');
        }
        else
        {            
            $data['_view'] = 'tbl_business_staff/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_business_staff
     */
    function edit($staff_id)
    {   
        // check if the tbl_business_staff exists before trying to edit it
        $data['tbl_business_staff'] = $this->Tbl_business_staff_model->get_tbl_business_staff($staff_id);
        
        if(isset($data['tbl_business_staff']['staff_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'staff_password' => $this->input->post('staff_password'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'staff_profile_img' => $this->input->post('staff_profile_img'),
					'staff_name' => $this->input->post('staff_name'),
					'staff_lname' => $this->input->post('staff_lname'),
					'staff_title' => $this->input->post('staff_title'),
					'staff_email' => $this->input->post('staff_email'),
					'available_days' => $this->input->post('available_days'),
					'staff_role' => $this->input->post('staff_role'),
					'staff_status' => $this->input->post('staff_status'),
					'track_compensation' => $this->input->post('track_compensation'),
					'regular_pay_per_hour_amt' => $this->input->post('regular_pay_per_hour_amt'),
					'regular_percent_revenue' => $this->input->post('regular_percent_revenue'),
					'overtime_pay_per_hour_amt' => $this->input->post('overtime_pay_per_hour_amt'),
					'overtime_percent_revenue' => $this->input->post('overtime_percent_revenue'),
					'email_me' => $this->input->post('email_me'),
					'call_me' => $this->input->post('call_me'),
					'text_me' => $this->input->post('text_me'),
					'is_delete' => $this->input->post('is_delete'),
					'staff_birthdate' => $this->input->post('staff_birthdate'),
					'staff_contact_number' => $this->input->post('staff_contact_number'),
					'confirm_code' => $this->input->post('confirm_code'),
					'staff_tattoo_img' => $this->input->post('staff_tattoo_img'),
					'managed_location' => $this->input->post('managed_location'),
					'served_locations' => $this->input->post('served_locations'),
					'about_me_point_1' => $this->input->post('about_me_point_1'),
					'about_me_point_2' => $this->input->post('about_me_point_2'),
					'services_served' => $this->input->post('services_served'),
					'events_served' => $this->input->post('events_served'),
                );

                $this->Tbl_business_staff_model->update_tbl_business_staff($staff_id,$params);            
                redirect('tbl_business_staff/index');
            }
            else
            {
                $data['_view'] = 'tbl_business_staff/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_business_staff you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_business_staff
     */
    function remove($staff_id)
    {
        $tbl_business_staff = $this->Tbl_business_staff_model->get_tbl_business_staff($staff_id);

        // check if the tbl_business_staff exists before trying to delete it
        if(isset($tbl_business_staff['staff_id']))
        {
            $this->Tbl_business_staff_model->delete_tbl_business_staff($staff_id);
            redirect('tbl_business_staff/index');
        }
        else
            show_error('The tbl_business_staff you are trying to delete does not exist.');
    }
    
}
