<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_view extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_business_view_model');
    } 

    /*
     * Listing of tbl_business_view
     */
    function index()
    {
        $data['tbl_business_view'] = $this->Tbl_business_view_model->get_all_tbl_business_view();
        
        $data['_view'] = 'tbl_business_view/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_business_view
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'view_id' => $this->input->post('view_id'),
				'business_id' => $this->input->post('business_id'),
				'fk_user_id' => $this->input->post('fk_user_id'),
				'ip_address' => $this->input->post('ip_address'),
				'view_count' => $this->input->post('view_count'),
				'added_date' => $this->input->post('added_date'),
            );
            
            $tbl_business_view_id = $this->Tbl_business_view_model->add_tbl_business_view($params);
            redirect('tbl_business_view/index');
        }
        else
        {            
            $data['_view'] = 'tbl_business_view/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_business_view
     */
    function edit($)
    {   
        // check if the tbl_business_view exists before trying to edit it
        $data['tbl_business_view'] = $this->Tbl_business_view_model->get_tbl_business_view($);
        
        if(isset($data['tbl_business_view']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'view_id' => $this->input->post('view_id'),
					'business_id' => $this->input->post('business_id'),
					'fk_user_id' => $this->input->post('fk_user_id'),
					'ip_address' => $this->input->post('ip_address'),
					'view_count' => $this->input->post('view_count'),
					'added_date' => $this->input->post('added_date'),
                );

                $this->Tbl_business_view_model->update_tbl_business_view($,$params);            
                redirect('tbl_business_view/index');
            }
            else
            {
                $data['_view'] = 'tbl_business_view/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_business_view you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_business_view
     */
    function remove($)
    {
        $tbl_business_view = $this->Tbl_business_view_model->get_tbl_business_view($);

        // check if the tbl_business_view exists before trying to delete it
        if(isset($tbl_business_view['']))
        {
            $this->Tbl_business_view_model->delete_tbl_business_view($);
            redirect('tbl_business_view/index');
        }
        else
            show_error('The tbl_business_view you are trying to delete does not exist.');
    }
    
}
