<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_add_availibility extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_add_availibility_model');
    } 

    /*
     * Listing of tbl_add_availibility
     */
    function index()
    {
        $data['tbl_add_availibility'] = $this->Tbl_add_availibility_model->get_all_tbl_add_availibility();
        
        $data['_view'] = 'tbl_add_availibility/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_add_availibility
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_business_id' => $this->input->post('fk_business_id'),
				'staff_id' => $this->input->post('staff_id'),
				'day_of_week' => $this->input->post('day_of_week'),
				'date' => $this->input->post('date'),
				'start_time' => $this->input->post('start_time'),
				'end_time' => $this->input->post('end_time'),
				'date_time' => $this->input->post('date_time'),
				'status' => $this->input->post('status'),
            );
            
            $tbl_add_availibility_id = $this->Tbl_add_availibility_model->add_tbl_add_availibility($params);
            redirect('tbl_add_availibility/index');
        }
        else
        {            
            $data['_view'] = 'tbl_add_availibility/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_add_availibility
     */
    function edit($availibility_id)
    {   
        // check if the tbl_add_availibility exists before trying to edit it
        $data['tbl_add_availibility'] = $this->Tbl_add_availibility_model->get_tbl_add_availibility($availibility_id);
        
        if(isset($data['tbl_add_availibility']['availibility_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_business_id' => $this->input->post('fk_business_id'),
					'staff_id' => $this->input->post('staff_id'),
					'day_of_week' => $this->input->post('day_of_week'),
					'date' => $this->input->post('date'),
					'start_time' => $this->input->post('start_time'),
					'end_time' => $this->input->post('end_time'),
					'date_time' => $this->input->post('date_time'),
					'status' => $this->input->post('status'),
                );

                $this->Tbl_add_availibility_model->update_tbl_add_availibility($availibility_id,$params);            
                redirect('tbl_add_availibility/index');
            }
            else
            {
                $data['_view'] = 'tbl_add_availibility/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_add_availibility you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_add_availibility
     */
    function remove($availibility_id)
    {
        $tbl_add_availibility = $this->Tbl_add_availibility_model->get_tbl_add_availibility($availibility_id);

        // check if the tbl_add_availibility exists before trying to delete it
        if(isset($tbl_add_availibility['availibility_id']))
        {
            $this->Tbl_add_availibility_model->delete_tbl_add_availibility($availibility_id);
            redirect('tbl_add_availibility/index');
        }
        else
            show_error('The tbl_add_availibility you are trying to delete does not exist.');
    }
    
}
