<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_site_statu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_site_statu_model');
    } 

    /*
     * Listing of tbl_site_status
     */
    function index()
    {
        $data['tbl_site_status'] = $this->Tbl_site_statu_model->get_all_tbl_site_status();
        
        $data['_view'] = 'tbl_site_statu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_site_statu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'site_id' => $this->input->post('site_id'),
				'site_status' => $this->input->post('site_status'),
            );
            
            $tbl_site_statu_id = $this->Tbl_site_statu_model->add_tbl_site_statu($params);
            redirect('tbl_site_statu/index');
        }
        else
        {            
            $data['_view'] = 'tbl_site_statu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_site_statu
     */
    function edit($)
    {   
        // check if the tbl_site_statu exists before trying to edit it
        $data['tbl_site_statu'] = $this->Tbl_site_statu_model->get_tbl_site_statu($);
        
        if(isset($data['tbl_site_statu']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'site_id' => $this->input->post('site_id'),
					'site_status' => $this->input->post('site_status'),
                );

                $this->Tbl_site_statu_model->update_tbl_site_statu($,$params);            
                redirect('tbl_site_statu/index');
            }
            else
            {
                $data['_view'] = 'tbl_site_statu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_site_statu you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_site_statu
     */
    function remove($)
    {
        $tbl_site_statu = $this->Tbl_site_statu_model->get_tbl_site_statu($);

        // check if the tbl_site_statu exists before trying to delete it
        if(isset($tbl_site_statu['']))
        {
            $this->Tbl_site_statu_model->delete_tbl_site_statu($);
            redirect('tbl_site_statu/index');
        }
        else
            show_error('The tbl_site_statu you are trying to delete does not exist.');
    }
    
}
