<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_studio_tattoo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_studio_tattoo_model');
    } 

    /*
     * Listing of tbl_studio_tattoos
     */
    function index()
    {
        $data['tbl_studio_tattoos'] = $this->Tbl_studio_tattoo_model->get_all_tbl_studio_tattoos();
        
        $data['_view'] = 'tbl_studio_tattoo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_studio_tattoo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tattoo_title' => $this->input->post('tattoo_title'),
				'duration' => $this->input->post('duration'),
				'tatto_staff' => $this->input->post('tatto_staff'),
				'tattoo_price' => $this->input->post('tattoo_price'),
				'tattoo_style' => $this->input->post('tattoo_style'),
				'tattoo_image' => $this->input->post('tattoo_image'),
				'category' => $this->input->post('category'),
				'sub_category' => $this->input->post('sub_category'),
				'color' => $this->input->post('color'),
				'size' => $this->input->post('size'),
				'user_id' => $this->input->post('user_id'),
				'is_deleted' => $this->input->post('is_deleted'),
				'tattoo_description' => $this->input->post('tattoo_description'),
            );
            
            $tbl_studio_tattoo_id = $this->Tbl_studio_tattoo_model->add_tbl_studio_tattoo($params);
            redirect('tbl_studio_tattoo/index');
        }
        else
        {            
            $data['_view'] = 'tbl_studio_tattoo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_studio_tattoo
     */
    function edit($id)
    {   
        // check if the tbl_studio_tattoo exists before trying to edit it
        $data['tbl_studio_tattoo'] = $this->Tbl_studio_tattoo_model->get_tbl_studio_tattoo($id);
        
        if(isset($data['tbl_studio_tattoo']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tattoo_title' => $this->input->post('tattoo_title'),
					'duration' => $this->input->post('duration'),
					'tatto_staff' => $this->input->post('tatto_staff'),
					'tattoo_price' => $this->input->post('tattoo_price'),
					'tattoo_style' => $this->input->post('tattoo_style'),
					'tattoo_image' => $this->input->post('tattoo_image'),
					'category' => $this->input->post('category'),
					'sub_category' => $this->input->post('sub_category'),
					'color' => $this->input->post('color'),
					'size' => $this->input->post('size'),
					'user_id' => $this->input->post('user_id'),
					'is_deleted' => $this->input->post('is_deleted'),
					'tattoo_description' => $this->input->post('tattoo_description'),
                );

                $this->Tbl_studio_tattoo_model->update_tbl_studio_tattoo($id,$params);            
                redirect('tbl_studio_tattoo/index');
            }
            else
            {
                $data['_view'] = 'tbl_studio_tattoo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_studio_tattoo you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_studio_tattoo
     */
    function remove($id)
    {
        $tbl_studio_tattoo = $this->Tbl_studio_tattoo_model->get_tbl_studio_tattoo($id);

        // check if the tbl_studio_tattoo exists before trying to delete it
        if(isset($tbl_studio_tattoo['id']))
        {
            $this->Tbl_studio_tattoo_model->delete_tbl_studio_tattoo($id);
            redirect('tbl_studio_tattoo/index');
        }
        else
            show_error('The tbl_studio_tattoo you are trying to delete does not exist.');
    }
    
}
