<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_user_master extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_user_master_model');
    } 

    /*
     * Listing of tbl_user_master
     */
    function index()
    {
        $data['tbl_user_master'] = $this->Tbl_user_master_model->get_all_tbl_user_master();
        
        $data['_view'] = 'tbl_user_master/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_user_master
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'fname' => $this->input->post('fname'),
				'lname' => $this->input->post('lname'),
				'email_id' => $this->input->post('email_id'),
				'giftcard_remaining_amount' => $this->input->post('giftcard_remaining_amount'),
				'zipcode' => $this->input->post('zipcode'),
				'phone' => $this->input->post('phone'),
				'terms_check' => $this->input->post('terms_check'),
				'user_type' => $this->input->post('user_type'),
				'confirm_code' => $this->input->post('confirm_code'),
				'is_verified' => $this->input->post('is_verified'),
				'is_special' => $this->input->post('is_special'),
				'is_assured' => $this->input->post('is_assured'),
				'is_featured' => $this->input->post('is_featured'),
				'user_status' => $this->input->post('user_status'),
				'user_city' => $this->input->post('user_city'),
				'user_state' => $this->input->post('user_state'),
				'user_country' => $this->input->post('user_country'),
				'cdate' => $this->input->post('cdate'),
				'setup_status' => $this->input->post('setup_status'),
				'gender' => $this->input->post('gender'),
				'birthdate' => $this->input->post('birthdate'),
				'profile_image' => $this->input->post('profile_image'),
				'accredited_batch_request' => $this->input->post('accredited_batch_request'),
				'accredited_batch_info' => $this->input->post('accredited_batch_info'),
				'is_first_time' => $this->input->post('is_first_time'),
				'address1' => $this->input->post('address1'),
				'address2' => $this->input->post('address2'),
				'register_type' => $this->input->post('register_type'),
				'city_id' => $this->input->post('city_id'),
				'country_id' => $this->input->post('country_id'),
				'state_id' => $this->input->post('state_id'),
				'cover_img' => $this->input->post('cover_img'),
            );
            
            $tbl_user_master_id = $this->Tbl_user_master_model->add_tbl_user_master($params);
            redirect('tbl_user_master/index');
        }
        else
        {            
            $data['_view'] = 'tbl_user_master/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_user_master
     */
    function edit($user_id)
    {   
        // check if the tbl_user_master exists before trying to edit it
        $data['tbl_user_master'] = $this->Tbl_user_master_model->get_tbl_user_master($user_id);
        
        if(isset($data['tbl_user_master']['user_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'fname' => $this->input->post('fname'),
					'lname' => $this->input->post('lname'),
					'email_id' => $this->input->post('email_id'),
					'giftcard_remaining_amount' => $this->input->post('giftcard_remaining_amount'),
					'zipcode' => $this->input->post('zipcode'),
					'phone' => $this->input->post('phone'),
					'terms_check' => $this->input->post('terms_check'),
					'user_type' => $this->input->post('user_type'),
					'confirm_code' => $this->input->post('confirm_code'),
					'is_verified' => $this->input->post('is_verified'),
					'is_special' => $this->input->post('is_special'),
					'is_assured' => $this->input->post('is_assured'),
					'is_featured' => $this->input->post('is_featured'),
					'user_status' => $this->input->post('user_status'),
					'user_city' => $this->input->post('user_city'),
					'user_state' => $this->input->post('user_state'),
					'user_country' => $this->input->post('user_country'),
					'cdate' => $this->input->post('cdate'),
					'setup_status' => $this->input->post('setup_status'),
					'gender' => $this->input->post('gender'),
					'birthdate' => $this->input->post('birthdate'),
					'profile_image' => $this->input->post('profile_image'),
					'accredited_batch_request' => $this->input->post('accredited_batch_request'),
					'accredited_batch_info' => $this->input->post('accredited_batch_info'),
					'is_first_time' => $this->input->post('is_first_time'),
					'address1' => $this->input->post('address1'),
					'address2' => $this->input->post('address2'),
					'register_type' => $this->input->post('register_type'),
					'city_id' => $this->input->post('city_id'),
					'country_id' => $this->input->post('country_id'),
					'state_id' => $this->input->post('state_id'),
					'cover_img' => $this->input->post('cover_img'),
                );

                $this->Tbl_user_master_model->update_tbl_user_master($user_id,$params);            
                redirect('tbl_user_master/index');
            }
            else
            {
                $data['_view'] = 'tbl_user_master/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_user_master you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_user_master
     */
    function remove($user_id)
    {
        $tbl_user_master = $this->Tbl_user_master_model->get_tbl_user_master($user_id);

        // check if the tbl_user_master exists before trying to delete it
        if(isset($tbl_user_master['user_id']))
        {
            $this->Tbl_user_master_model->delete_tbl_user_master($user_id);
            redirect('tbl_user_master/index');
        }
        else
            show_error('The tbl_user_master you are trying to delete does not exist.');
    }
    
}
