<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_walkin_user extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_walkin_user_model');
    } 

    /*
     * Listing of tbl_walkin_users
     */
    function index()
    {
        $data['tbl_walkin_users'] = $this->Tbl_walkin_user_model->get_all_tbl_walkin_users();
        
        $data['_view'] = 'tbl_walkin_user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_walkin_user
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'business_id' => $this->input->post('business_id'),
				'first_name' => $this->input->post('first_name'),
				'last_name' => $this->input->post('last_name'),
				'email_id' => $this->input->post('email_id'),
				'mobile_no' => $this->input->post('mobile_no'),
				'address' => $this->input->post('address'),
				'reg_date' => $this->input->post('reg_date'),
            );
            
            $tbl_walkin_user_id = $this->Tbl_walkin_user_model->add_tbl_walkin_user($params);
            redirect('tbl_walkin_user/index');
        }
        else
        {            
            $data['_view'] = 'tbl_walkin_user/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_walkin_user
     */
    function edit($id)
    {   
        // check if the tbl_walkin_user exists before trying to edit it
        $data['tbl_walkin_user'] = $this->Tbl_walkin_user_model->get_tbl_walkin_user($id);
        
        if(isset($data['tbl_walkin_user']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'business_id' => $this->input->post('business_id'),
					'first_name' => $this->input->post('first_name'),
					'last_name' => $this->input->post('last_name'),
					'email_id' => $this->input->post('email_id'),
					'mobile_no' => $this->input->post('mobile_no'),
					'address' => $this->input->post('address'),
					'reg_date' => $this->input->post('reg_date'),
                );

                $this->Tbl_walkin_user_model->update_tbl_walkin_user($id,$params);            
                redirect('tbl_walkin_user/index');
            }
            else
            {
                $data['_view'] = 'tbl_walkin_user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_walkin_user you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_walkin_user
     */
    function remove($id)
    {
        $tbl_walkin_user = $this->Tbl_walkin_user_model->get_tbl_walkin_user($id);

        // check if the tbl_walkin_user exists before trying to delete it
        if(isset($tbl_walkin_user['id']))
        {
            $this->Tbl_walkin_user_model->delete_tbl_walkin_user($id);
            redirect('tbl_walkin_user/index');
        }
        else
            show_error('The tbl_walkin_user you are trying to delete does not exist.');
    }
    
}
