<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_cancel_and_refund extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_cancel_and_refund_model');
    } 

    /*
     * Listing of tbl_cancel_and_refund
     */
    function index()
    {
        $data['tbl_cancel_and_refund'] = $this->Tbl_cancel_and_refund_model->get_all_tbl_cancel_and_refund();
        
        $data['_view'] = 'tbl_cancel_and_refund/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_cancel_and_refund
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_business_id' => $this->input->post('fk_business_id'),
				'fk_business_user_id' => $this->input->post('fk_business_user_id'),
				'fk_user_id' => $this->input->post('fk_user_id'),
				'fk_cancel_appointment_id' => $this->input->post('fk_cancel_appointment_id'),
				'refund_amount' => $this->input->post('refund_amount'),
				'is_refund' => $this->input->post('is_refund'),
				'cancel_date' => $this->input->post('cancel_date'),
				'refund_done_date' => $this->input->post('refund_done_date'),
            );
            
            $tbl_cancel_and_refund_id = $this->Tbl_cancel_and_refund_model->add_tbl_cancel_and_refund($params);
            redirect('tbl_cancel_and_refund/index');
        }
        else
        {            
            $data['_view'] = 'tbl_cancel_and_refund/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_cancel_and_refund
     */
    function edit($refund_id)
    {   
        // check if the tbl_cancel_and_refund exists before trying to edit it
        $data['tbl_cancel_and_refund'] = $this->Tbl_cancel_and_refund_model->get_tbl_cancel_and_refund($refund_id);
        
        if(isset($data['tbl_cancel_and_refund']['refund_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_business_id' => $this->input->post('fk_business_id'),
					'fk_business_user_id' => $this->input->post('fk_business_user_id'),
					'fk_user_id' => $this->input->post('fk_user_id'),
					'fk_cancel_appointment_id' => $this->input->post('fk_cancel_appointment_id'),
					'refund_amount' => $this->input->post('refund_amount'),
					'is_refund' => $this->input->post('is_refund'),
					'cancel_date' => $this->input->post('cancel_date'),
					'refund_done_date' => $this->input->post('refund_done_date'),
                );

                $this->Tbl_cancel_and_refund_model->update_tbl_cancel_and_refund($refund_id,$params);            
                redirect('tbl_cancel_and_refund/index');
            }
            else
            {
                $data['_view'] = 'tbl_cancel_and_refund/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_cancel_and_refund you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_cancel_and_refund
     */
    function remove($refund_id)
    {
        $tbl_cancel_and_refund = $this->Tbl_cancel_and_refund_model->get_tbl_cancel_and_refund($refund_id);

        // check if the tbl_cancel_and_refund exists before trying to delete it
        if(isset($tbl_cancel_and_refund['refund_id']))
        {
            $this->Tbl_cancel_and_refund_model->delete_tbl_cancel_and_refund($refund_id);
            redirect('tbl_cancel_and_refund/index');
        }
        else
            show_error('The tbl_cancel_and_refund you are trying to delete does not exist.');
    }
    
}
