<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_sub_category_tag extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_sub_category_tag_model');
    } 

    /*
     * Listing of tbl_sub_category_tag
     */
    function index()
    {
        $data['tbl_sub_category_tag'] = $this->Tbl_sub_category_tag_model->get_all_tbl_sub_category_tag();
        
        $data['_view'] = 'tbl_sub_category_tag/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_sub_category_tag
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'sub_category_tag_name' => $this->input->post('sub_category_tag_name'),
				'sub_category_tag_status' => $this->input->post('sub_category_tag_status'),
				'is_delete' => $this->input->post('is_delete'),
            );
            
            $tbl_sub_category_tag_id = $this->Tbl_sub_category_tag_model->add_tbl_sub_category_tag($params);
            redirect('tbl_sub_category_tag/index');
        }
        else
        {            
            $data['_view'] = 'tbl_sub_category_tag/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_sub_category_tag
     */
    function edit($sub_category_tag_id)
    {   
        // check if the tbl_sub_category_tag exists before trying to edit it
        $data['tbl_sub_category_tag'] = $this->Tbl_sub_category_tag_model->get_tbl_sub_category_tag($sub_category_tag_id);
        
        if(isset($data['tbl_sub_category_tag']['sub_category_tag_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'sub_category_tag_name' => $this->input->post('sub_category_tag_name'),
					'sub_category_tag_status' => $this->input->post('sub_category_tag_status'),
					'is_delete' => $this->input->post('is_delete'),
                );

                $this->Tbl_sub_category_tag_model->update_tbl_sub_category_tag($sub_category_tag_id,$params);            
                redirect('tbl_sub_category_tag/index');
            }
            else
            {
                $data['_view'] = 'tbl_sub_category_tag/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_sub_category_tag you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_sub_category_tag
     */
    function remove($sub_category_tag_id)
    {
        $tbl_sub_category_tag = $this->Tbl_sub_category_tag_model->get_tbl_sub_category_tag($sub_category_tag_id);

        // check if the tbl_sub_category_tag exists before trying to delete it
        if(isset($tbl_sub_category_tag['sub_category_tag_id']))
        {
            $this->Tbl_sub_category_tag_model->delete_tbl_sub_category_tag($sub_category_tag_id);
            redirect('tbl_sub_category_tag/index');
        }
        else
            show_error('The tbl_sub_category_tag you are trying to delete does not exist.');
    }
    
}
