<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_appoinment extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_appoinment_model');
    } 

    /*
     * Listing of tbl_appoinment
     */
    function index()
    {
        $data['tbl_appoinment'] = $this->Tbl_appoinment_model->get_all_tbl_appoinment();
        
        $data['_view'] = 'tbl_appoinment/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_appoinment
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'deal_id' => $this->input->post('deal_id'),
				'fk_user_id' => $this->input->post('fk_user_id'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'fk_business_service_id' => $this->input->post('fk_business_service_id'),
				'fk_client_id' => $this->input->post('fk_client_id'),
				'fk_location_id' => $this->input->post('fk_location_id'),
				'fk_package_id' => $this->input->post('fk_package_id'),
				'service_cost' => $this->input->post('service_cost'),
				'total_cost' => $this->input->post('total_cost'),
				'apt_date' => $this->input->post('apt_date'),
				'apt_time' => $this->input->post('apt_time'),
				'end_apt_time' => $this->input->post('end_apt_time'),
				'cancel_time' => $this->input->post('cancel_time'),
				'medical_condition' => $this->input->post('medical_condition'),
				'card_token' => $this->input->post('card_token'),
				'transaction_ref_token' => $this->input->post('transaction_ref_token'),
				'transaction_date_time' => $this->input->post('transaction_date_time'),
				'transaction_correlation_id' => $this->input->post('transaction_correlation_id'),
				'apt_repeat_status' => $this->input->post('apt_repeat_status'),
				'apt_repeat_more_count' => $this->input->post('apt_repeat_more_count'),
				'apt_repeat_more_type' => $this->input->post('apt_repeat_more_type'),
				'apt_repeat_end' => $this->input->post('apt_repeat_end'),
				'apt_repeat_end_date' => $this->input->post('apt_repeat_end_date'),
				'apt_status' => $this->input->post('apt_status'),
				'payment_status' => $this->input->post('payment_status'),
				'confirmed_status' => $this->input->post('confirmed_status'),
				'refTransactionId' => $this->input->post('refTransactionId'),
				'refTransactionDate' => $this->input->post('refTransactionDate'),
				'refAmount' => $this->input->post('refAmount'),
				'is_recurring' => $this->input->post('is_recurring'),
				'recurring_parent' => $this->input->post('recurring_parent'),
				'fk_location_hours_id' => $this->input->post('fk_location_hours_id'),
				'is_present' => $this->input->post('is_present'),
				'fk_staff_id' => $this->input->post('fk_staff_id'),
				'apt_note' => $this->input->post('apt_note'),
				'medical_description' => $this->input->post('medical_description'),
				'recurring_data' => $this->input->post('recurring_data'),
            );
            
            $tbl_appoinment_id = $this->Tbl_appoinment_model->add_tbl_appoinment($params);
            redirect('tbl_appoinment/index');
        }
        else
        {            
            $data['_view'] = 'tbl_appoinment/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_appoinment
     */
    function edit($appoinment_id)
    {   
        // check if the tbl_appoinment exists before trying to edit it
        $data['tbl_appoinment'] = $this->Tbl_appoinment_model->get_tbl_appoinment($appoinment_id);
        
        if(isset($data['tbl_appoinment']['appoinment_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'deal_id' => $this->input->post('deal_id'),
					'fk_user_id' => $this->input->post('fk_user_id'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'fk_business_service_id' => $this->input->post('fk_business_service_id'),
					'fk_client_id' => $this->input->post('fk_client_id'),
					'fk_location_id' => $this->input->post('fk_location_id'),
					'fk_package_id' => $this->input->post('fk_package_id'),
					'service_cost' => $this->input->post('service_cost'),
					'total_cost' => $this->input->post('total_cost'),
					'apt_date' => $this->input->post('apt_date'),
					'apt_time' => $this->input->post('apt_time'),
					'end_apt_time' => $this->input->post('end_apt_time'),
					'cancel_time' => $this->input->post('cancel_time'),
					'medical_condition' => $this->input->post('medical_condition'),
					'card_token' => $this->input->post('card_token'),
					'transaction_ref_token' => $this->input->post('transaction_ref_token'),
					'transaction_date_time' => $this->input->post('transaction_date_time'),
					'transaction_correlation_id' => $this->input->post('transaction_correlation_id'),
					'apt_repeat_status' => $this->input->post('apt_repeat_status'),
					'apt_repeat_more_count' => $this->input->post('apt_repeat_more_count'),
					'apt_repeat_more_type' => $this->input->post('apt_repeat_more_type'),
					'apt_repeat_end' => $this->input->post('apt_repeat_end'),
					'apt_repeat_end_date' => $this->input->post('apt_repeat_end_date'),
					'apt_status' => $this->input->post('apt_status'),
					'payment_status' => $this->input->post('payment_status'),
					'confirmed_status' => $this->input->post('confirmed_status'),
					'refTransactionId' => $this->input->post('refTransactionId'),
					'refTransactionDate' => $this->input->post('refTransactionDate'),
					'refAmount' => $this->input->post('refAmount'),
					'is_recurring' => $this->input->post('is_recurring'),
					'recurring_parent' => $this->input->post('recurring_parent'),
					'fk_location_hours_id' => $this->input->post('fk_location_hours_id'),
					'is_present' => $this->input->post('is_present'),
					'fk_staff_id' => $this->input->post('fk_staff_id'),
					'apt_note' => $this->input->post('apt_note'),
					'medical_description' => $this->input->post('medical_description'),
					'recurring_data' => $this->input->post('recurring_data'),
                );

                $this->Tbl_appoinment_model->update_tbl_appoinment($appoinment_id,$params);            
                redirect('tbl_appoinment/index');
            }
            else
            {
                $data['_view'] = 'tbl_appoinment/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_appoinment you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_appoinment
     */
    function remove($appoinment_id)
    {
        $tbl_appoinment = $this->Tbl_appoinment_model->get_tbl_appoinment($appoinment_id);

        // check if the tbl_appoinment exists before trying to delete it
        if(isset($tbl_appoinment['appoinment_id']))
        {
            $this->Tbl_appoinment_model->delete_tbl_appoinment($appoinment_id);
            redirect('tbl_appoinment/index');
        }
        else
            show_error('The tbl_appoinment you are trying to delete does not exist.');
    }
    
}
