<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_user_package extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_user_package_model');
    } 

    /*
     * Listing of tbl_user_package
     */
    function index()
    {
        $data['tbl_user_package'] = $this->Tbl_user_package_model->get_all_tbl_user_package();
        
        $data['_view'] = 'tbl_user_package/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_user_package
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'pakage_name' => $this->input->post('pakage_name'),
				'fk_user_id' => $this->input->post('fk_user_id'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'packge_qty' => $this->input->post('packge_qty'),
				'fk_pakage_id' => $this->input->post('fk_pakage_id'),
				'pakage_remaining_qty' => $this->input->post('pakage_remaining_qty'),
				'purchase_date' => $this->input->post('purchase_date'),
				'expiry_date' => $this->input->post('expiry_date'),
				'status' => $this->input->post('status'),
				'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
            );
            
            $tbl_user_package_id = $this->Tbl_user_package_model->add_tbl_user_package($params);
            redirect('tbl_user_package/index');
        }
        else
        {            
            $data['_view'] = 'tbl_user_package/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_user_package
     */
    function edit($user_pakage_id)
    {   
        // check if the tbl_user_package exists before trying to edit it
        $data['tbl_user_package'] = $this->Tbl_user_package_model->get_tbl_user_package($user_pakage_id);
        
        if(isset($data['tbl_user_package']['user_pakage_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'pakage_name' => $this->input->post('pakage_name'),
					'fk_user_id' => $this->input->post('fk_user_id'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'packge_qty' => $this->input->post('packge_qty'),
					'fk_pakage_id' => $this->input->post('fk_pakage_id'),
					'pakage_remaining_qty' => $this->input->post('pakage_remaining_qty'),
					'purchase_date' => $this->input->post('purchase_date'),
					'expiry_date' => $this->input->post('expiry_date'),
					'status' => $this->input->post('status'),
					'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
                );

                $this->Tbl_user_package_model->update_tbl_user_package($user_pakage_id,$params);            
                redirect('tbl_user_package/index');
            }
            else
            {
                $data['_view'] = 'tbl_user_package/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_user_package you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_user_package
     */
    function remove($user_pakage_id)
    {
        $tbl_user_package = $this->Tbl_user_package_model->get_tbl_user_package($user_pakage_id);

        // check if the tbl_user_package exists before trying to delete it
        if(isset($tbl_user_package['user_pakage_id']))
        {
            $this->Tbl_user_package_model->delete_tbl_user_package($user_pakage_id);
            redirect('tbl_user_package/index');
        }
        else
            show_error('The tbl_user_package you are trying to delete does not exist.');
    }
    
}
