<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_services_menu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_services_menu_model');
    } 

    /*
     * Listing of tbl_services_menu
     */
    function index()
    {
        $data['tbl_services_menu'] = $this->Tbl_services_menu_model->get_all_tbl_services_menu();
        
        $data['_view'] = 'tbl_services_menu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_services_menu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'regular_price_exisiting' => $this->input->post('regular_price_exisiting'),
				'is_offpeak_time' => $this->input->post('is_offpeak_time'),
				'offpeak_type' => $this->input->post('offpeak_type'),
				'offpeak_price_new' => $this->input->post('offpeak_price_new'),
				'offpeak_price_exisiting' => $this->input->post('offpeak_price_exisiting'),
				'offpeak_times' => $this->input->post('offpeak_times'),
				'pause_status' => $this->input->post('pause_status'),
				'is_setup' => $this->input->post('is_setup'),
				'time_slot_type' => $this->input->post('time_slot_type'),
				'is_delete' => $this->input->post('is_delete'),
				'service_type' => $this->input->post('service_type'),
				'service_start_date' => $this->input->post('service_start_date'),
				'service_end_date' => $this->input->post('service_end_date'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'fk_category_id' => $this->input->post('fk_category_id'),
				'fk_subcat_id' => $this->input->post('fk_subcat_id'),
				'service_index' => $this->input->post('service_index'),
				'service_name' => $this->input->post('service_name'),
				'service_cat_name' => $this->input->post('service_cat_name'),
				'service_duration' => $this->input->post('service_duration'),
				'service_capacity' => $this->input->post('service_capacity'),
				'regular_price_new' => $this->input->post('regular_price_new'),
				'service_style' => $this->input->post('service_style'),
				'service_color' => $this->input->post('service_color'),
				'service_size' => $this->input->post('service_size'),
				'service_status' => $this->input->post('service_status'),
				'service_description' => $this->input->post('service_description'),
				'questions_answers' => $this->input->post('questions_answers'),
				'offered_by' => $this->input->post('offered_by'),
            );
            
            $tbl_services_menu_id = $this->Tbl_services_menu_model->add_tbl_services_menu($params);
            redirect('tbl_services_menu/index');
        }
        else
        {            
            $data['_view'] = 'tbl_services_menu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_services_menu
     */
    function edit($service_menu_id)
    {   
        // check if the tbl_services_menu exists before trying to edit it
        $data['tbl_services_menu'] = $this->Tbl_services_menu_model->get_tbl_services_menu($service_menu_id);
        
        if(isset($data['tbl_services_menu']['service_menu_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'regular_price_exisiting' => $this->input->post('regular_price_exisiting'),
					'is_offpeak_time' => $this->input->post('is_offpeak_time'),
					'offpeak_type' => $this->input->post('offpeak_type'),
					'offpeak_price_new' => $this->input->post('offpeak_price_new'),
					'offpeak_price_exisiting' => $this->input->post('offpeak_price_exisiting'),
					'offpeak_times' => $this->input->post('offpeak_times'),
					'pause_status' => $this->input->post('pause_status'),
					'is_setup' => $this->input->post('is_setup'),
					'time_slot_type' => $this->input->post('time_slot_type'),
					'is_delete' => $this->input->post('is_delete'),
					'service_type' => $this->input->post('service_type'),
					'service_start_date' => $this->input->post('service_start_date'),
					'service_end_date' => $this->input->post('service_end_date'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'fk_category_id' => $this->input->post('fk_category_id'),
					'fk_subcat_id' => $this->input->post('fk_subcat_id'),
					'service_index' => $this->input->post('service_index'),
					'service_name' => $this->input->post('service_name'),
					'service_cat_name' => $this->input->post('service_cat_name'),
					'service_duration' => $this->input->post('service_duration'),
					'service_capacity' => $this->input->post('service_capacity'),
					'regular_price_new' => $this->input->post('regular_price_new'),
					'service_style' => $this->input->post('service_style'),
					'service_color' => $this->input->post('service_color'),
					'service_size' => $this->input->post('service_size'),
					'service_status' => $this->input->post('service_status'),
					'service_description' => $this->input->post('service_description'),
					'questions_answers' => $this->input->post('questions_answers'),
					'offered_by' => $this->input->post('offered_by'),
                );

                $this->Tbl_services_menu_model->update_tbl_services_menu($service_menu_id,$params);            
                redirect('tbl_services_menu/index');
            }
            else
            {
                $data['_view'] = 'tbl_services_menu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_services_menu you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_services_menu
     */
    function remove($service_menu_id)
    {
        $tbl_services_menu = $this->Tbl_services_menu_model->get_tbl_services_menu($service_menu_id);

        // check if the tbl_services_menu exists before trying to delete it
        if(isset($tbl_services_menu['service_menu_id']))
        {
            $this->Tbl_services_menu_model->delete_tbl_services_menu($service_menu_id);
            redirect('tbl_services_menu/index');
        }
        else
            show_error('The tbl_services_menu you are trying to delete does not exist.');
    }
    
}
