<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_campaign_scheduler extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_campaign_scheduler_model');
    } 

    /*
     * Listing of tbl_campaign_scheduler
     */
    function index()
    {
        $data['tbl_campaign_scheduler'] = $this->Tbl_campaign_scheduler_model->get_all_tbl_campaign_scheduler();
        
        $data['_view'] = 'tbl_campaign_scheduler/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_campaign_scheduler
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'uniq_tracker_id' => $this->input->post('uniq_tracker_id'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'type' => $this->input->post('type'),
				'template_id' => $this->input->post('template_id'),
				'template_name' => $this->input->post('template_name'),
				'schedule_date' => $this->input->post('schedule_date'),
				'schedule_time' => $this->input->post('schedule_time'),
				'sent_time' => $this->input->post('sent_time'),
				'reply_to_name' => $this->input->post('reply_to_name'),
				'reply_to_email' => $this->input->post('reply_to_email'),
				'client_id' => $this->input->post('client_id'),
				'subject' => $this->input->post('subject'),
				'message_body' => $this->input->post('message_body'),
				'opened' => $this->input->post('opened'),
				'booked' => $this->input->post('booked'),
				'bounced' => $this->input->post('bounced'),
            );
            
            $tbl_campaign_scheduler_id = $this->Tbl_campaign_scheduler_model->add_tbl_campaign_scheduler($params);
            redirect('tbl_campaign_scheduler/index');
        }
        else
        {            
            $data['_view'] = 'tbl_campaign_scheduler/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_campaign_scheduler
     */
    function edit($scheduler_id)
    {   
        // check if the tbl_campaign_scheduler exists before trying to edit it
        $data['tbl_campaign_scheduler'] = $this->Tbl_campaign_scheduler_model->get_tbl_campaign_scheduler($scheduler_id);
        
        if(isset($data['tbl_campaign_scheduler']['scheduler_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'uniq_tracker_id' => $this->input->post('uniq_tracker_id'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'type' => $this->input->post('type'),
					'template_id' => $this->input->post('template_id'),
					'template_name' => $this->input->post('template_name'),
					'schedule_date' => $this->input->post('schedule_date'),
					'schedule_time' => $this->input->post('schedule_time'),
					'sent_time' => $this->input->post('sent_time'),
					'reply_to_name' => $this->input->post('reply_to_name'),
					'reply_to_email' => $this->input->post('reply_to_email'),
					'client_id' => $this->input->post('client_id'),
					'subject' => $this->input->post('subject'),
					'message_body' => $this->input->post('message_body'),
					'opened' => $this->input->post('opened'),
					'booked' => $this->input->post('booked'),
					'bounced' => $this->input->post('bounced'),
                );

                $this->Tbl_campaign_scheduler_model->update_tbl_campaign_scheduler($scheduler_id,$params);            
                redirect('tbl_campaign_scheduler/index');
            }
            else
            {
                $data['_view'] = 'tbl_campaign_scheduler/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_campaign_scheduler you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_campaign_scheduler
     */
    function remove($scheduler_id)
    {
        $tbl_campaign_scheduler = $this->Tbl_campaign_scheduler_model->get_tbl_campaign_scheduler($scheduler_id);

        // check if the tbl_campaign_scheduler exists before trying to delete it
        if(isset($tbl_campaign_scheduler['scheduler_id']))
        {
            $this->Tbl_campaign_scheduler_model->delete_tbl_campaign_scheduler($scheduler_id);
            redirect('tbl_campaign_scheduler/index');
        }
        else
            show_error('The tbl_campaign_scheduler you are trying to delete does not exist.');
    }
    
}
