<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_service_offpeak_time extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_service_offpeak_time_model');
    } 

    /*
     * Listing of tbl_service_offpeak_times
     */
    function index()
    {
        $data['tbl_service_offpeak_times'] = $this->Tbl_service_offpeak_time_model->get_all_tbl_service_offpeak_times();
        
        $data['_view'] = 'tbl_service_offpeak_time/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_service_offpeak_time
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
				'day' => $this->input->post('day'),
				'start_time' => $this->input->post('start_time'),
				'end_time' => $this->input->post('end_time'),
            );
            
            $tbl_service_offpeak_time_id = $this->Tbl_service_offpeak_time_model->add_tbl_service_offpeak_time($params);
            redirect('tbl_service_offpeak_time/index');
        }
        else
        {            
            $data['_view'] = 'tbl_service_offpeak_time/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_service_offpeak_time
     */
    function edit($offpeak_time_id)
    {   
        // check if the tbl_service_offpeak_time exists before trying to edit it
        $data['tbl_service_offpeak_time'] = $this->Tbl_service_offpeak_time_model->get_tbl_service_offpeak_time($offpeak_time_id);
        
        if(isset($data['tbl_service_offpeak_time']['offpeak_time_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
					'day' => $this->input->post('day'),
					'start_time' => $this->input->post('start_time'),
					'end_time' => $this->input->post('end_time'),
                );

                $this->Tbl_service_offpeak_time_model->update_tbl_service_offpeak_time($offpeak_time_id,$params);            
                redirect('tbl_service_offpeak_time/index');
            }
            else
            {
                $data['_view'] = 'tbl_service_offpeak_time/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_service_offpeak_time you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_service_offpeak_time
     */
    function remove($offpeak_time_id)
    {
        $tbl_service_offpeak_time = $this->Tbl_service_offpeak_time_model->get_tbl_service_offpeak_time($offpeak_time_id);

        // check if the tbl_service_offpeak_time exists before trying to delete it
        if(isset($tbl_service_offpeak_time['offpeak_time_id']))
        {
            $this->Tbl_service_offpeak_time_model->delete_tbl_service_offpeak_time($offpeak_time_id);
            redirect('tbl_service_offpeak_time/index');
        }
        else
            show_error('The tbl_service_offpeak_time you are trying to delete does not exist.');
    }
    
}
