<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_style extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_style_model');
    } 

    /*
     * Listing of tbl_style
     */
    function index()
    {
        $data['tbl_style'] = $this->Tbl_style_model->get_all_tbl_style();
        
        $data['_view'] = 'tbl_style/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_style
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'style_name' => $this->input->post('style_name'),
				'style_slug' => $this->input->post('style_slug'),
				'style_status' => $this->input->post('style_status'),
				'is_delete' => $this->input->post('is_delete'),
            );
            
            $tbl_style_id = $this->Tbl_style_model->add_tbl_style($params);
            redirect('tbl_style/index');
        }
        else
        {            
            $data['_view'] = 'tbl_style/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_style
     */
    function edit($style_id)
    {   
        // check if the tbl_style exists before trying to edit it
        $data['tbl_style'] = $this->Tbl_style_model->get_tbl_style($style_id);
        
        if(isset($data['tbl_style']['style_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'style_name' => $this->input->post('style_name'),
					'style_slug' => $this->input->post('style_slug'),
					'style_status' => $this->input->post('style_status'),
					'is_delete' => $this->input->post('is_delete'),
                );

                $this->Tbl_style_model->update_tbl_style($style_id,$params);            
                redirect('tbl_style/index');
            }
            else
            {
                $data['_view'] = 'tbl_style/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_style you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_style
     */
    function remove($style_id)
    {
        $tbl_style = $this->Tbl_style_model->get_tbl_style($style_id);

        // check if the tbl_style exists before trying to delete it
        if(isset($tbl_style['style_id']))
        {
            $this->Tbl_style_model->delete_tbl_style($style_id);
            redirect('tbl_style/index');
        }
        else
            show_error('The tbl_style you are trying to delete does not exist.');
    }
    
}
