<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_automated_message extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_automated_message_model');
    } 

    /*
     * Listing of tbl_automated_message
     */
    function index()
    {
        $data['tbl_automated_message'] = $this->Tbl_automated_message_model->get_all_tbl_automated_message();
        
        $data['_view'] = 'tbl_automated_message/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_automated_message
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_event_id' => $this->input->post('fk_event_id'),
				'event_category_name' => $this->input->post('event_category_name'),
				'message_name' => $this->input->post('message_name'),
				'fk_user_id' => $this->input->post('fk_user_id'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'reply_name' => $this->input->post('reply_name'),
				'reply_email' => $this->input->post('reply_email'),
				'message_body_one' => $this->input->post('message_body_one'),
				'message_body_two' => $this->input->post('message_body_two'),
				'text_message' => $this->input->post('text_message'),
				'default_send_type' => $this->input->post('default_send_type'),
				'subject' => $this->input->post('subject'),
				'status' => $this->input->post('status'),
            );
            
            $tbl_automated_message_id = $this->Tbl_automated_message_model->add_tbl_automated_message($params);
            redirect('tbl_automated_message/index');
        }
        else
        {            
            $data['_view'] = 'tbl_automated_message/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_automated_message
     */
    function edit($auto_id)
    {   
        // check if the tbl_automated_message exists before trying to edit it
        $data['tbl_automated_message'] = $this->Tbl_automated_message_model->get_tbl_automated_message($auto_id);
        
        if(isset($data['tbl_automated_message']['auto_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_event_id' => $this->input->post('fk_event_id'),
					'event_category_name' => $this->input->post('event_category_name'),
					'message_name' => $this->input->post('message_name'),
					'fk_user_id' => $this->input->post('fk_user_id'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'reply_name' => $this->input->post('reply_name'),
					'reply_email' => $this->input->post('reply_email'),
					'message_body_one' => $this->input->post('message_body_one'),
					'message_body_two' => $this->input->post('message_body_two'),
					'text_message' => $this->input->post('text_message'),
					'default_send_type' => $this->input->post('default_send_type'),
					'subject' => $this->input->post('subject'),
					'status' => $this->input->post('status'),
                );

                $this->Tbl_automated_message_model->update_tbl_automated_message($auto_id,$params);            
                redirect('tbl_automated_message/index');
            }
            else
            {
                $data['_view'] = 'tbl_automated_message/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_automated_message you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_automated_message
     */
    function remove($auto_id)
    {
        $tbl_automated_message = $this->Tbl_automated_message_model->get_tbl_automated_message($auto_id);

        // check if the tbl_automated_message exists before trying to delete it
        if(isset($tbl_automated_message['auto_id']))
        {
            $this->Tbl_automated_message_model->delete_tbl_automated_message($auto_id);
            redirect('tbl_automated_message/index');
        }
        else
            show_error('The tbl_automated_message you are trying to delete does not exist.');
    }
    
}
