<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_card_type extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_card_type_model');
    } 

    /*
     * Listing of tbl_card_type
     */
    function index()
    {
        $data['tbl_card_type'] = $this->Tbl_card_type_model->get_all_tbl_card_type();
        
        $data['_view'] = 'tbl_card_type/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_card_type
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'card_type' => $this->input->post('card_type'),
				'card_logo' => $this->input->post('card_logo'),
            );
            
            $tbl_card_type_id = $this->Tbl_card_type_model->add_tbl_card_type($params);
            redirect('tbl_card_type/index');
        }
        else
        {            
            $data['_view'] = 'tbl_card_type/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_card_type
     */
    function edit($id)
    {   
        // check if the tbl_card_type exists before trying to edit it
        $data['tbl_card_type'] = $this->Tbl_card_type_model->get_tbl_card_type($id);
        
        if(isset($data['tbl_card_type']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'card_type' => $this->input->post('card_type'),
					'card_logo' => $this->input->post('card_logo'),
                );

                $this->Tbl_card_type_model->update_tbl_card_type($id,$params);            
                redirect('tbl_card_type/index');
            }
            else
            {
                $data['_view'] = 'tbl_card_type/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_card_type you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_card_type
     */
    function remove($id)
    {
        $tbl_card_type = $this->Tbl_card_type_model->get_tbl_card_type($id);

        // check if the tbl_card_type exists before trying to delete it
        if(isset($tbl_card_type['id']))
        {
            $this->Tbl_card_type_model->delete_tbl_card_type($id);
            redirect('tbl_card_type/index');
        }
        else
            show_error('The tbl_card_type you are trying to delete does not exist.');
    }
    
}
