<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_home_page_content extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_home_page_content_model');
    } 

    /*
     * Listing of tbl_home_page_content
     */
    function index()
    {
        $data['tbl_home_page_content'] = $this->Tbl_home_page_content_model->get_all_tbl_home_page_content();
        
        $data['_view'] = 'tbl_home_page_content/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_home_page_content
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'content' => $this->input->post('content'),
            );
            
            $tbl_home_page_content_id = $this->Tbl_home_page_content_model->add_tbl_home_page_content($params);
            redirect('tbl_home_page_content/index');
        }
        else
        {            
            $data['_view'] = 'tbl_home_page_content/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_home_page_content
     */
    function edit($id)
    {   
        // check if the tbl_home_page_content exists before trying to edit it
        $data['tbl_home_page_content'] = $this->Tbl_home_page_content_model->get_tbl_home_page_content($id);
        
        if(isset($data['tbl_home_page_content']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'content' => $this->input->post('content'),
                );

                $this->Tbl_home_page_content_model->update_tbl_home_page_content($id,$params);            
                redirect('tbl_home_page_content/index');
            }
            else
            {
                $data['_view'] = 'tbl_home_page_content/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_home_page_content you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_home_page_content
     */
    function remove($id)
    {
        $tbl_home_page_content = $this->Tbl_home_page_content_model->get_tbl_home_page_content($id);

        // check if the tbl_home_page_content exists before trying to delete it
        if(isset($tbl_home_page_content['id']))
        {
            $this->Tbl_home_page_content_model->delete_tbl_home_page_content($id);
            redirect('tbl_home_page_content/index');
        }
        else
            show_error('The tbl_home_page_content you are trying to delete does not exist.');
    }
    
}
