<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_size extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_size_model');
    } 

    /*
     * Listing of tbl_size
     */
    function index()
    {
        $data['tbl_size'] = $this->Tbl_size_model->get_all_tbl_size();
        
        $data['_view'] = 'tbl_size/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_size
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'size_name' => $this->input->post('size_name'),
				'size_slug' => $this->input->post('size_slug'),
				'is_delete' => $this->input->post('is_delete'),
				'size_status' => $this->input->post('size_status'),
            );
            
            $tbl_size_id = $this->Tbl_size_model->add_tbl_size($params);
            redirect('tbl_size/index');
        }
        else
        {            
            $data['_view'] = 'tbl_size/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_size
     */
    function edit($id)
    {   
        // check if the tbl_size exists before trying to edit it
        $data['tbl_size'] = $this->Tbl_size_model->get_tbl_size($id);
        
        if(isset($data['tbl_size']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'size_name' => $this->input->post('size_name'),
					'size_slug' => $this->input->post('size_slug'),
					'is_delete' => $this->input->post('is_delete'),
					'size_status' => $this->input->post('size_status'),
                );

                $this->Tbl_size_model->update_tbl_size($id,$params);            
                redirect('tbl_size/index');
            }
            else
            {
                $data['_view'] = 'tbl_size/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_size you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_size
     */
    function remove($id)
    {
        $tbl_size = $this->Tbl_size_model->get_tbl_size($id);

        // check if the tbl_size exists before trying to delete it
        if(isset($tbl_size['id']))
        {
            $this->Tbl_size_model->delete_tbl_size($id);
            redirect('tbl_size/index');
        }
        else
            show_error('The tbl_size you are trying to delete does not exist.');
    }
    
}
