<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_admin_stripe_detail extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_admin_stripe_detail_model');
    } 

    /*
     * Listing of tbl_admin_stripe_details
     */
    function index()
    {
        $data['tbl_admin_stripe_details'] = $this->Tbl_admin_stripe_detail_model->get_all_tbl_admin_stripe_details();
        
        $data['_view'] = 'tbl_admin_stripe_detail/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_admin_stripe_detail
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'stripe_live_api_key' => $this->input->post('stripe_live_api_key'),
				'stripe_live_public_api_key' => $this->input->post('stripe_live_public_api_key'),
            );
            
            $tbl_admin_stripe_detail_id = $this->Tbl_admin_stripe_detail_model->add_tbl_admin_stripe_detail($params);
            redirect('tbl_admin_stripe_detail/index');
        }
        else
        {            
            $data['_view'] = 'tbl_admin_stripe_detail/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_admin_stripe_detail
     */
    function edit($stripe_id)
    {   
        // check if the tbl_admin_stripe_detail exists before trying to edit it
        $data['tbl_admin_stripe_detail'] = $this->Tbl_admin_stripe_detail_model->get_tbl_admin_stripe_detail($stripe_id);
        
        if(isset($data['tbl_admin_stripe_detail']['stripe_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'stripe_live_api_key' => $this->input->post('stripe_live_api_key'),
					'stripe_live_public_api_key' => $this->input->post('stripe_live_public_api_key'),
                );

                $this->Tbl_admin_stripe_detail_model->update_tbl_admin_stripe_detail($stripe_id,$params);            
                redirect('tbl_admin_stripe_detail/index');
            }
            else
            {
                $data['_view'] = 'tbl_admin_stripe_detail/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_admin_stripe_detail you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_admin_stripe_detail
     */
    function remove($stripe_id)
    {
        $tbl_admin_stripe_detail = $this->Tbl_admin_stripe_detail_model->get_tbl_admin_stripe_detail($stripe_id);

        // check if the tbl_admin_stripe_detail exists before trying to delete it
        if(isset($tbl_admin_stripe_detail['stripe_id']))
        {
            $this->Tbl_admin_stripe_detail_model->delete_tbl_admin_stripe_detail($stripe_id);
            redirect('tbl_admin_stripe_detail/index');
        }
        else
            show_error('The tbl_admin_stripe_detail you are trying to delete does not exist.');
    }
    
}
