<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_gift_card extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_gift_card_model');
    } 

    /*
     * Listing of tbl_gift_card
     */
    function index()
    {
        $data['tbl_gift_card'] = $this->Tbl_gift_card_model->get_all_tbl_gift_card();
        
        $data['_view'] = 'tbl_gift_card/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_gift_card
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_user_id' => $this->input->post('fk_user_id'),
				'recipient_name' => $this->input->post('recipient_name'),
				'recipient_email' => $this->input->post('recipient_email'),
				'recipient_user_id' => $this->input->post('recipient_user_id'),
				'gift_type' => $this->input->post('gift_type'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
				'total_amount' => $this->input->post('total_amount'),
				'remaining_amount' => $this->input->post('remaining_amount'),
				'gift_card_token' => $this->input->post('gift_card_token'),
				'transaction_ref_token' => $this->input->post('transaction_ref_token'),
				'transaction_date_time' => $this->input->post('transaction_date_time'),
				'transaction_correlation_id' => $this->input->post('transaction_correlation_id'),
            );
            
            $tbl_gift_card_id = $this->Tbl_gift_card_model->add_tbl_gift_card($params);
            redirect('tbl_gift_card/index');
        }
        else
        {            
            $data['_view'] = 'tbl_gift_card/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_gift_card
     */
    function edit($gift_card_id)
    {   
        // check if the tbl_gift_card exists before trying to edit it
        $data['tbl_gift_card'] = $this->Tbl_gift_card_model->get_tbl_gift_card($gift_card_id);
        
        if(isset($data['tbl_gift_card']['gift_card_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_user_id' => $this->input->post('fk_user_id'),
					'recipient_name' => $this->input->post('recipient_name'),
					'recipient_email' => $this->input->post('recipient_email'),
					'recipient_user_id' => $this->input->post('recipient_user_id'),
					'gift_type' => $this->input->post('gift_type'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
					'total_amount' => $this->input->post('total_amount'),
					'remaining_amount' => $this->input->post('remaining_amount'),
					'gift_card_token' => $this->input->post('gift_card_token'),
					'transaction_ref_token' => $this->input->post('transaction_ref_token'),
					'transaction_date_time' => $this->input->post('transaction_date_time'),
					'transaction_correlation_id' => $this->input->post('transaction_correlation_id'),
                );

                $this->Tbl_gift_card_model->update_tbl_gift_card($gift_card_id,$params);            
                redirect('tbl_gift_card/index');
            }
            else
            {
                $data['_view'] = 'tbl_gift_card/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_gift_card you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_gift_card
     */
    function remove($gift_card_id)
    {
        $tbl_gift_card = $this->Tbl_gift_card_model->get_tbl_gift_card($gift_card_id);

        // check if the tbl_gift_card exists before trying to delete it
        if(isset($tbl_gift_card['gift_card_id']))
        {
            $this->Tbl_gift_card_model->delete_tbl_gift_card($gift_card_id);
            redirect('tbl_gift_card/index');
        }
        else
            show_error('The tbl_gift_card you are trying to delete does not exist.');
    }
    
}
