<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_location extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_business_location_model');
    } 

    /*
     * Listing of tbl_business_locations
     */
    function index()
    {
        $data['tbl_business_locations'] = $this->Tbl_business_location_model->get_all_tbl_business_locations();
        
        $data['_view'] = 'tbl_business_location/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_business_location
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_business_id' => $this->input->post('fk_business_id'),
				'travel_to_customer' => $this->input->post('travel_to_customer'),
				'street_address' => $this->input->post('street_address'),
				'street_address2' => $this->input->post('street_address2'),
				'street_address3' => $this->input->post('street_address3'),
				'city' => $this->input->post('city'),
				'district' => $this->input->post('district'),
				'country' => $this->input->post('country'),
				'zip' => $this->input->post('zip'),
				'phone' => $this->input->post('phone'),
				'ada_accessible' => $this->input->post('ada_accessible'),
				'parking' => $this->input->post('parking'),
				'language' => $this->input->post('language'),
				'location_detail' => $this->input->post('location_detail'),
				'latitude' => $this->input->post('latitude'),
				'longitude' => $this->input->post('longitude'),
				'is_active' => $this->input->post('is_active'),
				'giolocation' => $this->input->post('giolocation'),
				'event_conduct' => $this->input->post('event_conduct'),
				'service_conduct' => $this->input->post('service_conduct'),
				'staff_conduct' => $this->input->post('staff_conduct'),
            );
            
            $tbl_business_location_id = $this->Tbl_business_location_model->add_tbl_business_location($params);
            redirect('tbl_business_location/index');
        }
        else
        {            
            $data['_view'] = 'tbl_business_location/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_business_location
     */
    function edit($location_id)
    {   
        // check if the tbl_business_location exists before trying to edit it
        $data['tbl_business_location'] = $this->Tbl_business_location_model->get_tbl_business_location($location_id);
        
        if(isset($data['tbl_business_location']['location_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_business_id' => $this->input->post('fk_business_id'),
					'travel_to_customer' => $this->input->post('travel_to_customer'),
					'street_address' => $this->input->post('street_address'),
					'street_address2' => $this->input->post('street_address2'),
					'street_address3' => $this->input->post('street_address3'),
					'city' => $this->input->post('city'),
					'district' => $this->input->post('district'),
					'country' => $this->input->post('country'),
					'zip' => $this->input->post('zip'),
					'phone' => $this->input->post('phone'),
					'ada_accessible' => $this->input->post('ada_accessible'),
					'parking' => $this->input->post('parking'),
					'language' => $this->input->post('language'),
					'location_detail' => $this->input->post('location_detail'),
					'latitude' => $this->input->post('latitude'),
					'longitude' => $this->input->post('longitude'),
					'is_active' => $this->input->post('is_active'),
					'giolocation' => $this->input->post('giolocation'),
					'event_conduct' => $this->input->post('event_conduct'),
					'service_conduct' => $this->input->post('service_conduct'),
					'staff_conduct' => $this->input->post('staff_conduct'),
                );

                $this->Tbl_business_location_model->update_tbl_business_location($location_id,$params);            
                redirect('tbl_business_location/index');
            }
            else
            {
                $data['_view'] = 'tbl_business_location/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_business_location you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_business_location
     */
    function remove($location_id)
    {
        $tbl_business_location = $this->Tbl_business_location_model->get_tbl_business_location($location_id);

        // check if the tbl_business_location exists before trying to delete it
        if(isset($tbl_business_location['location_id']))
        {
            $this->Tbl_business_location_model->delete_tbl_business_location($location_id);
            redirect('tbl_business_location/index');
        }
        else
            show_error('The tbl_business_location you are trying to delete does not exist.');
    }
    
}
