<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_service_pakage extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_service_pakage_model');
    } 

    /*
     * Listing of tbl_service_pakages
     */
    function index()
    {
        $data['tbl_service_pakages'] = $this->Tbl_service_pakage_model->get_all_tbl_service_pakages();
        
        $data['_view'] = 'tbl_service_pakage/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_service_pakage
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'pakage_name' => $this->input->post('pakage_name'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'pakage_qty' => $this->input->post('pakage_qty'),
				'pakage_duration' => $this->input->post('pakage_duration'),
				'price' => $this->input->post('price'),
				'date' => $this->input->post('date'),
				'is_delete' => $this->input->post('is_delete'),
				'pk_service_menu_id' => $this->input->post('pk_service_menu_id'),
            );
            
            $tbl_service_pakage_id = $this->Tbl_service_pakage_model->add_tbl_service_pakage($params);
            redirect('tbl_service_pakage/index');
        }
        else
        {            
            $data['_view'] = 'tbl_service_pakage/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_service_pakage
     */
    function edit($ser_pk_id)
    {   
        // check if the tbl_service_pakage exists before trying to edit it
        $data['tbl_service_pakage'] = $this->Tbl_service_pakage_model->get_tbl_service_pakage($ser_pk_id);
        
        if(isset($data['tbl_service_pakage']['ser_pk_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'pakage_name' => $this->input->post('pakage_name'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'pakage_qty' => $this->input->post('pakage_qty'),
					'pakage_duration' => $this->input->post('pakage_duration'),
					'price' => $this->input->post('price'),
					'date' => $this->input->post('date'),
					'is_delete' => $this->input->post('is_delete'),
					'pk_service_menu_id' => $this->input->post('pk_service_menu_id'),
                );

                $this->Tbl_service_pakage_model->update_tbl_service_pakage($ser_pk_id,$params);            
                redirect('tbl_service_pakage/index');
            }
            else
            {
                $data['_view'] = 'tbl_service_pakage/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_service_pakage you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_service_pakage
     */
    function remove($ser_pk_id)
    {
        $tbl_service_pakage = $this->Tbl_service_pakage_model->get_tbl_service_pakage($ser_pk_id);

        // check if the tbl_service_pakage exists before trying to delete it
        if(isset($tbl_service_pakage['ser_pk_id']))
        {
            $this->Tbl_service_pakage_model->delete_tbl_service_pakage($ser_pk_id);
            redirect('tbl_service_pakage/index');
        }
        else
            show_error('The tbl_service_pakage you are trying to delete does not exist.');
    }
    
}
