<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_contact_inquiry extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_contact_inquiry_model');
    } 

    /*
     * Listing of tbl_contact_inquiries
     */
    function index()
    {
        $data['tbl_contact_inquiries'] = $this->Tbl_contact_inquiry_model->get_all_tbl_contact_inquiries();
        
        $data['_view'] = 'tbl_contact_inquiry/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_contact_inquiry
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'email' => $this->input->post('email'),
				'subject' => $this->input->post('subject'),
				'type_of_business' => $this->input->post('type_of_business'),
				'mobile_no' => $this->input->post('mobile_no'),
				'date_time' => $this->input->post('date_time'),
				'seen_status' => $this->input->post('seen_status'),
				'country' => $this->input->post('country'),
				'appointment_date' => $this->input->post('appointment_date'),
				'appointment_time' => $this->input->post('appointment_time'),
				'message' => $this->input->post('message'),
            );
            
            $tbl_contact_inquiry_id = $this->Tbl_contact_inquiry_model->add_tbl_contact_inquiry($params);
            redirect('tbl_contact_inquiry/index');
        }
        else
        {            
            $data['_view'] = 'tbl_contact_inquiry/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_contact_inquiry
     */
    function edit($contact_id)
    {   
        // check if the tbl_contact_inquiry exists before trying to edit it
        $data['tbl_contact_inquiry'] = $this->Tbl_contact_inquiry_model->get_tbl_contact_inquiry($contact_id);
        
        if(isset($data['tbl_contact_inquiry']['contact_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'email' => $this->input->post('email'),
					'subject' => $this->input->post('subject'),
					'type_of_business' => $this->input->post('type_of_business'),
					'mobile_no' => $this->input->post('mobile_no'),
					'date_time' => $this->input->post('date_time'),
					'seen_status' => $this->input->post('seen_status'),
					'country' => $this->input->post('country'),
					'appointment_date' => $this->input->post('appointment_date'),
					'appointment_time' => $this->input->post('appointment_time'),
					'message' => $this->input->post('message'),
                );

                $this->Tbl_contact_inquiry_model->update_tbl_contact_inquiry($contact_id,$params);            
                redirect('tbl_contact_inquiry/index');
            }
            else
            {
                $data['_view'] = 'tbl_contact_inquiry/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_contact_inquiry you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_contact_inquiry
     */
    function remove($contact_id)
    {
        $tbl_contact_inquiry = $this->Tbl_contact_inquiry_model->get_tbl_contact_inquiry($contact_id);

        // check if the tbl_contact_inquiry exists before trying to delete it
        if(isset($tbl_contact_inquiry['contact_id']))
        {
            $this->Tbl_contact_inquiry_model->delete_tbl_contact_inquiry($contact_id);
            redirect('tbl_contact_inquiry/index');
        }
        else
            show_error('The tbl_contact_inquiry you are trying to delete does not exist.');
    }
    
}
