<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_services_staff extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_services_staff_model');
    } 

    /*
     * Listing of tbl_services_staff
     */
    function index()
    {
        $data['tbl_services_staff'] = $this->Tbl_services_staff_model->get_all_tbl_services_staff();
        
        $data['_view'] = 'tbl_services_staff/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_services_staff
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_location_id' => $this->input->post('fk_location_id'),
				'fk_service_id' => $this->input->post('fk_service_id'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'fk_staff_id' => $this->input->post('fk_staff_id'),
            );
            
            $tbl_services_staff_id = $this->Tbl_services_staff_model->add_tbl_services_staff($params);
            redirect('tbl_services_staff/index');
        }
        else
        {            
            $data['_view'] = 'tbl_services_staff/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_services_staff
     */
    function edit($id)
    {   
        // check if the tbl_services_staff exists before trying to edit it
        $data['tbl_services_staff'] = $this->Tbl_services_staff_model->get_tbl_services_staff($id);
        
        if(isset($data['tbl_services_staff']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_location_id' => $this->input->post('fk_location_id'),
					'fk_service_id' => $this->input->post('fk_service_id'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'fk_staff_id' => $this->input->post('fk_staff_id'),
                );

                $this->Tbl_services_staff_model->update_tbl_services_staff($id,$params);            
                redirect('tbl_services_staff/index');
            }
            else
            {
                $data['_view'] = 'tbl_services_staff/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_services_staff you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_services_staff
     */
    function remove($id)
    {
        $tbl_services_staff = $this->Tbl_services_staff_model->get_tbl_services_staff($id);

        // check if the tbl_services_staff exists before trying to delete it
        if(isset($tbl_services_staff['id']))
        {
            $this->Tbl_services_staff_model->delete_tbl_services_staff($id);
            redirect('tbl_services_staff/index');
        }
        else
            show_error('The tbl_services_staff you are trying to delete does not exist.');
    }
    
}
