<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_automated_event extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_automated_event_model');
    } 

    /*
     * Listing of tbl_automated_event
     */
    function index()
    {
        $data['tbl_automated_event'] = $this->Tbl_automated_event_model->get_all_tbl_automated_event();
        
        $data['_view'] = 'tbl_automated_event/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_automated_event
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'event_category_name' => $this->input->post('event_category_name'),
				'event_name' => $this->input->post('event_name'),
				'event_sub_title' => $this->input->post('event_sub_title'),
				'message_body_one' => $this->input->post('message_body_one'),
				'message_body_two' => $this->input->post('message_body_two'),
				'subject' => $this->input->post('subject'),
            );
            
            $tbl_automated_event_id = $this->Tbl_automated_event_model->add_tbl_automated_event($params);
            redirect('tbl_automated_event/index');
        }
        else
        {            
            $data['_view'] = 'tbl_automated_event/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_automated_event
     */
    function edit($event_type_id)
    {   
        // check if the tbl_automated_event exists before trying to edit it
        $data['tbl_automated_event'] = $this->Tbl_automated_event_model->get_tbl_automated_event($event_type_id);
        
        if(isset($data['tbl_automated_event']['event_type_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'event_category_name' => $this->input->post('event_category_name'),
					'event_name' => $this->input->post('event_name'),
					'event_sub_title' => $this->input->post('event_sub_title'),
					'message_body_one' => $this->input->post('message_body_one'),
					'message_body_two' => $this->input->post('message_body_two'),
					'subject' => $this->input->post('subject'),
                );

                $this->Tbl_automated_event_model->update_tbl_automated_event($event_type_id,$params);            
                redirect('tbl_automated_event/index');
            }
            else
            {
                $data['_view'] = 'tbl_automated_event/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_automated_event you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_automated_event
     */
    function remove($event_type_id)
    {
        $tbl_automated_event = $this->Tbl_automated_event_model->get_tbl_automated_event($event_type_id);

        // check if the tbl_automated_event exists before trying to delete it
        if(isset($tbl_automated_event['event_type_id']))
        {
            $this->Tbl_automated_event_model->delete_tbl_automated_event($event_type_id);
            redirect('tbl_automated_event/index');
        }
        else
            show_error('The tbl_automated_event you are trying to delete does not exist.');
    }
    
}
