<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_businessuser_promocode extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_businessuser_promocode_model');
    } 

    /*
     * Listing of tbl_businessuser_promocode
     */
    function index()
    {
        $data['tbl_businessuser_promocode'] = $this->Tbl_businessuser_promocode_model->get_all_tbl_businessuser_promocode();
        
        $data['_view'] = 'tbl_businessuser_promocode/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_businessuser_promocode
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'business_id' => $this->input->post('business_id'),
				'promo_code' => $this->input->post('promo_code'),
				'promo_nickname' => $this->input->post('promo_nickname'),
				'promo_discount' => $this->input->post('promo_discount'),
				'discount_type' => $this->input->post('discount_type'),
				'promo_start_date' => $this->input->post('promo_start_date'),
				'promo_end_date' => $this->input->post('promo_end_date'),
				'one_use' => $this->input->post('one_use'),
				'new_client' => $this->input->post('new_client'),
				'promo_location' => $this->input->post('promo_location'),
				'promo_staff' => $this->input->post('promo_staff'),
				'promo_services' => $this->input->post('promo_services'),
				'promocode_status' => $this->input->post('promocode_status'),
				'fk_user_id' => $this->input->post('fk_user_id'),
            );
            
            $tbl_businessuser_promocode_id = $this->Tbl_businessuser_promocode_model->add_tbl_businessuser_promocode($params);
            redirect('tbl_businessuser_promocode/index');
        }
        else
        {            
            $data['_view'] = 'tbl_businessuser_promocode/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_businessuser_promocode
     */
    function edit($promo_id)
    {   
        // check if the tbl_businessuser_promocode exists before trying to edit it
        $data['tbl_businessuser_promocode'] = $this->Tbl_businessuser_promocode_model->get_tbl_businessuser_promocode($promo_id);
        
        if(isset($data['tbl_businessuser_promocode']['promo_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'business_id' => $this->input->post('business_id'),
					'promo_code' => $this->input->post('promo_code'),
					'promo_nickname' => $this->input->post('promo_nickname'),
					'promo_discount' => $this->input->post('promo_discount'),
					'discount_type' => $this->input->post('discount_type'),
					'promo_start_date' => $this->input->post('promo_start_date'),
					'promo_end_date' => $this->input->post('promo_end_date'),
					'one_use' => $this->input->post('one_use'),
					'new_client' => $this->input->post('new_client'),
					'promo_location' => $this->input->post('promo_location'),
					'promo_staff' => $this->input->post('promo_staff'),
					'promo_services' => $this->input->post('promo_services'),
					'promocode_status' => $this->input->post('promocode_status'),
					'fk_user_id' => $this->input->post('fk_user_id'),
                );

                $this->Tbl_businessuser_promocode_model->update_tbl_businessuser_promocode($promo_id,$params);            
                redirect('tbl_businessuser_promocode/index');
            }
            else
            {
                $data['_view'] = 'tbl_businessuser_promocode/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_businessuser_promocode you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_businessuser_promocode
     */
    function remove($promo_id)
    {
        $tbl_businessuser_promocode = $this->Tbl_businessuser_promocode_model->get_tbl_businessuser_promocode($promo_id);

        // check if the tbl_businessuser_promocode exists before trying to delete it
        if(isset($tbl_businessuser_promocode['promo_id']))
        {
            $this->Tbl_businessuser_promocode_model->delete_tbl_businessuser_promocode($promo_id);
            redirect('tbl_businessuser_promocode/index');
        }
        else
            show_error('The tbl_businessuser_promocode you are trying to delete does not exist.');
    }
    
}
