<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_campaign_template extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_campaign_template_model');
    } 

    /*
     * Listing of tbl_campaign_templates
     */
    function index()
    {
        $data['tbl_campaign_templates'] = $this->Tbl_campaign_template_model->get_all_tbl_campaign_templates();
        
        $data['_view'] = 'tbl_campaign_template/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_campaign_template
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'campaign_id' => $this->input->post('campaign_id'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'template_name' => $this->input->post('template_name'),
				'category' => $this->input->post('category'),
				'subject' => $this->input->post('subject'),
				'reply_to_name' => $this->input->post('reply_to_name'),
				'reply_to_email' => $this->input->post('reply_to_email'),
				'message_body' => $this->input->post('message_body'),
            );
            
            $tbl_campaign_template_id = $this->Tbl_campaign_template_model->add_tbl_campaign_template($params);
            redirect('tbl_campaign_template/index');
        }
        else
        {            
            $data['_view'] = 'tbl_campaign_template/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_campaign_template
     */
    function edit($template_id)
    {   
        // check if the tbl_campaign_template exists before trying to edit it
        $data['tbl_campaign_template'] = $this->Tbl_campaign_template_model->get_tbl_campaign_template($template_id);
        
        if(isset($data['tbl_campaign_template']['template_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'campaign_id' => $this->input->post('campaign_id'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'template_name' => $this->input->post('template_name'),
					'category' => $this->input->post('category'),
					'subject' => $this->input->post('subject'),
					'reply_to_name' => $this->input->post('reply_to_name'),
					'reply_to_email' => $this->input->post('reply_to_email'),
					'message_body' => $this->input->post('message_body'),
                );

                $this->Tbl_campaign_template_model->update_tbl_campaign_template($template_id,$params);            
                redirect('tbl_campaign_template/index');
            }
            else
            {
                $data['_view'] = 'tbl_campaign_template/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_campaign_template you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_campaign_template
     */
    function remove($template_id)
    {
        $tbl_campaign_template = $this->Tbl_campaign_template_model->get_tbl_campaign_template($template_id);

        // check if the tbl_campaign_template exists before trying to delete it
        if(isset($tbl_campaign_template['template_id']))
        {
            $this->Tbl_campaign_template_model->delete_tbl_campaign_template($template_id);
            redirect('tbl_campaign_template/index');
        }
        else
            show_error('The tbl_campaign_template you are trying to delete does not exist.');
    }
    
}
