<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_client_custom_price extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_client_custom_price_model');
    } 

    /*
     * Listing of tbl_client_custom_price
     */
    function index()
    {
        $data['tbl_client_custom_price'] = $this->Tbl_client_custom_price_model->get_all_tbl_client_custom_price();
        
        $data['_view'] = 'tbl_client_custom_price/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_client_custom_price
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_client_id' => $this->input->post('fk_client_id'),
				'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
				'fk_staff_id' => $this->input->post('fk_staff_id'),
				'custom_price' => $this->input->post('custom_price'),
            );
            
            $tbl_client_custom_price_id = $this->Tbl_client_custom_price_model->add_tbl_client_custom_price($params);
            redirect('tbl_client_custom_price/index');
        }
        else
        {            
            $data['_view'] = 'tbl_client_custom_price/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_client_custom_price
     */
    function edit($custom_price_id)
    {   
        // check if the tbl_client_custom_price exists before trying to edit it
        $data['tbl_client_custom_price'] = $this->Tbl_client_custom_price_model->get_tbl_client_custom_price($custom_price_id);
        
        if(isset($data['tbl_client_custom_price']['custom_price_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_client_id' => $this->input->post('fk_client_id'),
					'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
					'fk_staff_id' => $this->input->post('fk_staff_id'),
					'custom_price' => $this->input->post('custom_price'),
                );

                $this->Tbl_client_custom_price_model->update_tbl_client_custom_price($custom_price_id,$params);            
                redirect('tbl_client_custom_price/index');
            }
            else
            {
                $data['_view'] = 'tbl_client_custom_price/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_client_custom_price you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_client_custom_price
     */
    function remove($custom_price_id)
    {
        $tbl_client_custom_price = $this->Tbl_client_custom_price_model->get_tbl_client_custom_price($custom_price_id);

        // check if the tbl_client_custom_price exists before trying to delete it
        if(isset($tbl_client_custom_price['custom_price_id']))
        {
            $this->Tbl_client_custom_price_model->delete_tbl_client_custom_price($custom_price_id);
            redirect('tbl_client_custom_price/index');
        }
        else
            show_error('The tbl_client_custom_price you are trying to delete does not exist.');
    }
    
}
