<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_client extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_client_model');
    } 

    /*
     * Listing of tbl_client
     */
    function index()
    {
        $data['tbl_client'] = $this->Tbl_client_model->get_all_tbl_client();
        
        $data['_view'] = 'tbl_client/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_client
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_business_id' => $this->input->post('fk_business_id'),
				'fk_user_id' => $this->input->post('fk_user_id'),
				'fname' => $this->input->post('fname'),
				'lname' => $this->input->post('lname'),
				'email' => $this->input->post('email'),
				'mobile_phone' => $this->input->post('mobile_phone'),
				'home_phone' => $this->input->post('home_phone'),
				'work_phone' => $this->input->post('work_phone'),
				'profile_image' => $this->input->post('profile_image'),
				'client_since' => $this->input->post('client_since'),
				'fk_location_id' => $this->input->post('fk_location_id'),
				'fk_staff_id' => $this->input->post('fk_staff_id'),
				'contact_preference' => $this->input->post('contact_preference'),
				'date_of_birth' => $this->input->post('date_of_birth'),
				'gender' => $this->input->post('gender'),
				'is_booking' => $this->input->post('is_booking'),
				'client_notes' => $this->input->post('client_notes'),
				'edited_on' => $this->input->post('edited_on'),
				'is_delete' => $this->input->post('is_delete'),
            );
            
            $tbl_client_id = $this->Tbl_client_model->add_tbl_client($params);
            redirect('tbl_client/index');
        }
        else
        {            
            $data['_view'] = 'tbl_client/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_client
     */
    function edit($client_id)
    {   
        // check if the tbl_client exists before trying to edit it
        $data['tbl_client'] = $this->Tbl_client_model->get_tbl_client($client_id);
        
        if(isset($data['tbl_client']['client_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_business_id' => $this->input->post('fk_business_id'),
					'fk_user_id' => $this->input->post('fk_user_id'),
					'fname' => $this->input->post('fname'),
					'lname' => $this->input->post('lname'),
					'email' => $this->input->post('email'),
					'mobile_phone' => $this->input->post('mobile_phone'),
					'home_phone' => $this->input->post('home_phone'),
					'work_phone' => $this->input->post('work_phone'),
					'profile_image' => $this->input->post('profile_image'),
					'client_since' => $this->input->post('client_since'),
					'fk_location_id' => $this->input->post('fk_location_id'),
					'fk_staff_id' => $this->input->post('fk_staff_id'),
					'contact_preference' => $this->input->post('contact_preference'),
					'date_of_birth' => $this->input->post('date_of_birth'),
					'gender' => $this->input->post('gender'),
					'is_booking' => $this->input->post('is_booking'),
					'client_notes' => $this->input->post('client_notes'),
					'edited_on' => $this->input->post('edited_on'),
					'is_delete' => $this->input->post('is_delete'),
                );

                $this->Tbl_client_model->update_tbl_client($client_id,$params);            
                redirect('tbl_client/index');
            }
            else
            {
                $data['_view'] = 'tbl_client/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_client you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_client
     */
    function remove($client_id)
    {
        $tbl_client = $this->Tbl_client_model->get_tbl_client($client_id);

        // check if the tbl_client exists before trying to delete it
        if(isset($tbl_client['client_id']))
        {
            $this->Tbl_client_model->delete_tbl_client($client_id);
            redirect('tbl_client/index');
        }
        else
            show_error('The tbl_client you are trying to delete does not exist.');
    }
    
}
