<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_cover_information extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_business_cover_information_model');
    } 

    /*
     * Listing of tbl_business_cover_information
     */
    function index()
    {
        $data['tbl_business_cover_information'] = $this->Tbl_business_cover_information_model->get_all_tbl_business_cover_information();
        
        $data['_view'] = 'tbl_business_cover_information/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_business_cover_information
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'cover_id' => $this->input->post('cover_id'),
				'fk_business_id' => $this->input->post('fk_business_id'),
				'cover_photo' => $this->input->post('cover_photo'),
				'text_one' => $this->input->post('text_one'),
				'text_two' => $this->input->post('text_two'),
				'text_three' => $this->input->post('text_three'),
            );
            
            $tbl_business_cover_information_id = $this->Tbl_business_cover_information_model->add_tbl_business_cover_information($params);
            redirect('tbl_business_cover_information/index');
        }
        else
        {            
            $data['_view'] = 'tbl_business_cover_information/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_business_cover_information
     */
    function edit($)
    {   
        // check if the tbl_business_cover_information exists before trying to edit it
        $data['tbl_business_cover_information'] = $this->Tbl_business_cover_information_model->get_tbl_business_cover_information($);
        
        if(isset($data['tbl_business_cover_information']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'cover_id' => $this->input->post('cover_id'),
					'fk_business_id' => $this->input->post('fk_business_id'),
					'cover_photo' => $this->input->post('cover_photo'),
					'text_one' => $this->input->post('text_one'),
					'text_two' => $this->input->post('text_two'),
					'text_three' => $this->input->post('text_three'),
                );

                $this->Tbl_business_cover_information_model->update_tbl_business_cover_information($,$params);            
                redirect('tbl_business_cover_information/index');
            }
            else
            {
                $data['_view'] = 'tbl_business_cover_information/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_business_cover_information you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_business_cover_information
     */
    function remove($)
    {
        $tbl_business_cover_information = $this->Tbl_business_cover_information_model->get_tbl_business_cover_information($);

        // check if the tbl_business_cover_information exists before trying to delete it
        if(isset($tbl_business_cover_information['']))
        {
            $this->Tbl_business_cover_information_model->delete_tbl_business_cover_information($);
            redirect('tbl_business_cover_information/index');
        }
        else
            show_error('The tbl_business_cover_information you are trying to delete does not exist.');
    }
    
}
