<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_deposit_storage extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_deposit_storage_model');
    } 

    /*
     * Listing of tbl_deposit_storage
     */
    function index()
    {
        $data['tbl_deposit_storage'] = $this->Tbl_deposit_storage_model->get_all_tbl_deposit_storage();
        
        $data['_view'] = 'tbl_deposit_storage/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_deposit_storage
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_user_id' => $this->input->post('fk_user_id'),
				'paypal_email' => $this->input->post('paypal_email'),
				'paper_check' => $this->input->post('paper_check'),
				'selected' => $this->input->post('selected'),
				'direct_deposit' => $this->input->post('direct_deposit'),
            );
            
            $tbl_deposit_storage_id = $this->Tbl_deposit_storage_model->add_tbl_deposit_storage($params);
            redirect('tbl_deposit_storage/index');
        }
        else
        {            
            $data['_view'] = 'tbl_deposit_storage/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_deposit_storage
     */
    function edit($deposit_info_id)
    {   
        // check if the tbl_deposit_storage exists before trying to edit it
        $data['tbl_deposit_storage'] = $this->Tbl_deposit_storage_model->get_tbl_deposit_storage($deposit_info_id);
        
        if(isset($data['tbl_deposit_storage']['deposit_info_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_user_id' => $this->input->post('fk_user_id'),
					'paypal_email' => $this->input->post('paypal_email'),
					'paper_check' => $this->input->post('paper_check'),
					'selected' => $this->input->post('selected'),
					'direct_deposit' => $this->input->post('direct_deposit'),
                );

                $this->Tbl_deposit_storage_model->update_tbl_deposit_storage($deposit_info_id,$params);            
                redirect('tbl_deposit_storage/index');
            }
            else
            {
                $data['_view'] = 'tbl_deposit_storage/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_deposit_storage you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_deposit_storage
     */
    function remove($deposit_info_id)
    {
        $tbl_deposit_storage = $this->Tbl_deposit_storage_model->get_tbl_deposit_storage($deposit_info_id);

        // check if the tbl_deposit_storage exists before trying to delete it
        if(isset($tbl_deposit_storage['deposit_info_id']))
        {
            $this->Tbl_deposit_storage_model->delete_tbl_deposit_storage($deposit_info_id);
            redirect('tbl_deposit_storage/index');
        }
        else
            show_error('The tbl_deposit_storage you are trying to delete does not exist.');
    }
    
}
