<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_labe extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_business_labe_model');
    } 

    /*
     * Listing of tbl_business_labes
     */
    function index()
    {
        $data['tbl_business_labes'] = $this->Tbl_business_labe_model->get_all_tbl_business_labes();
        
        $data['_view'] = 'tbl_business_labe/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_business_labe
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id' => $this->input->post('id'),
				'fk_user_id' => $this->input->post('fk_user_id'),
				'label_name' => $this->input->post('label_name'),
				'fk_business_id' => $this->input->post('fk_business_id'),
            );
            
            $tbl_business_labe_id = $this->Tbl_business_labe_model->add_tbl_business_labe($params);
            redirect('tbl_business_labe/index');
        }
        else
        {            
            $data['_view'] = 'tbl_business_labe/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_business_labe
     */
    function edit($)
    {   
        // check if the tbl_business_labe exists before trying to edit it
        $data['tbl_business_labe'] = $this->Tbl_business_labe_model->get_tbl_business_labe($);
        
        if(isset($data['tbl_business_labe']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id' => $this->input->post('id'),
					'fk_user_id' => $this->input->post('fk_user_id'),
					'label_name' => $this->input->post('label_name'),
					'fk_business_id' => $this->input->post('fk_business_id'),
                );

                $this->Tbl_business_labe_model->update_tbl_business_labe($,$params);            
                redirect('tbl_business_labe/index');
            }
            else
            {
                $data['_view'] = 'tbl_business_labe/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_business_labe you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_business_labe
     */
    function remove($)
    {
        $tbl_business_labe = $this->Tbl_business_labe_model->get_tbl_business_labe($);

        // check if the tbl_business_labe exists before trying to delete it
        if(isset($tbl_business_labe['']))
        {
            $this->Tbl_business_labe_model->delete_tbl_business_labe($);
            redirect('tbl_business_labe/index');
        }
        else
            show_error('The tbl_business_labe you are trying to delete does not exist.');
    }
    
}
