<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_cc_datum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_cc_datum_model');
    } 

    /*
     * Listing of tbl_cc_data
     */
    function index()
    {
        $data['tbl_cc_data'] = $this->Tbl_cc_datum_model->get_all_tbl_cc_data();
        
        $data['_view'] = 'tbl_cc_datum/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_cc_datum
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_user_id' => $this->input->post('fk_user_id'),
				'cc_end_number' => $this->input->post('cc_end_number'),
				'is_active' => $this->input->post('is_active'),
				'data' => $this->input->post('data'),
            );
            
            $tbl_cc_datum_id = $this->Tbl_cc_datum_model->add_tbl_cc_datum($params);
            redirect('tbl_cc_datum/index');
        }
        else
        {            
            $data['_view'] = 'tbl_cc_datum/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_cc_datum
     */
    function edit($cc_data_id)
    {   
        // check if the tbl_cc_datum exists before trying to edit it
        $data['tbl_cc_datum'] = $this->Tbl_cc_datum_model->get_tbl_cc_datum($cc_data_id);
        
        if(isset($data['tbl_cc_datum']['cc_data_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_user_id' => $this->input->post('fk_user_id'),
					'cc_end_number' => $this->input->post('cc_end_number'),
					'is_active' => $this->input->post('is_active'),
					'data' => $this->input->post('data'),
                );

                $this->Tbl_cc_datum_model->update_tbl_cc_datum($cc_data_id,$params);            
                redirect('tbl_cc_datum/index');
            }
            else
            {
                $data['_view'] = 'tbl_cc_datum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_cc_datum you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_cc_datum
     */
    function remove($cc_data_id)
    {
        $tbl_cc_datum = $this->Tbl_cc_datum_model->get_tbl_cc_datum($cc_data_id);

        // check if the tbl_cc_datum exists before trying to delete it
        if(isset($tbl_cc_datum['cc_data_id']))
        {
            $this->Tbl_cc_datum_model->delete_tbl_cc_datum($cc_data_id);
            redirect('tbl_cc_datum/index');
        }
        else
            show_error('The tbl_cc_datum you are trying to delete does not exist.');
    }
    
}
