<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_site_setting extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_site_setting_model');
    } 

    /*
     * Listing of tbl_site_settings
     */
    function index()
    {
        $data['tbl_site_settings'] = $this->Tbl_site_setting_model->get_all_tbl_site_settings();
        
        $data['_view'] = 'tbl_site_setting/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_site_setting
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'stripe_tansaction_fees' => $this->input->post('stripe_tansaction_fees'),
            );
            
            $tbl_site_setting_id = $this->Tbl_site_setting_model->add_tbl_site_setting($params);
            redirect('tbl_site_setting/index');
        }
        else
        {            
            $data['_view'] = 'tbl_site_setting/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_site_setting
     */
    function edit($id)
    {   
        // check if the tbl_site_setting exists before trying to edit it
        $data['tbl_site_setting'] = $this->Tbl_site_setting_model->get_tbl_site_setting($id);
        
        if(isset($data['tbl_site_setting']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'stripe_tansaction_fees' => $this->input->post('stripe_tansaction_fees'),
                );

                $this->Tbl_site_setting_model->update_tbl_site_setting($id,$params);            
                redirect('tbl_site_setting/index');
            }
            else
            {
                $data['_view'] = 'tbl_site_setting/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_site_setting you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_site_setting
     */
    function remove($id)
    {
        $tbl_site_setting = $this->Tbl_site_setting_model->get_tbl_site_setting($id);

        // check if the tbl_site_setting exists before trying to delete it
        if(isset($tbl_site_setting['id']))
        {
            $this->Tbl_site_setting_model->delete_tbl_site_setting($id);
            redirect('tbl_site_setting/index');
        }
        else
            show_error('The tbl_site_setting you are trying to delete does not exist.');
    }
    
}
