<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_campaign_default extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_campaign_default_model');
    } 

    /*
     * Listing of tbl_campaign_default
     */
    function index()
    {
        $data['tbl_campaign_default'] = $this->Tbl_campaign_default_model->get_all_tbl_campaign_default();
        
        $data['_view'] = 'tbl_campaign_default/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_campaign_default
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'category' => $this->input->post('category'),
				'campaign_name' => $this->input->post('campaign_name'),
				'sub_title' => $this->input->post('sub_title'),
				'subject_default' => $this->input->post('subject_default'),
				'campaign_body' => $this->input->post('campaign_body'),
            );
            
            $tbl_campaign_default_id = $this->Tbl_campaign_default_model->add_tbl_campaign_default($params);
            redirect('tbl_campaign_default/index');
        }
        else
        {            
            $data['_view'] = 'tbl_campaign_default/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_campaign_default
     */
    function edit($campaign_id)
    {   
        // check if the tbl_campaign_default exists before trying to edit it
        $data['tbl_campaign_default'] = $this->Tbl_campaign_default_model->get_tbl_campaign_default($campaign_id);
        
        if(isset($data['tbl_campaign_default']['campaign_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'category' => $this->input->post('category'),
					'campaign_name' => $this->input->post('campaign_name'),
					'sub_title' => $this->input->post('sub_title'),
					'subject_default' => $this->input->post('subject_default'),
					'campaign_body' => $this->input->post('campaign_body'),
                );

                $this->Tbl_campaign_default_model->update_tbl_campaign_default($campaign_id,$params);            
                redirect('tbl_campaign_default/index');
            }
            else
            {
                $data['_view'] = 'tbl_campaign_default/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_campaign_default you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_campaign_default
     */
    function remove($campaign_id)
    {
        $tbl_campaign_default = $this->Tbl_campaign_default_model->get_tbl_campaign_default($campaign_id);

        // check if the tbl_campaign_default exists before trying to delete it
        if(isset($tbl_campaign_default['campaign_id']))
        {
            $this->Tbl_campaign_default_model->delete_tbl_campaign_default($campaign_id);
            redirect('tbl_campaign_default/index');
        }
        else
            show_error('The tbl_campaign_default you are trying to delete does not exist.');
    }
    
}
