<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_staff_block_off_time extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_staff_block_off_time_model');
    } 

    /*
     * Listing of tbl_staff_block_off_time
     */
    function index()
    {
        $data['tbl_staff_block_off_time'] = $this->Tbl_staff_block_off_time_model->get_all_tbl_staff_block_off_time();
        
        $data['_view'] = 'tbl_staff_block_off_time/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_staff_block_off_time
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_business_id' => $this->input->post('fk_business_id'),
				'fk_location_id' => $this->input->post('fk_location_id'),
				'fk_staff_id' => $this->input->post('fk_staff_id'),
				'block_off_title' => $this->input->post('block_off_title'),
				'block_off_start_date' => $this->input->post('block_off_start_date'),
				'block_off_end_date' => $this->input->post('block_off_end_date'),
				'block_off_start_time' => $this->input->post('block_off_start_time'),
				'block_off_end_time' => $this->input->post('block_off_end_time'),
				'off_note' => $this->input->post('off_note'),
            );
            
            $tbl_staff_block_off_time_id = $this->Tbl_staff_block_off_time_model->add_tbl_staff_block_off_time($params);
            redirect('tbl_staff_block_off_time/index');
        }
        else
        {            
            $data['_view'] = 'tbl_staff_block_off_time/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_staff_block_off_time
     */
    function edit($block_off_id)
    {   
        // check if the tbl_staff_block_off_time exists before trying to edit it
        $data['tbl_staff_block_off_time'] = $this->Tbl_staff_block_off_time_model->get_tbl_staff_block_off_time($block_off_id);
        
        if(isset($data['tbl_staff_block_off_time']['block_off_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_business_id' => $this->input->post('fk_business_id'),
					'fk_location_id' => $this->input->post('fk_location_id'),
					'fk_staff_id' => $this->input->post('fk_staff_id'),
					'block_off_title' => $this->input->post('block_off_title'),
					'block_off_start_date' => $this->input->post('block_off_start_date'),
					'block_off_end_date' => $this->input->post('block_off_end_date'),
					'block_off_start_time' => $this->input->post('block_off_start_time'),
					'block_off_end_time' => $this->input->post('block_off_end_time'),
					'off_note' => $this->input->post('off_note'),
                );

                $this->Tbl_staff_block_off_time_model->update_tbl_staff_block_off_time($block_off_id,$params);            
                redirect('tbl_staff_block_off_time/index');
            }
            else
            {
                $data['_view'] = 'tbl_staff_block_off_time/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_staff_block_off_time you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_staff_block_off_time
     */
    function remove($block_off_id)
    {
        $tbl_staff_block_off_time = $this->Tbl_staff_block_off_time_model->get_tbl_staff_block_off_time($block_off_id);

        // check if the tbl_staff_block_off_time exists before trying to delete it
        if(isset($tbl_staff_block_off_time['block_off_id']))
        {
            $this->Tbl_staff_block_off_time_model->delete_tbl_staff_block_off_time($block_off_id);
            redirect('tbl_staff_block_off_time/index');
        }
        else
            show_error('The tbl_staff_block_off_time you are trying to delete does not exist.');
    }
    
}
