<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_communication_preference extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_communication_preference_model');
    } 

    /*
     * Listing of tbl_communication_preferences
     */
    function index()
    {
        $data['tbl_communication_preferences'] = $this->Tbl_communication_preference_model->get_all_tbl_communication_preferences();
        
        $data['_view'] = 'tbl_communication_preference/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_communication_preference
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_user_id' => $this->input->post('fk_user_id'),
				'receive_product_announcements' => $this->input->post('receive_product_announcements'),
				'email' => $this->input->post('email'),
				'sms' => $this->input->post('sms'),
            );
            
            $tbl_communication_preference_id = $this->Tbl_communication_preference_model->add_tbl_communication_preference($params);
            redirect('tbl_communication_preference/index');
        }
        else
        {            
            $data['_view'] = 'tbl_communication_preference/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_communication_preference
     */
    function edit($communication_preferences_id)
    {   
        // check if the tbl_communication_preference exists before trying to edit it
        $data['tbl_communication_preference'] = $this->Tbl_communication_preference_model->get_tbl_communication_preference($communication_preferences_id);
        
        if(isset($data['tbl_communication_preference']['communication_preferences_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_user_id' => $this->input->post('fk_user_id'),
					'receive_product_announcements' => $this->input->post('receive_product_announcements'),
					'email' => $this->input->post('email'),
					'sms' => $this->input->post('sms'),
                );

                $this->Tbl_communication_preference_model->update_tbl_communication_preference($communication_preferences_id,$params);            
                redirect('tbl_communication_preference/index');
            }
            else
            {
                $data['_view'] = 'tbl_communication_preference/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_communication_preference you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_communication_preference
     */
    function remove($communication_preferences_id)
    {
        $tbl_communication_preference = $this->Tbl_communication_preference_model->get_tbl_communication_preference($communication_preferences_id);

        // check if the tbl_communication_preference exists before trying to delete it
        if(isset($tbl_communication_preference['communication_preferences_id']))
        {
            $this->Tbl_communication_preference_model->delete_tbl_communication_preference($communication_preferences_id);
            redirect('tbl_communication_preference/index');
        }
        else
            show_error('The tbl_communication_preference you are trying to delete does not exist.');
    }
    
}
