<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_email_id_master extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_email_id_master_model');
    } 

    /*
     * Listing of tbl_email_id_master
     */
    function index()
    {
        $data['tbl_email_id_master'] = $this->Tbl_email_id_master_model->get_all_tbl_email_id_master();
        
        $data['_view'] = 'tbl_email_id_master/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_email_id_master
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'contact_email' => $this->input->post('contact_email'),
				'info_email' => $this->input->post('info_email'),
				'support_email' => $this->input->post('support_email'),
				'business_email' => $this->input->post('business_email'),
				'media_email' => $this->input->post('media_email'),
				'job_email' => $this->input->post('job_email'),
            );
            
            $tbl_email_id_master_id = $this->Tbl_email_id_master_model->add_tbl_email_id_master($params);
            redirect('tbl_email_id_master/index');
        }
        else
        {            
            $data['_view'] = 'tbl_email_id_master/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_email_id_master
     */
    function edit($id)
    {   
        // check if the tbl_email_id_master exists before trying to edit it
        $data['tbl_email_id_master'] = $this->Tbl_email_id_master_model->get_tbl_email_id_master($id);
        
        if(isset($data['tbl_email_id_master']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'contact_email' => $this->input->post('contact_email'),
					'info_email' => $this->input->post('info_email'),
					'support_email' => $this->input->post('support_email'),
					'business_email' => $this->input->post('business_email'),
					'media_email' => $this->input->post('media_email'),
					'job_email' => $this->input->post('job_email'),
                );

                $this->Tbl_email_id_master_model->update_tbl_email_id_master($id,$params);            
                redirect('tbl_email_id_master/index');
            }
            else
            {
                $data['_view'] = 'tbl_email_id_master/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_email_id_master you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_email_id_master
     */
    function remove($id)
    {
        $tbl_email_id_master = $this->Tbl_email_id_master_model->get_tbl_email_id_master($id);

        // check if the tbl_email_id_master exists before trying to delete it
        if(isset($tbl_email_id_master['id']))
        {
            $this->Tbl_email_id_master_model->delete_tbl_email_id_master($id);
            redirect('tbl_email_id_master/index');
        }
        else
            show_error('The tbl_email_id_master you are trying to delete does not exist.');
    }
    
}
