<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_setting extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_business_setting_model');
    } 

    /*
     * Listing of tbl_business_settings
     */
    function index()
    {
        $data['tbl_business_settings'] = $this->Tbl_business_setting_model->get_all_tbl_business_settings();
        
        $data['_view'] = 'tbl_business_setting/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_business_setting
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_business_id' => $this->input->post('fk_business_id'),
				'calender_system' => $this->input->post('calender_system'),
				'booking_time_interval' => $this->input->post('booking_time_interval'),
				'advance_marketplace_notice' => $this->input->post('advance_marketplace_notice'),
				'advance_booking_time' => $this->input->post('advance_booking_time'),
				'advance_booking_time_type' => $this->input->post('advance_booking_time_type'),
				'booking_entity' => $this->input->post('booking_entity'),
				'booking_auto_accept' => $this->input->post('booking_auto_accept'),
				'marketplace_booking_email' => $this->input->post('marketplace_booking_email'),
				'marketplace_booking_call_no' => $this->input->post('marketplace_booking_call_no'),
				'marketplace_booking_text_no' => $this->input->post('marketplace_booking_text_no'),
				'cancel_time' => $this->input->post('cancel_time'),
				'communicator_options' => $this->input->post('communicator_options'),
				'direct_staff_member_booking' => $this->input->post('direct_staff_member_booking'),
				'price_vary_by_location' => $this->input->post('price_vary_by_location'),
				'scheduler_access_level' => $this->input->post('scheduler_access_level'),
				'track_compensation' => $this->input->post('track_compensation'),
				'clock_in_out' => $this->input->post('clock_in_out'),
            );
            
            $tbl_business_setting_id = $this->Tbl_business_setting_model->add_tbl_business_setting($params);
            redirect('tbl_business_setting/index');
        }
        else
        {            
            $data['_view'] = 'tbl_business_setting/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_business_setting
     */
    function edit($settings_id)
    {   
        // check if the tbl_business_setting exists before trying to edit it
        $data['tbl_business_setting'] = $this->Tbl_business_setting_model->get_tbl_business_setting($settings_id);
        
        if(isset($data['tbl_business_setting']['settings_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_business_id' => $this->input->post('fk_business_id'),
					'calender_system' => $this->input->post('calender_system'),
					'booking_time_interval' => $this->input->post('booking_time_interval'),
					'advance_marketplace_notice' => $this->input->post('advance_marketplace_notice'),
					'advance_booking_time' => $this->input->post('advance_booking_time'),
					'advance_booking_time_type' => $this->input->post('advance_booking_time_type'),
					'booking_entity' => $this->input->post('booking_entity'),
					'booking_auto_accept' => $this->input->post('booking_auto_accept'),
					'marketplace_booking_email' => $this->input->post('marketplace_booking_email'),
					'marketplace_booking_call_no' => $this->input->post('marketplace_booking_call_no'),
					'marketplace_booking_text_no' => $this->input->post('marketplace_booking_text_no'),
					'cancel_time' => $this->input->post('cancel_time'),
					'communicator_options' => $this->input->post('communicator_options'),
					'direct_staff_member_booking' => $this->input->post('direct_staff_member_booking'),
					'price_vary_by_location' => $this->input->post('price_vary_by_location'),
					'scheduler_access_level' => $this->input->post('scheduler_access_level'),
					'track_compensation' => $this->input->post('track_compensation'),
					'clock_in_out' => $this->input->post('clock_in_out'),
                );

                $this->Tbl_business_setting_model->update_tbl_business_setting($settings_id,$params);            
                redirect('tbl_business_setting/index');
            }
            else
            {
                $data['_view'] = 'tbl_business_setting/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_business_setting you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_business_setting
     */
    function remove($settings_id)
    {
        $tbl_business_setting = $this->Tbl_business_setting_model->get_tbl_business_setting($settings_id);

        // check if the tbl_business_setting exists before trying to delete it
        if(isset($tbl_business_setting['settings_id']))
        {
            $this->Tbl_business_setting_model->delete_tbl_business_setting($settings_id);
            redirect('tbl_business_setting/index');
        }
        else
            show_error('The tbl_business_setting you are trying to delete does not exist.');
    }
    
}
