<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_service_time_slot extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_service_time_slot_model');
    } 

    /*
     * Listing of tbl_service_time_slots
     */
    function index()
    {
        $data['tbl_service_time_slots'] = $this->Tbl_service_time_slot_model->get_all_tbl_service_time_slots();
        
        $data['_view'] = 'tbl_service_time_slot/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_service_time_slot
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
				'day' => $this->input->post('day'),
				'start_time' => $this->input->post('start_time'),
				'end_time' => $this->input->post('end_time'),
            );
            
            $tbl_service_time_slot_id = $this->Tbl_service_time_slot_model->add_tbl_service_time_slot($params);
            redirect('tbl_service_time_slot/index');
        }
        else
        {            
            $data['_view'] = 'tbl_service_time_slot/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_service_time_slot
     */
    function edit($time_slot_id)
    {   
        // check if the tbl_service_time_slot exists before trying to edit it
        $data['tbl_service_time_slot'] = $this->Tbl_service_time_slot_model->get_tbl_service_time_slot($time_slot_id);
        
        if(isset($data['tbl_service_time_slot']['time_slot_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_service_menu_id' => $this->input->post('fk_service_menu_id'),
					'day' => $this->input->post('day'),
					'start_time' => $this->input->post('start_time'),
					'end_time' => $this->input->post('end_time'),
                );

                $this->Tbl_service_time_slot_model->update_tbl_service_time_slot($time_slot_id,$params);            
                redirect('tbl_service_time_slot/index');
            }
            else
            {
                $data['_view'] = 'tbl_service_time_slot/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_service_time_slot you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_service_time_slot
     */
    function remove($time_slot_id)
    {
        $tbl_service_time_slot = $this->Tbl_service_time_slot_model->get_tbl_service_time_slot($time_slot_id);

        // check if the tbl_service_time_slot exists before trying to delete it
        if(isset($tbl_service_time_slot['time_slot_id']))
        {
            $this->Tbl_service_time_slot_model->delete_tbl_service_time_slot($time_slot_id);
            redirect('tbl_service_time_slot/index');
        }
        else
            show_error('The tbl_service_time_slot you are trying to delete does not exist.');
    }
    
}
