<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_service_package extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_service_package_model');
    } 

    /*
     * Listing of tbl_service_packages
     */
    function index()
    {
        $data['tbl_service_packages'] = $this->Tbl_service_package_model->get_all_tbl_service_packages();
        
        $data['_view'] = 'tbl_service_package/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_service_package
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fk_business_id' => $this->input->post('fk_business_id'),
				'fk_subcat_id' => $this->input->post('fk_subcat_id'),
				'package_name' => $this->input->post('package_name'),
				'no_of_appointments' => $this->input->post('no_of_appointments'),
				'expires' => $this->input->post('expires'),
				'package_details' => $this->input->post('package_details'),
				'package_price' => $this->input->post('package_price'),
				'can_be_used_for' => $this->input->post('can_be_used_for'),
            );
            
            $tbl_service_package_id = $this->Tbl_service_package_model->add_tbl_service_package($params);
            redirect('tbl_service_package/index');
        }
        else
        {            
            $data['_view'] = 'tbl_service_package/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_service_package
     */
    function edit($package_id)
    {   
        // check if the tbl_service_package exists before trying to edit it
        $data['tbl_service_package'] = $this->Tbl_service_package_model->get_tbl_service_package($package_id);
        
        if(isset($data['tbl_service_package']['package_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fk_business_id' => $this->input->post('fk_business_id'),
					'fk_subcat_id' => $this->input->post('fk_subcat_id'),
					'package_name' => $this->input->post('package_name'),
					'no_of_appointments' => $this->input->post('no_of_appointments'),
					'expires' => $this->input->post('expires'),
					'package_details' => $this->input->post('package_details'),
					'package_price' => $this->input->post('package_price'),
					'can_be_used_for' => $this->input->post('can_be_used_for'),
                );

                $this->Tbl_service_package_model->update_tbl_service_package($package_id,$params);            
                redirect('tbl_service_package/index');
            }
            else
            {
                $data['_view'] = 'tbl_service_package/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_service_package you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_service_package
     */
    function remove($package_id)
    {
        $tbl_service_package = $this->Tbl_service_package_model->get_tbl_service_package($package_id);

        // check if the tbl_service_package exists before trying to delete it
        if(isset($tbl_service_package['package_id']))
        {
            $this->Tbl_service_package_model->delete_tbl_service_package($package_id);
            redirect('tbl_service_package/index');
        }
        else
            show_error('The tbl_service_package you are trying to delete does not exist.');
    }
    
}
