<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_temp_appointment extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_temp_appointment_model');
    } 

    /*
     * Listing of tbl_temp_appointment
     */
    function index()
    {
        $data['tbl_temp_appointment'] = $this->Tbl_temp_appointment_model->get_all_tbl_temp_appointment();
        
        $data['_view'] = 'tbl_temp_appointment/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_temp_appointment
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'unique_userid' => $this->input->post('unique_userid'),
				'login_userid' => $this->input->post('login_userid'),
				'business_id' => $this->input->post('business_id'),
				'service_menu_id' => $this->input->post('service_menu_id'),
				'tattoo_id' => $this->input->post('tattoo_id'),
				'category_id' => $this->input->post('category_id'),
				'sub_cat_id' => $this->input->post('sub_cat_id'),
				'style_id' => $this->input->post('style_id'),
				'color_id' => $this->input->post('color_id'),
				'size_id' => $this->input->post('size_id'),
				'size' => $this->input->post('size'),
				'staff_id' => $this->input->post('staff_id'),
				'availibility_id' => $this->input->post('availibility_id'),
				'cover_up' => $this->input->post('cover_up'),
				'previous_tattoo_img' => $this->input->post('previous_tattoo_img'),
				'reference_tattoo' => $this->input->post('reference_tattoo'),
				'appointment_date' => $this->input->post('appointment_date'),
				'charges' => $this->input->post('charges'),
				'esitmated_amount' => $this->input->post('esitmated_amount'),
				'amount_to_be_pay_online' => $this->input->post('amount_to_be_pay_online'),
				'start_time' => $this->input->post('start_time'),
				'end_time' => $this->input->post('end_time'),
				'location' => $this->input->post('location'),
				'duration' => $this->input->post('duration'),
				'booking_desc' => $this->input->post('booking_desc'),
				'medical_condition' => $this->input->post('medical_condition'),
				'sub_category' => $this->input->post('sub_category'),
				'medical_description' => $this->input->post('medical_description'),
            );
            
            $tbl_temp_appointment_id = $this->Tbl_temp_appointment_model->add_tbl_temp_appointment($params);
            redirect('tbl_temp_appointment/index');
        }
        else
        {            
            $data['_view'] = 'tbl_temp_appointment/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_temp_appointment
     */
    function edit($id)
    {   
        // check if the tbl_temp_appointment exists before trying to edit it
        $data['tbl_temp_appointment'] = $this->Tbl_temp_appointment_model->get_tbl_temp_appointment($id);
        
        if(isset($data['tbl_temp_appointment']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'unique_userid' => $this->input->post('unique_userid'),
					'login_userid' => $this->input->post('login_userid'),
					'business_id' => $this->input->post('business_id'),
					'service_menu_id' => $this->input->post('service_menu_id'),
					'tattoo_id' => $this->input->post('tattoo_id'),
					'category_id' => $this->input->post('category_id'),
					'sub_cat_id' => $this->input->post('sub_cat_id'),
					'style_id' => $this->input->post('style_id'),
					'color_id' => $this->input->post('color_id'),
					'size_id' => $this->input->post('size_id'),
					'size' => $this->input->post('size'),
					'staff_id' => $this->input->post('staff_id'),
					'availibility_id' => $this->input->post('availibility_id'),
					'cover_up' => $this->input->post('cover_up'),
					'previous_tattoo_img' => $this->input->post('previous_tattoo_img'),
					'reference_tattoo' => $this->input->post('reference_tattoo'),
					'appointment_date' => $this->input->post('appointment_date'),
					'charges' => $this->input->post('charges'),
					'esitmated_amount' => $this->input->post('esitmated_amount'),
					'amount_to_be_pay_online' => $this->input->post('amount_to_be_pay_online'),
					'start_time' => $this->input->post('start_time'),
					'end_time' => $this->input->post('end_time'),
					'location' => $this->input->post('location'),
					'duration' => $this->input->post('duration'),
					'booking_desc' => $this->input->post('booking_desc'),
					'medical_condition' => $this->input->post('medical_condition'),
					'sub_category' => $this->input->post('sub_category'),
					'medical_description' => $this->input->post('medical_description'),
                );

                $this->Tbl_temp_appointment_model->update_tbl_temp_appointment($id,$params);            
                redirect('tbl_temp_appointment/index');
            }
            else
            {
                $data['_view'] = 'tbl_temp_appointment/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_temp_appointment you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_temp_appointment
     */
    function remove($id)
    {
        $tbl_temp_appointment = $this->Tbl_temp_appointment_model->get_tbl_temp_appointment($id);

        // check if the tbl_temp_appointment exists before trying to delete it
        if(isset($tbl_temp_appointment['id']))
        {
            $this->Tbl_temp_appointment_model->delete_tbl_temp_appointment($id);
            redirect('tbl_temp_appointment/index');
        }
        else
            show_error('The tbl_temp_appointment you are trying to delete does not exist.');
    }
    
}
