<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_category extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_category_model');
    } 

    /*
     * Listing of tbl_category
     */
    function index()
    {
        $data['tbl_category'] = $this->Tbl_category_model->get_all_tbl_category();
        
        $data['_view'] = 'tbl_category/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_category
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'category_name' => $this->input->post('category_name'),
				'category_slug' => $this->input->post('category_slug'),
				'tattoo_commission' => $this->input->post('tattoo_commission'),
				'custom_tattoo_commission' => $this->input->post('custom_tattoo_commission'),
				'deposit_amount' => $this->input->post('deposit_amount'),
				'cat_logo' => $this->input->post('cat_logo'),
				'category_status' => $this->input->post('category_status'),
				'is_delete' => $this->input->post('is_delete'),
            );
            
            $tbl_category_id = $this->Tbl_category_model->add_tbl_category($params);
            redirect('tbl_category/index');
        }
        else
        {            
            $data['_view'] = 'tbl_category/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_category
     */
    function edit($category_id)
    {   
        // check if the tbl_category exists before trying to edit it
        $data['tbl_category'] = $this->Tbl_category_model->get_tbl_category($category_id);
        
        if(isset($data['tbl_category']['category_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'category_name' => $this->input->post('category_name'),
					'category_slug' => $this->input->post('category_slug'),
					'tattoo_commission' => $this->input->post('tattoo_commission'),
					'custom_tattoo_commission' => $this->input->post('custom_tattoo_commission'),
					'deposit_amount' => $this->input->post('deposit_amount'),
					'cat_logo' => $this->input->post('cat_logo'),
					'category_status' => $this->input->post('category_status'),
					'is_delete' => $this->input->post('is_delete'),
                );

                $this->Tbl_category_model->update_tbl_category($category_id,$params);            
                redirect('tbl_category/index');
            }
            else
            {
                $data['_view'] = 'tbl_category/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_category you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_category
     */
    function remove($category_id)
    {
        $tbl_category = $this->Tbl_category_model->get_tbl_category($category_id);

        // check if the tbl_category exists before trying to delete it
        if(isset($tbl_category['category_id']))
        {
            $this->Tbl_category_model->delete_tbl_category($category_id);
            redirect('tbl_category/index');
        }
        else
            show_error('The tbl_category you are trying to delete does not exist.');
    }
    
}
