<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_dynamic_page extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_dynamic_page_model');
    } 

    /*
     * Listing of tbl_dynamic_pages
     */
    function index()
    {
        $data['tbl_dynamic_pages'] = $this->Tbl_dynamic_page_model->get_all_tbl_dynamic_pages();
        
        $data['_view'] = 'tbl_dynamic_page/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_dynamic_page
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'page_name' => $this->input->post('page_name'),
				'slug' => $this->input->post('slug'),
				'page_title' => $this->input->post('page_title'),
				'front_status' => $this->input->post('front_status'),
				'meta_title' => $this->input->post('meta_title'),
				'page_description' => $this->input->post('page_description'),
				'meta_keyword' => $this->input->post('meta_keyword'),
				'meta_description' => $this->input->post('meta_description'),
            );
            
            $tbl_dynamic_page_id = $this->Tbl_dynamic_page_model->add_tbl_dynamic_page($params);
            redirect('tbl_dynamic_page/index');
        }
        else
        {            
            $data['_view'] = 'tbl_dynamic_page/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_dynamic_page
     */
    function edit($page_id)
    {   
        // check if the tbl_dynamic_page exists before trying to edit it
        $data['tbl_dynamic_page'] = $this->Tbl_dynamic_page_model->get_tbl_dynamic_page($page_id);
        
        if(isset($data['tbl_dynamic_page']['page_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'page_name' => $this->input->post('page_name'),
					'slug' => $this->input->post('slug'),
					'page_title' => $this->input->post('page_title'),
					'front_status' => $this->input->post('front_status'),
					'meta_title' => $this->input->post('meta_title'),
					'page_description' => $this->input->post('page_description'),
					'meta_keyword' => $this->input->post('meta_keyword'),
					'meta_description' => $this->input->post('meta_description'),
                );

                $this->Tbl_dynamic_page_model->update_tbl_dynamic_page($page_id,$params);            
                redirect('tbl_dynamic_page/index');
            }
            else
            {
                $data['_view'] = 'tbl_dynamic_page/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_dynamic_page you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_dynamic_page
     */
    function remove($page_id)
    {
        $tbl_dynamic_page = $this->Tbl_dynamic_page_model->get_tbl_dynamic_page($page_id);

        // check if the tbl_dynamic_page exists before trying to delete it
        if(isset($tbl_dynamic_page['page_id']))
        {
            $this->Tbl_dynamic_page_model->delete_tbl_dynamic_page($page_id);
            redirect('tbl_dynamic_page/index');
        }
        else
            show_error('The tbl_dynamic_page you are trying to delete does not exist.');
    }
    
}
