<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_payment extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_payment_model');
    } 

    /*
     * Listing of tbl_payment
     */
    function index()
    {
        $data['tbl_payment'] = $this->Tbl_payment_model->get_all_tbl_payment();
        
        $data['_view'] = 'tbl_payment/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_payment
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'card_no' => $this->input->post('card_no'),
				'card_cvc' => $this->input->post('card_cvc'),
				'card_exp_month' => $this->input->post('card_exp_month'),
				'card_exp_year' => $this->input->post('card_exp_year'),
				'paid_amount' => $this->input->post('paid_amount'),
				'txn_id' => $this->input->post('txn_id'),
				'balance_transaction' => $this->input->post('balance_transaction'),
				'payment_date' => $this->input->post('payment_date'),
				'stripeResponse' => $this->input->post('stripeResponse'),
            );
            
            $tbl_payment_id = $this->Tbl_payment_model->add_tbl_payment($params);
            redirect('tbl_payment/index');
        }
        else
        {            
            $data['_view'] = 'tbl_payment/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_payment
     */
    function edit($id)
    {   
        // check if the tbl_payment exists before trying to edit it
        $data['tbl_payment'] = $this->Tbl_payment_model->get_tbl_payment($id);
        
        if(isset($data['tbl_payment']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'card_no' => $this->input->post('card_no'),
					'card_cvc' => $this->input->post('card_cvc'),
					'card_exp_month' => $this->input->post('card_exp_month'),
					'card_exp_year' => $this->input->post('card_exp_year'),
					'paid_amount' => $this->input->post('paid_amount'),
					'txn_id' => $this->input->post('txn_id'),
					'balance_transaction' => $this->input->post('balance_transaction'),
					'payment_date' => $this->input->post('payment_date'),
					'stripeResponse' => $this->input->post('stripeResponse'),
                );

                $this->Tbl_payment_model->update_tbl_payment($id,$params);            
                redirect('tbl_payment/index');
            }
            else
            {
                $data['_view'] = 'tbl_payment/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_payment you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_payment
     */
    function remove($id)
    {
        $tbl_payment = $this->Tbl_payment_model->get_tbl_payment($id);

        // check if the tbl_payment exists before trying to delete it
        if(isset($tbl_payment['id']))
        {
            $this->Tbl_payment_model->delete_tbl_payment($id);
            redirect('tbl_payment/index');
        }
        else
            show_error('The tbl_payment you are trying to delete does not exist.');
    }
    
}
