<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_notification extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_notification_model');
    } 

    /*
     * Listing of tbl_notifications
     */
    function index()
    {
        $data['tbl_notifications'] = $this->Tbl_notification_model->get_all_tbl_notifications();
        
        $data['_view'] = 'tbl_notification/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_notification
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'sender_id' => $this->input->post('sender_id'),
				'receiver_id' => $this->input->post('receiver_id'),
				'to_staff_id' => $this->input->post('to_staff_id'),
				'notification' => $this->input->post('notification'),
				'booking_type' => $this->input->post('booking_type'),
				'walkin_id' => $this->input->post('walkin_id'),
				'links' => $this->input->post('links'),
				'is_read' => $this->input->post('is_read'),
				'admin_read' => $this->input->post('admin_read'),
				'date' => $this->input->post('date'),
            );
            
            $tbl_notification_id = $this->Tbl_notification_model->add_tbl_notification($params);
            redirect('tbl_notification/index');
        }
        else
        {            
            $data['_view'] = 'tbl_notification/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_notification
     */
    function edit($notification_id)
    {   
        // check if the tbl_notification exists before trying to edit it
        $data['tbl_notification'] = $this->Tbl_notification_model->get_tbl_notification($notification_id);
        
        if(isset($data['tbl_notification']['notification_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'sender_id' => $this->input->post('sender_id'),
					'receiver_id' => $this->input->post('receiver_id'),
					'to_staff_id' => $this->input->post('to_staff_id'),
					'notification' => $this->input->post('notification'),
					'booking_type' => $this->input->post('booking_type'),
					'walkin_id' => $this->input->post('walkin_id'),
					'links' => $this->input->post('links'),
					'is_read' => $this->input->post('is_read'),
					'admin_read' => $this->input->post('admin_read'),
					'date' => $this->input->post('date'),
                );

                $this->Tbl_notification_model->update_tbl_notification($notification_id,$params);            
                redirect('tbl_notification/index');
            }
            else
            {
                $data['_view'] = 'tbl_notification/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_notification you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_notification
     */
    function remove($notification_id)
    {
        $tbl_notification = $this->Tbl_notification_model->get_tbl_notification($notification_id);

        // check if the tbl_notification exists before trying to delete it
        if(isset($tbl_notification['notification_id']))
        {
            $this->Tbl_notification_model->delete_tbl_notification($notification_id);
            redirect('tbl_notification/index');
        }
        else
            show_error('The tbl_notification you are trying to delete does not exist.');
    }
    
}
