<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_myplan_master extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_myplan_master_model');
    } 

    /*
     * Listing of tbl_myplan_master
     */
    function index()
    {
        $data['tbl_myplan_master'] = $this->Tbl_myplan_master_model->get_all_tbl_myplan_master();
        
        $data['_view'] = 'tbl_myplan_master/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_myplan_master
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'bussiness_id' => $this->input->post('bussiness_id'),
				'plan_type' => $this->input->post('plan_type'),
				'amount' => $this->input->post('amount'),
				'plan_duration' => $this->input->post('plan_duration'),
				'myplan_card_token' => $this->input->post('myplan_card_token'),
				'transaction_ref_token' => $this->input->post('transaction_ref_token'),
				'transaction_date_time' => $this->input->post('transaction_date_time'),
				'transaction_end_date' => $this->input->post('transaction_end_date'),
				'transaction_correlation_id' => $this->input->post('transaction_correlation_id'),
				'status' => $this->input->post('status'),
				'is_paid' => $this->input->post('is_paid'),
            );
            
            $tbl_myplan_master_id = $this->Tbl_myplan_master_model->add_tbl_myplan_master($params);
            redirect('tbl_myplan_master/index');
        }
        else
        {            
            $data['_view'] = 'tbl_myplan_master/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_myplan_master
     */
    function edit($myplan_id)
    {   
        // check if the tbl_myplan_master exists before trying to edit it
        $data['tbl_myplan_master'] = $this->Tbl_myplan_master_model->get_tbl_myplan_master($myplan_id);
        
        if(isset($data['tbl_myplan_master']['myplan_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'bussiness_id' => $this->input->post('bussiness_id'),
					'plan_type' => $this->input->post('plan_type'),
					'amount' => $this->input->post('amount'),
					'plan_duration' => $this->input->post('plan_duration'),
					'myplan_card_token' => $this->input->post('myplan_card_token'),
					'transaction_ref_token' => $this->input->post('transaction_ref_token'),
					'transaction_date_time' => $this->input->post('transaction_date_time'),
					'transaction_end_date' => $this->input->post('transaction_end_date'),
					'transaction_correlation_id' => $this->input->post('transaction_correlation_id'),
					'status' => $this->input->post('status'),
					'is_paid' => $this->input->post('is_paid'),
                );

                $this->Tbl_myplan_master_model->update_tbl_myplan_master($myplan_id,$params);            
                redirect('tbl_myplan_master/index');
            }
            else
            {
                $data['_view'] = 'tbl_myplan_master/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_myplan_master you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_myplan_master
     */
    function remove($myplan_id)
    {
        $tbl_myplan_master = $this->Tbl_myplan_master_model->get_tbl_myplan_master($myplan_id);

        // check if the tbl_myplan_master exists before trying to delete it
        if(isset($tbl_myplan_master['myplan_id']))
        {
            $this->Tbl_myplan_master_model->delete_tbl_myplan_master($myplan_id);
            redirect('tbl_myplan_master/index');
        }
        else
            show_error('The tbl_myplan_master you are trying to delete does not exist.');
    }
    
}
