<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Notification_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get notification by notification_id
     */
    function get_notification($notification_id)
    {
        return $this->db->get_where('notification',array('notification_id'=>$notification_id))->row_array();
    }
        
    /*
     * Get all notification
     */
    function get_all_notification()
    {
        $this->db->order_by('notification_id', 'desc');
        return $this->db->get('notification')->result_array();
    }
        
    /*
     * function to add new notification
     */
    function add_notification($params)
    {
        $this->db->insert('notification',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update notification
     */
    function update_notification($notification_id,$params)
    {
        $this->db->where('notification_id',$notification_id);
        return $this->db->update('notification',$params);
    }
    
    /*
     * function to delete notification
     */
    function delete_notification($notification_id)
    {
        return $this->db->delete('notification',array('notification_id'=>$notification_id));
    }
}
