<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_home_page_content_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_home_page_content by id
     */
    function get_tbl_home_page_content($id)
    {
        return $this->db->get_where('tbl_home_page_content',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_home_page_content
     */
    function get_all_tbl_home_page_content()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_home_page_content')->result_array();
    }
        
    /*
     * function to add new tbl_home_page_content
     */
    function add_tbl_home_page_content($params)
    {
        $this->db->insert('tbl_home_page_content',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_home_page_content
     */
    function update_tbl_home_page_content($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_home_page_content',$params);
    }
    
    /*
     * function to delete tbl_home_page_content
     */
    function delete_tbl_home_page_content($id)
    {
        return $this->db->delete('tbl_home_page_content',array('id'=>$id));
    }
}
