<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_email_id_master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_email_id_master by id
     */
    function get_tbl_email_id_master($id)
    {
        return $this->db->get_where('tbl_email_id_master',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_email_id_master
     */
    function get_all_tbl_email_id_master()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_email_id_master')->result_array();
    }
        
    /*
     * function to add new tbl_email_id_master
     */
    function add_tbl_email_id_master($params)
    {
        $this->db->insert('tbl_email_id_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_email_id_master
     */
    function update_tbl_email_id_master($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_email_id_master',$params);
    }
    
    /*
     * function to delete tbl_email_id_master
     */
    function delete_tbl_email_id_master($id)
    {
        return $this->db->delete('tbl_email_id_master',array('id'=>$id));
    }
}
