<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_waiting_list_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_waiting_list by waiting_id
     */
    function get_tbl_waiting_list($waiting_id)
    {
        return $this->db->get_where('tbl_waiting_list',array('waiting_id'=>$waiting_id))->row_array();
    }
        
    /*
     * Get all tbl_waiting_list
     */
    function get_all_tbl_waiting_list()
    {
        $this->db->order_by('waiting_id', 'desc');
        return $this->db->get('tbl_waiting_list')->result_array();
    }
        
    /*
     * function to add new tbl_waiting_list
     */
    function add_tbl_waiting_list($params)
    {
        $this->db->insert('tbl_waiting_list',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_waiting_list
     */
    function update_tbl_waiting_list($waiting_id,$params)
    {
        $this->db->where('waiting_id',$waiting_id);
        return $this->db->update('tbl_waiting_list',$params);
    }
    
    /*
     * function to delete tbl_waiting_list
     */
    function delete_tbl_waiting_list($waiting_id)
    {
        return $this->db->delete('tbl_waiting_list',array('waiting_id'=>$waiting_id));
    }
}
