<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_news_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_news by news_id
     */
    function get_tbl_news($news_id)
    {
        return $this->db->get_where('tbl_news',array('news_id'=>$news_id))->row_array();
    }
        
    /*
     * Get all tbl_news
     */
    function get_all_tbl_news()
    {
        $this->db->order_by('news_id', 'desc');
        return $this->db->get('tbl_news')->result_array();
    }
        
    /*
     * function to add new tbl_news
     */
    function add_tbl_news($params)
    {
        $this->db->insert('tbl_news',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_news
     */
    function update_tbl_news($news_id,$params)
    {
        $this->db->where('news_id',$news_id);
        return $this->db->update('tbl_news',$params);
    }
    
    /*
     * function to delete tbl_news
     */
    function delete_tbl_news($news_id)
    {
        return $this->db->delete('tbl_news',array('news_id'=>$news_id));
    }
}
