<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_video_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_business_video by video_id
     */
    function get_tbl_business_video($video_id)
    {
        return $this->db->get_where('tbl_business_videos',array('video_id'=>$video_id))->row_array();
    }
        
    /*
     * Get all tbl_business_videos
     */
    function get_all_tbl_business_videos()
    {
        $this->db->order_by('video_id', 'desc');
        return $this->db->get('tbl_business_videos')->result_array();
    }
        
    /*
     * function to add new tbl_business_video
     */
    function add_tbl_business_video($params)
    {
        $this->db->insert('tbl_business_videos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_business_video
     */
    function update_tbl_business_video($video_id,$params)
    {
        $this->db->where('video_id',$video_id);
        return $this->db->update('tbl_business_videos',$params);
    }
    
    /*
     * function to delete tbl_business_video
     */
    function delete_tbl_business_video($video_id)
    {
        return $this->db->delete('tbl_business_videos',array('video_id'=>$video_id));
    }
}
