<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_labe_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_business_labe by 
     */
    function get_tbl_business_labe($)
    {
        return $this->db->get_where('tbl_business_labes',array(''=>$))->row_array();
    }
        
    /*
     * Get all tbl_business_labes
     */
    function get_all_tbl_business_labes()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('tbl_business_labes')->result_array();
    }
        
    /*
     * function to add new tbl_business_labe
     */
    function add_tbl_business_labe($params)
    {
        $this->db->insert('tbl_business_labes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_business_labe
     */
    function update_tbl_business_labe($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('tbl_business_labes',$params);
    }
    
    /*
     * function to delete tbl_business_labe
     */
    function delete_tbl_business_labe($)
    {
        return $this->db->delete('tbl_business_labes',array(''=>$));
    }
}
