<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_location_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_business_location by location_id
     */
    function get_tbl_business_location($location_id)
    {
        return $this->db->get_where('tbl_business_locations',array('location_id'=>$location_id))->row_array();
    }
        
    /*
     * Get all tbl_business_locations
     */
    function get_all_tbl_business_locations()
    {
        $this->db->order_by('location_id', 'desc');
        return $this->db->get('tbl_business_locations')->result_array();
    }
        
    /*
     * function to add new tbl_business_location
     */
    function add_tbl_business_location($params)
    {
        $this->db->insert('tbl_business_locations',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_business_location
     */
    function update_tbl_business_location($location_id,$params)
    {
        $this->db->where('location_id',$location_id);
        return $this->db->update('tbl_business_locations',$params);
    }
    
    /*
     * function to delete tbl_business_location
     */
    function delete_tbl_business_location($location_id)
    {
        return $this->db->delete('tbl_business_locations',array('location_id'=>$location_id));
    }
}
