<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_favorite_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_favorite by favorite_id
     */
    function get_tbl_favorite($favorite_id)
    {
        return $this->db->get_where('tbl_favorites',array('favorite_id'=>$favorite_id))->row_array();
    }
        
    /*
     * Get all tbl_favorites
     */
    function get_all_tbl_favorites()
    {
        $this->db->order_by('favorite_id', 'desc');
        return $this->db->get('tbl_favorites')->result_array();
    }
        
    /*
     * function to add new tbl_favorite
     */
    function add_tbl_favorite($params)
    {
        $this->db->insert('tbl_favorites',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_favorite
     */
    function update_tbl_favorite($favorite_id,$params)
    {
        $this->db->where('favorite_id',$favorite_id);
        return $this->db->update('tbl_favorites',$params);
    }
    
    /*
     * function to delete tbl_favorite
     */
    function delete_tbl_favorite($favorite_id)
    {
        return $this->db->delete('tbl_favorites',array('favorite_id'=>$favorite_id));
    }
}
