<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_setting_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_business_setting by settings_id
     */
    function get_tbl_business_setting($settings_id)
    {
        return $this->db->get_where('tbl_business_settings',array('settings_id'=>$settings_id))->row_array();
    }
        
    /*
     * Get all tbl_business_settings
     */
    function get_all_tbl_business_settings()
    {
        $this->db->order_by('settings_id', 'desc');
        return $this->db->get('tbl_business_settings')->result_array();
    }
        
    /*
     * function to add new tbl_business_setting
     */
    function add_tbl_business_setting($params)
    {
        $this->db->insert('tbl_business_settings',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_business_setting
     */
    function update_tbl_business_setting($settings_id,$params)
    {
        $this->db->where('settings_id',$settings_id);
        return $this->db->update('tbl_business_settings',$params);
    }
    
    /*
     * function to delete tbl_business_setting
     */
    function delete_tbl_business_setting($settings_id)
    {
        return $this->db->delete('tbl_business_settings',array('settings_id'=>$settings_id));
    }
}
