<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_services_menu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_services_menu by service_menu_id
     */
    function get_tbl_services_menu($service_menu_id)
    {
        return $this->db->get_where('tbl_services_menu',array('service_menu_id'=>$service_menu_id))->row_array();
    }
        
    /*
     * Get all tbl_services_menu
     */
    function get_all_tbl_services_menu()
    {
        $this->db->order_by('service_menu_id', 'desc');
        return $this->db->get('tbl_services_menu')->result_array();
    }
        
    /*
     * function to add new tbl_services_menu
     */
    function add_tbl_services_menu($params)
    {
        $this->db->insert('tbl_services_menu',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_services_menu
     */
    function update_tbl_services_menu($service_menu_id,$params)
    {
        $this->db->where('service_menu_id',$service_menu_id);
        return $this->db->update('tbl_services_menu',$params);
    }
    
    /*
     * function to delete tbl_services_menu
     */
    function delete_tbl_services_menu($service_menu_id)
    {
        return $this->db->delete('tbl_services_menu',array('service_menu_id'=>$service_menu_id));
    }
}
