<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_deposit_storage_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_deposit_storage by deposit_info_id
     */
    function get_tbl_deposit_storage($deposit_info_id)
    {
        return $this->db->get_where('tbl_deposit_storage',array('deposit_info_id'=>$deposit_info_id))->row_array();
    }
        
    /*
     * Get all tbl_deposit_storage
     */
    function get_all_tbl_deposit_storage()
    {
        $this->db->order_by('deposit_info_id', 'desc');
        return $this->db->get('tbl_deposit_storage')->result_array();
    }
        
    /*
     * function to add new tbl_deposit_storage
     */
    function add_tbl_deposit_storage($params)
    {
        $this->db->insert('tbl_deposit_storage',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_deposit_storage
     */
    function update_tbl_deposit_storage($deposit_info_id,$params)
    {
        $this->db->where('deposit_info_id',$deposit_info_id);
        return $this->db->update('tbl_deposit_storage',$params);
    }
    
    /*
     * function to delete tbl_deposit_storage
     */
    function delete_tbl_deposit_storage($deposit_info_id)
    {
        return $this->db->delete('tbl_deposit_storage',array('deposit_info_id'=>$deposit_info_id));
    }
}
