<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_campaign_template_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_campaign_template by template_id
     */
    function get_tbl_campaign_template($template_id)
    {
        return $this->db->get_where('tbl_campaign_templates',array('template_id'=>$template_id))->row_array();
    }
        
    /*
     * Get all tbl_campaign_templates
     */
    function get_all_tbl_campaign_templates()
    {
        $this->db->order_by('template_id', 'desc');
        return $this->db->get('tbl_campaign_templates')->result_array();
    }
        
    /*
     * function to add new tbl_campaign_template
     */
    function add_tbl_campaign_template($params)
    {
        $this->db->insert('tbl_campaign_templates',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_campaign_template
     */
    function update_tbl_campaign_template($template_id,$params)
    {
        $this->db->where('template_id',$template_id);
        return $this->db->update('tbl_campaign_templates',$params);
    }
    
    /*
     * function to delete tbl_campaign_template
     */
    function delete_tbl_campaign_template($template_id)
    {
        return $this->db->delete('tbl_campaign_templates',array('template_id'=>$template_id));
    }
}
