<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_cover_information_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_business_cover_information by 
     */
    function get_tbl_business_cover_information($)
    {
        return $this->db->get_where('tbl_business_cover_information',array(''=>$))->row_array();
    }
        
    /*
     * Get all tbl_business_cover_information
     */
    function get_all_tbl_business_cover_information()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('tbl_business_cover_information')->result_array();
    }
        
    /*
     * function to add new tbl_business_cover_information
     */
    function add_tbl_business_cover_information($params)
    {
        $this->db->insert('tbl_business_cover_information',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_business_cover_information
     */
    function update_tbl_business_cover_information($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('tbl_business_cover_information',$params);
    }
    
    /*
     * function to delete tbl_business_cover_information
     */
    function delete_tbl_business_cover_information($)
    {
        return $this->db->delete('tbl_business_cover_information',array(''=>$));
    }
}
