<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_communication_preference_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_communication_preference by communication_preferences_id
     */
    function get_tbl_communication_preference($communication_preferences_id)
    {
        return $this->db->get_where('tbl_communication_preferences',array('communication_preferences_id'=>$communication_preferences_id))->row_array();
    }
        
    /*
     * Get all tbl_communication_preferences
     */
    function get_all_tbl_communication_preferences()
    {
        $this->db->order_by('communication_preferences_id', 'desc');
        return $this->db->get('tbl_communication_preferences')->result_array();
    }
        
    /*
     * function to add new tbl_communication_preference
     */
    function add_tbl_communication_preference($params)
    {
        $this->db->insert('tbl_communication_preferences',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_communication_preference
     */
    function update_tbl_communication_preference($communication_preferences_id,$params)
    {
        $this->db->where('communication_preferences_id',$communication_preferences_id);
        return $this->db->update('tbl_communication_preferences',$params);
    }
    
    /*
     * function to delete tbl_communication_preference
     */
    function delete_tbl_communication_preference($communication_preferences_id)
    {
        return $this->db->delete('tbl_communication_preferences',array('communication_preferences_id'=>$communication_preferences_id));
    }
}
