<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_booking_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_booking by id
     */
    function get_tbl_booking($id)
    {
        return $this->db->get_where('tbl_booking',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_booking
     */
    function get_all_tbl_booking()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_booking')->result_array();
    }
        
    /*
     * function to add new tbl_booking
     */
    function add_tbl_booking($params)
    {
        $this->db->insert('tbl_booking',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_booking
     */
    function update_tbl_booking($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_booking',$params);
    }
    
    /*
     * function to delete tbl_booking
     */
    function delete_tbl_booking($id)
    {
        return $this->db->delete('tbl_booking',array('id'=>$id));
    }
}
