<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_myplan_master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_myplan_master by myplan_id
     */
    function get_tbl_myplan_master($myplan_id)
    {
        return $this->db->get_where('tbl_myplan_master',array('myplan_id'=>$myplan_id))->row_array();
    }
        
    /*
     * Get all tbl_myplan_master
     */
    function get_all_tbl_myplan_master()
    {
        $this->db->order_by('myplan_id', 'desc');
        return $this->db->get('tbl_myplan_master')->result_array();
    }
        
    /*
     * function to add new tbl_myplan_master
     */
    function add_tbl_myplan_master($params)
    {
        $this->db->insert('tbl_myplan_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_myplan_master
     */
    function update_tbl_myplan_master($myplan_id,$params)
    {
        $this->db->where('myplan_id',$myplan_id);
        return $this->db->update('tbl_myplan_master',$params);
    }
    
    /*
     * function to delete tbl_myplan_master
     */
    function delete_tbl_myplan_master($myplan_id)
    {
        return $this->db->delete('tbl_myplan_master',array('myplan_id'=>$myplan_id));
    }
}
