<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_user_master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_user_master by user_id
     */
    function get_tbl_user_master($user_id)
    {
        return $this->db->get_where('tbl_user_master',array('user_id'=>$user_id))->row_array();
    }
        
    /*
     * Get all tbl_user_master
     */
    function get_all_tbl_user_master()
    {
        $this->db->order_by('user_id', 'desc');
        return $this->db->get('tbl_user_master')->result_array();
    }
        
    /*
     * function to add new tbl_user_master
     */
    function add_tbl_user_master($params)
    {
        $this->db->insert('tbl_user_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_user_master
     */
    function update_tbl_user_master($user_id,$params)
    {
        $this->db->where('user_id',$user_id);
        return $this->db->update('tbl_user_master',$params);
    }
    
    /*
     * function to delete tbl_user_master
     */
    function delete_tbl_user_master($user_id)
    {
        return $this->db->delete('tbl_user_master',array('user_id'=>$user_id));
    }
}
