<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_client_label_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_client_label by label_id
     */
    function get_tbl_client_label($label_id)
    {
        return $this->db->get_where('tbl_client_label',array('label_id'=>$label_id))->row_array();
    }
        
    /*
     * Get all tbl_client_label
     */
    function get_all_tbl_client_label()
    {
        $this->db->order_by('label_id', 'desc');
        return $this->db->get('tbl_client_label')->result_array();
    }
        
    /*
     * function to add new tbl_client_label
     */
    function add_tbl_client_label($params)
    {
        $this->db->insert('tbl_client_label',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_client_label
     */
    function update_tbl_client_label($label_id,$params)
    {
        $this->db->where('label_id',$label_id);
        return $this->db->update('tbl_client_label',$params);
    }
    
    /*
     * function to delete tbl_client_label
     */
    function delete_tbl_client_label($label_id)
    {
        return $this->db->delete('tbl_client_label',array('label_id'=>$label_id));
    }
}
