<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_my_style_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_my_style by id
     */
    function get_tbl_my_style($id)
    {
        return $this->db->get_where('tbl_my_styles',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_my_styles
     */
    function get_all_tbl_my_styles()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_my_styles')->result_array();
    }
        
    /*
     * function to add new tbl_my_style
     */
    function add_tbl_my_style($params)
    {
        $this->db->insert('tbl_my_styles',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_my_style
     */
    function update_tbl_my_style($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_my_styles',$params);
    }
    
    /*
     * function to delete tbl_my_style
     */
    function delete_tbl_my_style($id)
    {
        return $this->db->delete('tbl_my_styles',array('id'=>$id));
    }
}
