<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_style_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_style by style_id
     */
    function get_tbl_style($style_id)
    {
        return $this->db->get_where('tbl_style',array('style_id'=>$style_id))->row_array();
    }
        
    /*
     * Get all tbl_style
     */
    function get_all_tbl_style()
    {
        $this->db->order_by('style_id', 'desc');
        return $this->db->get('tbl_style')->result_array();
    }
        
    /*
     * function to add new tbl_style
     */
    function add_tbl_style($params)
    {
        $this->db->insert('tbl_style',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_style
     */
    function update_tbl_style($style_id,$params)
    {
        $this->db->where('style_id',$style_id);
        return $this->db->update('tbl_style',$params);
    }
    
    /*
     * function to delete tbl_style
     */
    function delete_tbl_style($style_id)
    {
        return $this->db->delete('tbl_style',array('style_id'=>$style_id));
    }
}
