<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_review_rating_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_review_rating by id
     */
    function get_tbl_review_rating($id)
    {
        return $this->db->get_where('tbl_review_ratings',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_review_ratings
     */
    function get_all_tbl_review_ratings()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_review_ratings')->result_array();
    }
        
    /*
     * function to add new tbl_review_rating
     */
    function add_tbl_review_rating($params)
    {
        $this->db->insert('tbl_review_ratings',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_review_rating
     */
    function update_tbl_review_rating($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_review_ratings',$params);
    }
    
    /*
     * function to delete tbl_review_rating
     */
    function delete_tbl_review_rating($id)
    {
        return $this->db->delete('tbl_review_ratings',array('id'=>$id));
    }
}
