<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_site_setting_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_site_setting by id
     */
    function get_tbl_site_setting($id)
    {
        return $this->db->get_where('tbl_site_settings',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_site_settings
     */
    function get_all_tbl_site_settings()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_site_settings')->result_array();
    }
        
    /*
     * function to add new tbl_site_setting
     */
    function add_tbl_site_setting($params)
    {
        $this->db->insert('tbl_site_settings',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_site_setting
     */
    function update_tbl_site_setting($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_site_settings',$params);
    }
    
    /*
     * function to delete tbl_site_setting
     */
    function delete_tbl_site_setting($id)
    {
        return $this->db->delete('tbl_site_settings',array('id'=>$id));
    }
}
