<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_service_offpeak_time_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_service_offpeak_time by offpeak_time_id
     */
    function get_tbl_service_offpeak_time($offpeak_time_id)
    {
        return $this->db->get_where('tbl_service_offpeak_times',array('offpeak_time_id'=>$offpeak_time_id))->row_array();
    }
        
    /*
     * Get all tbl_service_offpeak_times
     */
    function get_all_tbl_service_offpeak_times()
    {
        $this->db->order_by('offpeak_time_id', 'desc');
        return $this->db->get('tbl_service_offpeak_times')->result_array();
    }
        
    /*
     * function to add new tbl_service_offpeak_time
     */
    function add_tbl_service_offpeak_time($params)
    {
        $this->db->insert('tbl_service_offpeak_times',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_service_offpeak_time
     */
    function update_tbl_service_offpeak_time($offpeak_time_id,$params)
    {
        $this->db->where('offpeak_time_id',$offpeak_time_id);
        return $this->db->update('tbl_service_offpeak_times',$params);
    }
    
    /*
     * function to delete tbl_service_offpeak_time
     */
    function delete_tbl_service_offpeak_time($offpeak_time_id)
    {
        return $this->db->delete('tbl_service_offpeak_times',array('offpeak_time_id'=>$offpeak_time_id));
    }
}
