<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_service_time_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_service_time by time_id
     */
    function get_tbl_service_time($time_id)
    {
        return $this->db->get_where('tbl_service_time',array('time_id'=>$time_id))->row_array();
    }
        
    /*
     * Get all tbl_service_time
     */
    function get_all_tbl_service_time()
    {
        $this->db->order_by('time_id', 'desc');
        return $this->db->get('tbl_service_time')->result_array();
    }
        
    /*
     * function to add new tbl_service_time
     */
    function add_tbl_service_time($params)
    {
        $this->db->insert('tbl_service_time',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_service_time
     */
    function update_tbl_service_time($time_id,$params)
    {
        $this->db->where('time_id',$time_id);
        return $this->db->update('tbl_service_time',$params);
    }
    
    /*
     * function to delete tbl_service_time
     */
    function delete_tbl_service_time($time_id)
    {
        return $this->db->delete('tbl_service_time',array('time_id'=>$time_id));
    }
}
