<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_faq_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_faq_category by faq_category_id
     */
    function get_tbl_faq_category($faq_category_id)
    {
        return $this->db->get_where('tbl_faq_categories',array('faq_category_id'=>$faq_category_id))->row_array();
    }
        
    /*
     * Get all tbl_faq_categories
     */
    function get_all_tbl_faq_categories()
    {
        $this->db->order_by('faq_category_id', 'desc');
        return $this->db->get('tbl_faq_categories')->result_array();
    }
        
    /*
     * function to add new tbl_faq_category
     */
    function add_tbl_faq_category($params)
    {
        $this->db->insert('tbl_faq_categories',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_faq_category
     */
    function update_tbl_faq_category($faq_category_id,$params)
    {
        $this->db->where('faq_category_id',$faq_category_id);
        return $this->db->update('tbl_faq_categories',$params);
    }
    
    /*
     * function to delete tbl_faq_category
     */
    function delete_tbl_faq_category($faq_category_id)
    {
        return $this->db->delete('tbl_faq_categories',array('faq_category_id'=>$faq_category_id));
    }
}
