<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_staff_block_off_time_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_staff_block_off_time by block_off_id
     */
    function get_tbl_staff_block_off_time($block_off_id)
    {
        return $this->db->get_where('tbl_staff_block_off_time',array('block_off_id'=>$block_off_id))->row_array();
    }
        
    /*
     * Get all tbl_staff_block_off_time
     */
    function get_all_tbl_staff_block_off_time()
    {
        $this->db->order_by('block_off_id', 'desc');
        return $this->db->get('tbl_staff_block_off_time')->result_array();
    }
        
    /*
     * function to add new tbl_staff_block_off_time
     */
    function add_tbl_staff_block_off_time($params)
    {
        $this->db->insert('tbl_staff_block_off_time',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_staff_block_off_time
     */
    function update_tbl_staff_block_off_time($block_off_id,$params)
    {
        $this->db->where('block_off_id',$block_off_id);
        return $this->db->update('tbl_staff_block_off_time',$params);
    }
    
    /*
     * function to delete tbl_staff_block_off_time
     */
    function delete_tbl_staff_block_off_time($block_off_id)
    {
        return $this->db->delete('tbl_staff_block_off_time',array('block_off_id'=>$block_off_id));
    }
}
