<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_team_member_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_team_member by member_id
     */
    function get_tbl_team_member($member_id)
    {
        return $this->db->get_where('tbl_team_members',array('member_id'=>$member_id))->row_array();
    }
        
    /*
     * Get all tbl_team_members
     */
    function get_all_tbl_team_members()
    {
        $this->db->order_by('member_id', 'desc');
        return $this->db->get('tbl_team_members')->result_array();
    }
        
    /*
     * function to add new tbl_team_member
     */
    function add_tbl_team_member($params)
    {
        $this->db->insert('tbl_team_members',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_team_member
     */
    function update_tbl_team_member($member_id,$params)
    {
        $this->db->where('member_id',$member_id);
        return $this->db->update('tbl_team_members',$params);
    }
    
    /*
     * function to delete tbl_team_member
     */
    function delete_tbl_team_member($member_id)
    {
        return $this->db->delete('tbl_team_members',array('member_id'=>$member_id));
    }
}
