<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_service_pakage_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_service_pakage by ser_pk_id
     */
    function get_tbl_service_pakage($ser_pk_id)
    {
        return $this->db->get_where('tbl_service_pakages',array('ser_pk_id'=>$ser_pk_id))->row_array();
    }
        
    /*
     * Get all tbl_service_pakages
     */
    function get_all_tbl_service_pakages()
    {
        $this->db->order_by('ser_pk_id', 'desc');
        return $this->db->get('tbl_service_pakages')->result_array();
    }
        
    /*
     * function to add new tbl_service_pakage
     */
    function add_tbl_service_pakage($params)
    {
        $this->db->insert('tbl_service_pakages',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_service_pakage
     */
    function update_tbl_service_pakage($ser_pk_id,$params)
    {
        $this->db->where('ser_pk_id',$ser_pk_id);
        return $this->db->update('tbl_service_pakages',$params);
    }
    
    /*
     * function to delete tbl_service_pakage
     */
    function delete_tbl_service_pakage($ser_pk_id)
    {
        return $this->db->delete('tbl_service_pakages',array('ser_pk_id'=>$ser_pk_id));
    }
}
