<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_color_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_color by color_id
     */
    function get_tbl_color($color_id)
    {
        return $this->db->get_where('tbl_color',array('color_id'=>$color_id))->row_array();
    }
        
    /*
     * Get all tbl_color
     */
    function get_all_tbl_color()
    {
        $this->db->order_by('color_id', 'desc');
        return $this->db->get('tbl_color')->result_array();
    }
        
    /*
     * function to add new tbl_color
     */
    function add_tbl_color($params)
    {
        $this->db->insert('tbl_color',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_color
     */
    function update_tbl_color($color_id,$params)
    {
        $this->db->where('color_id',$color_id);
        return $this->db->update('tbl_color',$params);
    }
    
    /*
     * function to delete tbl_color
     */
    function delete_tbl_color($color_id)
    {
        return $this->db->delete('tbl_color',array('color_id'=>$color_id));
    }
}
