<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_location_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_location by id
     */
    function get_tbl_location($id)
    {
        return $this->db->get_where('tbl_location',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_location
     */
    function get_all_tbl_location()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_location')->result_array();
    }
        
    /*
     * function to add new tbl_location
     */
    function add_tbl_location($params)
    {
        $this->db->insert('tbl_location',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_location
     */
    function update_tbl_location($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_location',$params);
    }
    
    /*
     * function to delete tbl_location
     */
    function delete_tbl_location($id)
    {
        return $this->db->delete('tbl_location',array('id'=>$id));
    }
}
