<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_admin_stripe_detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_admin_stripe_detail by stripe_id
     */
    function get_tbl_admin_stripe_detail($stripe_id)
    {
        return $this->db->get_where('tbl_admin_stripe_details',array('stripe_id'=>$stripe_id))->row_array();
    }
        
    /*
     * Get all tbl_admin_stripe_details
     */
    function get_all_tbl_admin_stripe_details()
    {
        $this->db->order_by('stripe_id', 'desc');
        return $this->db->get('tbl_admin_stripe_details')->result_array();
    }
        
    /*
     * function to add new tbl_admin_stripe_detail
     */
    function add_tbl_admin_stripe_detail($params)
    {
        $this->db->insert('tbl_admin_stripe_details',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_admin_stripe_detail
     */
    function update_tbl_admin_stripe_detail($stripe_id,$params)
    {
        $this->db->where('stripe_id',$stripe_id);
        return $this->db->update('tbl_admin_stripe_details',$params);
    }
    
    /*
     * function to delete tbl_admin_stripe_detail
     */
    function delete_tbl_admin_stripe_detail($stripe_id)
    {
        return $this->db->delete('tbl_admin_stripe_details',array('stripe_id'=>$stripe_id));
    }
}
