<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_newsletter_subscriber_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_newsletter_subscriber by sub_id
     */
    function get_tbl_newsletter_subscriber($sub_id)
    {
        return $this->db->get_where('tbl_newsletter_subscriber',array('sub_id'=>$sub_id))->row_array();
    }
        
    /*
     * Get all tbl_newsletter_subscriber
     */
    function get_all_tbl_newsletter_subscriber()
    {
        $this->db->order_by('sub_id', 'desc');
        return $this->db->get('tbl_newsletter_subscriber')->result_array();
    }
        
    /*
     * function to add new tbl_newsletter_subscriber
     */
    function add_tbl_newsletter_subscriber($params)
    {
        $this->db->insert('tbl_newsletter_subscriber',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_newsletter_subscriber
     */
    function update_tbl_newsletter_subscriber($sub_id,$params)
    {
        $this->db->where('sub_id',$sub_id);
        return $this->db->update('tbl_newsletter_subscriber',$params);
    }
    
    /*
     * function to delete tbl_newsletter_subscriber
     */
    function delete_tbl_newsletter_subscriber($sub_id)
    {
        return $this->db->delete('tbl_newsletter_subscriber',array('sub_id'=>$sub_id));
    }
}
