<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_service_package_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_service_package by package_id
     */
    function get_tbl_service_package($package_id)
    {
        return $this->db->get_where('tbl_service_packages',array('package_id'=>$package_id))->row_array();
    }
        
    /*
     * Get all tbl_service_packages
     */
    function get_all_tbl_service_packages()
    {
        $this->db->order_by('package_id', 'desc');
        return $this->db->get('tbl_service_packages')->result_array();
    }
        
    /*
     * function to add new tbl_service_package
     */
    function add_tbl_service_package($params)
    {
        $this->db->insert('tbl_service_packages',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_service_package
     */
    function update_tbl_service_package($package_id,$params)
    {
        $this->db->where('package_id',$package_id);
        return $this->db->update('tbl_service_packages',$params);
    }
    
    /*
     * function to delete tbl_service_package
     */
    function delete_tbl_service_package($package_id)
    {
        return $this->db->delete('tbl_service_packages',array('package_id'=>$package_id));
    }
}
