<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_campaign_default_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_campaign_default by campaign_id
     */
    function get_tbl_campaign_default($campaign_id)
    {
        return $this->db->get_where('tbl_campaign_default',array('campaign_id'=>$campaign_id))->row_array();
    }
        
    /*
     * Get all tbl_campaign_default
     */
    function get_all_tbl_campaign_default()
    {
        $this->db->order_by('campaign_id', 'desc');
        return $this->db->get('tbl_campaign_default')->result_array();
    }
        
    /*
     * function to add new tbl_campaign_default
     */
    function add_tbl_campaign_default($params)
    {
        $this->db->insert('tbl_campaign_default',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_campaign_default
     */
    function update_tbl_campaign_default($campaign_id,$params)
    {
        $this->db->where('campaign_id',$campaign_id);
        return $this->db->update('tbl_campaign_default',$params);
    }
    
    /*
     * function to delete tbl_campaign_default
     */
    function delete_tbl_campaign_default($campaign_id)
    {
        return $this->db->delete('tbl_campaign_default',array('campaign_id'=>$campaign_id));
    }
}
