<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_photo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_business_photo by photo_id
     */
    function get_tbl_business_photo($photo_id)
    {
        return $this->db->get_where('tbl_business_photos',array('photo_id'=>$photo_id))->row_array();
    }
        
    /*
     * Get all tbl_business_photos
     */
    function get_all_tbl_business_photos()
    {
        $this->db->order_by('photo_id', 'desc');
        return $this->db->get('tbl_business_photos')->result_array();
    }
        
    /*
     * function to add new tbl_business_photo
     */
    function add_tbl_business_photo($params)
    {
        $this->db->insert('tbl_business_photos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_business_photo
     */
    function update_tbl_business_photo($photo_id,$params)
    {
        $this->db->where('photo_id',$photo_id);
        return $this->db->update('tbl_business_photos',$params);
    }
    
    /*
     * function to delete tbl_business_photo
     */
    function delete_tbl_business_photo($photo_id)
    {
        return $this->db->delete('tbl_business_photos',array('photo_id'=>$photo_id));
    }
}
