<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_card_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_card_type by id
     */
    function get_tbl_card_type($id)
    {
        return $this->db->get_where('tbl_card_type',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_card_type
     */
    function get_all_tbl_card_type()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_card_type')->result_array();
    }
        
    /*
     * function to add new tbl_card_type
     */
    function add_tbl_card_type($params)
    {
        $this->db->insert('tbl_card_type',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_card_type
     */
    function update_tbl_card_type($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_card_type',$params);
    }
    
    /*
     * function to delete tbl_card_type
     */
    function delete_tbl_card_type($id)
    {
        return $this->db->delete('tbl_card_type',array('id'=>$id));
    }
}
