<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_notification_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_notification by notification_id
     */
    function get_tbl_notification($notification_id)
    {
        return $this->db->get_where('tbl_notifications',array('notification_id'=>$notification_id))->row_array();
    }
        
    /*
     * Get all tbl_notifications
     */
    function get_all_tbl_notifications()
    {
        $this->db->order_by('notification_id', 'desc');
        return $this->db->get('tbl_notifications')->result_array();
    }
        
    /*
     * function to add new tbl_notification
     */
    function add_tbl_notification($params)
    {
        $this->db->insert('tbl_notifications',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_notification
     */
    function update_tbl_notification($notification_id,$params)
    {
        $this->db->where('notification_id',$notification_id);
        return $this->db->update('tbl_notifications',$params);
    }
    
    /*
     * function to delete tbl_notification
     */
    function delete_tbl_notification($notification_id)
    {
        return $this->db->delete('tbl_notifications',array('notification_id'=>$notification_id));
    }
}
