<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_testimonial_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_testimonial by testimony_id
     */
    function get_tbl_testimonial($testimony_id)
    {
        return $this->db->get_where('tbl_testimonials',array('testimony_id'=>$testimony_id))->row_array();
    }
        
    /*
     * Get all tbl_testimonials
     */
    function get_all_tbl_testimonials()
    {
        $this->db->order_by('testimony_id', 'desc');
        return $this->db->get('tbl_testimonials')->result_array();
    }
        
    /*
     * function to add new tbl_testimonial
     */
    function add_tbl_testimonial($params)
    {
        $this->db->insert('tbl_testimonials',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_testimonial
     */
    function update_tbl_testimonial($testimony_id,$params)
    {
        $this->db->where('testimony_id',$testimony_id);
        return $this->db->update('tbl_testimonials',$params);
    }
    
    /*
     * function to delete tbl_testimonial
     */
    function delete_tbl_testimonial($testimony_id)
    {
        return $this->db->delete('tbl_testimonials',array('testimony_id'=>$testimony_id));
    }
}
