<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_automated_event_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_automated_event by event_type_id
     */
    function get_tbl_automated_event($event_type_id)
    {
        return $this->db->get_where('tbl_automated_event',array('event_type_id'=>$event_type_id))->row_array();
    }
        
    /*
     * Get all tbl_automated_event
     */
    function get_all_tbl_automated_event()
    {
        $this->db->order_by('event_type_id', 'desc');
        return $this->db->get('tbl_automated_event')->result_array();
    }
        
    /*
     * function to add new tbl_automated_event
     */
    function add_tbl_automated_event($params)
    {
        $this->db->insert('tbl_automated_event',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_automated_event
     */
    function update_tbl_automated_event($event_type_id,$params)
    {
        $this->db->where('event_type_id',$event_type_id);
        return $this->db->update('tbl_automated_event',$params);
    }
    
    /*
     * function to delete tbl_automated_event
     */
    function delete_tbl_automated_event($event_type_id)
    {
        return $this->db->delete('tbl_automated_event',array('event_type_id'=>$event_type_id));
    }
}
