<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_event_instruction_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_event_instruction by event_instructions_id
     */
    function get_tbl_event_instruction($event_instructions_id)
    {
        return $this->db->get_where('tbl_event_instructions',array('event_instructions_id'=>$event_instructions_id))->row_array();
    }
        
    /*
     * Get all tbl_event_instructions
     */
    function get_all_tbl_event_instructions()
    {
        $this->db->order_by('event_instructions_id', 'desc');
        return $this->db->get('tbl_event_instructions')->result_array();
    }
        
    /*
     * function to add new tbl_event_instruction
     */
    function add_tbl_event_instruction($params)
    {
        $this->db->insert('tbl_event_instructions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_event_instruction
     */
    function update_tbl_event_instruction($event_instructions_id,$params)
    {
        $this->db->where('event_instructions_id',$event_instructions_id);
        return $this->db->update('tbl_event_instructions',$params);
    }
    
    /*
     * function to delete tbl_event_instruction
     */
    function delete_tbl_event_instruction($event_instructions_id)
    {
        return $this->db->delete('tbl_event_instructions',array('event_instructions_id'=>$event_instructions_id));
    }
}
