<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_social_link_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_social_link by social_id
     */
    function get_tbl_social_link($social_id)
    {
        return $this->db->get_where('tbl_social_link',array('social_id'=>$social_id))->row_array();
    }
        
    /*
     * Get all tbl_social_link
     */
    function get_all_tbl_social_link()
    {
        $this->db->order_by('social_id', 'desc');
        return $this->db->get('tbl_social_link')->result_array();
    }
        
    /*
     * function to add new tbl_social_link
     */
    function add_tbl_social_link($params)
    {
        $this->db->insert('tbl_social_link',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_social_link
     */
    function update_tbl_social_link($social_id,$params)
    {
        $this->db->where('social_id',$social_id);
        return $this->db->update('tbl_social_link',$params);
    }
    
    /*
     * function to delete tbl_social_link
     */
    function delete_tbl_social_link($social_id)
    {
        return $this->db->delete('tbl_social_link',array('social_id'=>$social_id));
    }
}
