<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_payment_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_payment by id
     */
    function get_tbl_payment($id)
    {
        return $this->db->get_where('tbl_payment',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_payment
     */
    function get_all_tbl_payment()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_payment')->result_array();
    }
        
    /*
     * function to add new tbl_payment
     */
    function add_tbl_payment($params)
    {
        $this->db->insert('tbl_payment',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_payment
     */
    function update_tbl_payment($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_payment',$params);
    }
    
    /*
     * function to delete tbl_payment
     */
    function delete_tbl_payment($id)
    {
        return $this->db->delete('tbl_payment',array('id'=>$id));
    }
}
