<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_district_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_district by id
     */
    function get_tbl_district($id)
    {
        return $this->db->get_where('tbl_districts',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_districts
     */
    function get_all_tbl_districts()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_districts')->result_array();
    }
        
    /*
     * function to add new tbl_district
     */
    function add_tbl_district($params)
    {
        $this->db->insert('tbl_districts',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_district
     */
    function update_tbl_district($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_districts',$params);
    }
    
    /*
     * function to delete tbl_district
     */
    function delete_tbl_district($id)
    {
        return $this->db->delete('tbl_districts',array('id'=>$id));
    }
}
