<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_gift_card_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_gift_card by gift_card_id
     */
    function get_tbl_gift_card($gift_card_id)
    {
        return $this->db->get_where('tbl_gift_card',array('gift_card_id'=>$gift_card_id))->row_array();
    }
        
    /*
     * Get all tbl_gift_card
     */
    function get_all_tbl_gift_card()
    {
        $this->db->order_by('gift_card_id', 'desc');
        return $this->db->get('tbl_gift_card')->result_array();
    }
        
    /*
     * function to add new tbl_gift_card
     */
    function add_tbl_gift_card($params)
    {
        $this->db->insert('tbl_gift_card',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_gift_card
     */
    function update_tbl_gift_card($gift_card_id,$params)
    {
        $this->db->where('gift_card_id',$gift_card_id);
        return $this->db->update('tbl_gift_card',$params);
    }
    
    /*
     * function to delete tbl_gift_card
     */
    function delete_tbl_gift_card($gift_card_id)
    {
        return $this->db->delete('tbl_gift_card',array('gift_card_id'=>$gift_card_id));
    }
}
