<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_event_direction_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_event_direction by event_directions_id
     */
    function get_tbl_event_direction($event_directions_id)
    {
        return $this->db->get_where('tbl_event_directions',array('event_directions_id'=>$event_directions_id))->row_array();
    }
        
    /*
     * Get all tbl_event_directions
     */
    function get_all_tbl_event_directions()
    {
        $this->db->order_by('event_directions_id', 'desc');
        return $this->db->get('tbl_event_directions')->result_array();
    }
        
    /*
     * function to add new tbl_event_direction
     */
    function add_tbl_event_direction($params)
    {
        $this->db->insert('tbl_event_directions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_event_direction
     */
    function update_tbl_event_direction($event_directions_id,$params)
    {
        $this->db->where('event_directions_id',$event_directions_id);
        return $this->db->update('tbl_event_directions',$params);
    }
    
    /*
     * function to delete tbl_event_direction
     */
    function delete_tbl_event_direction($event_directions_id)
    {
        return $this->db->delete('tbl_event_directions',array('event_directions_id'=>$event_directions_id));
    }
}
