<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_chat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_chat by id
     */
    function get_tbl_chat($id)
    {
        return $this->db->get_where('tbl_chat',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_chat
     */
    function get_all_tbl_chat()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_chat')->result_array();
    }
        
    /*
     * function to add new tbl_chat
     */
    function add_tbl_chat($params)
    {
        $this->db->insert('tbl_chat',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_chat
     */
    function update_tbl_chat($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_chat',$params);
    }
    
    /*
     * function to delete tbl_chat
     */
    function delete_tbl_chat($id)
    {
        return $this->db->delete('tbl_chat',array('id'=>$id));
    }
}
