<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_client_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_client by client_id
     */
    function get_tbl_client($client_id)
    {
        return $this->db->get_where('tbl_client',array('client_id'=>$client_id))->row_array();
    }
        
    /*
     * Get all tbl_client
     */
    function get_all_tbl_client()
    {
        $this->db->order_by('client_id', 'desc');
        return $this->db->get('tbl_client')->result_array();
    }
        
    /*
     * function to add new tbl_client
     */
    function add_tbl_client($params)
    {
        $this->db->insert('tbl_client',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_client
     */
    function update_tbl_client($client_id,$params)
    {
        $this->db->where('client_id',$client_id);
        return $this->db->update('tbl_client',$params);
    }
    
    /*
     * function to delete tbl_client
     */
    function delete_tbl_client($client_id)
    {
        return $this->db->delete('tbl_client',array('client_id'=>$client_id));
    }
}
