<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_site_statu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_site_statu by 
     */
    function get_tbl_site_statu($)
    {
        return $this->db->get_where('tbl_site_status',array(''=>$))->row_array();
    }
        
    /*
     * Get all tbl_site_status
     */
    function get_all_tbl_site_status()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('tbl_site_status')->result_array();
    }
        
    /*
     * function to add new tbl_site_statu
     */
    function add_tbl_site_statu($params)
    {
        $this->db->insert('tbl_site_status',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_site_statu
     */
    function update_tbl_site_statu($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('tbl_site_status',$params);
    }
    
    /*
     * function to delete tbl_site_statu
     */
    function delete_tbl_site_statu($)
    {
        return $this->db->delete('tbl_site_status',array(''=>$));
    }
}
