<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_banner_master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_banner_master by banner_id
     */
    function get_tbl_banner_master($banner_id)
    {
        return $this->db->get_where('tbl_banner_master',array('banner_id'=>$banner_id))->row_array();
    }
        
    /*
     * Get all tbl_banner_master
     */
    function get_all_tbl_banner_master()
    {
        $this->db->order_by('banner_id', 'desc');
        return $this->db->get('tbl_banner_master')->result_array();
    }
        
    /*
     * function to add new tbl_banner_master
     */
    function add_tbl_banner_master($params)
    {
        $this->db->insert('tbl_banner_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_banner_master
     */
    function update_tbl_banner_master($banner_id,$params)
    {
        $this->db->where('banner_id',$banner_id);
        return $this->db->update('tbl_banner_master',$params);
    }
    
    /*
     * function to delete tbl_banner_master
     */
    function delete_tbl_banner_master($banner_id)
    {
        return $this->db->delete('tbl_banner_master',array('banner_id'=>$banner_id));
    }
}
