<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_service_time_slot_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_service_time_slot by time_slot_id
     */
    function get_tbl_service_time_slot($time_slot_id)
    {
        return $this->db->get_where('tbl_service_time_slots',array('time_slot_id'=>$time_slot_id))->row_array();
    }
        
    /*
     * Get all tbl_service_time_slots
     */
    function get_all_tbl_service_time_slots()
    {
        $this->db->order_by('time_slot_id', 'desc');
        return $this->db->get('tbl_service_time_slots')->result_array();
    }
        
    /*
     * function to add new tbl_service_time_slot
     */
    function add_tbl_service_time_slot($params)
    {
        $this->db->insert('tbl_service_time_slots',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_service_time_slot
     */
    function update_tbl_service_time_slot($time_slot_id,$params)
    {
        $this->db->where('time_slot_id',$time_slot_id);
        return $this->db->update('tbl_service_time_slots',$params);
    }
    
    /*
     * function to delete tbl_service_time_slot
     */
    function delete_tbl_service_time_slot($time_slot_id)
    {
        return $this->db->delete('tbl_service_time_slots',array('time_slot_id'=>$time_slot_id));
    }
}
