<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_promocode_master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_promocode_master by promo_id
     */
    function get_tbl_promocode_master($promo_id)
    {
        return $this->db->get_where('tbl_promocode_master',array('promo_id'=>$promo_id))->row_array();
    }
        
    /*
     * Get all tbl_promocode_master
     */
    function get_all_tbl_promocode_master()
    {
        $this->db->order_by('promo_id', 'desc');
        return $this->db->get('tbl_promocode_master')->result_array();
    }
        
    /*
     * function to add new tbl_promocode_master
     */
    function add_tbl_promocode_master($params)
    {
        $this->db->insert('tbl_promocode_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_promocode_master
     */
    function update_tbl_promocode_master($promo_id,$params)
    {
        $this->db->where('promo_id',$promo_id);
        return $this->db->update('tbl_promocode_master',$params);
    }
    
    /*
     * function to delete tbl_promocode_master
     */
    function delete_tbl_promocode_master($promo_id)
    {
        return $this->db->delete('tbl_promocode_master',array('promo_id'=>$promo_id));
    }
}
