<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_mailing_addres_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_business_mailing_addres by mailing_id
     */
    function get_tbl_business_mailing_addres($mailing_id)
    {
        return $this->db->get_where('tbl_business_mailing_address',array('mailing_id'=>$mailing_id))->row_array();
    }
        
    /*
     * Get all tbl_business_mailing_address
     */
    function get_all_tbl_business_mailing_address()
    {
        $this->db->order_by('mailing_id', 'desc');
        return $this->db->get('tbl_business_mailing_address')->result_array();
    }
        
    /*
     * function to add new tbl_business_mailing_addres
     */
    function add_tbl_business_mailing_addres($params)
    {
        $this->db->insert('tbl_business_mailing_address',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_business_mailing_addres
     */
    function update_tbl_business_mailing_addres($mailing_id,$params)
    {
        $this->db->where('mailing_id',$mailing_id);
        return $this->db->update('tbl_business_mailing_address',$params);
    }
    
    /*
     * function to delete tbl_business_mailing_addres
     */
    function delete_tbl_business_mailing_addres($mailing_id)
    {
        return $this->db->delete('tbl_business_mailing_address',array('mailing_id'=>$mailing_id));
    }
}
