<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_services_staff_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_services_staff by id
     */
    function get_tbl_services_staff($id)
    {
        return $this->db->get_where('tbl_services_staff',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_services_staff
     */
    function get_all_tbl_services_staff()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_services_staff')->result_array();
    }
        
    /*
     * function to add new tbl_services_staff
     */
    function add_tbl_services_staff($params)
    {
        $this->db->insert('tbl_services_staff',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_services_staff
     */
    function update_tbl_services_staff($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_services_staff',$params);
    }
    
    /*
     * function to delete tbl_services_staff
     */
    function delete_tbl_services_staff($id)
    {
        return $this->db->delete('tbl_services_staff',array('id'=>$id));
    }
}
