<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_country_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_country by id
     */
    function get_tbl_country($id)
    {
        return $this->db->get_where('tbl_countries',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_countries
     */
    function get_all_tbl_countries()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_countries')->result_array();
    }
        
    /*
     * function to add new tbl_country
     */
    function add_tbl_country($params)
    {
        $this->db->insert('tbl_countries',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_country
     */
    function update_tbl_country($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_countries',$params);
    }
    
    /*
     * function to delete tbl_country
     */
    function delete_tbl_country($id)
    {
        return $this->db->delete('tbl_countries',array('id'=>$id));
    }
}
