<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_dynamic_page_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_dynamic_page by page_id
     */
    function get_tbl_dynamic_page($page_id)
    {
        return $this->db->get_where('tbl_dynamic_pages',array('page_id'=>$page_id))->row_array();
    }
        
    /*
     * Get all tbl_dynamic_pages
     */
    function get_all_tbl_dynamic_pages()
    {
        $this->db->order_by('page_id', 'desc');
        return $this->db->get('tbl_dynamic_pages')->result_array();
    }
        
    /*
     * function to add new tbl_dynamic_page
     */
    function add_tbl_dynamic_page($params)
    {
        $this->db->insert('tbl_dynamic_pages',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_dynamic_page
     */
    function update_tbl_dynamic_page($page_id,$params)
    {
        $this->db->where('page_id',$page_id);
        return $this->db->update('tbl_dynamic_pages',$params);
    }
    
    /*
     * function to delete tbl_dynamic_page
     */
    function delete_tbl_dynamic_page($page_id)
    {
        return $this->db->delete('tbl_dynamic_pages',array('page_id'=>$page_id));
    }
}
