<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_businessuser_promocode_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_businessuser_promocode by promo_id
     */
    function get_tbl_businessuser_promocode($promo_id)
    {
        return $this->db->get_where('tbl_businessuser_promocode',array('promo_id'=>$promo_id))->row_array();
    }
        
    /*
     * Get all tbl_businessuser_promocode
     */
    function get_all_tbl_businessuser_promocode()
    {
        $this->db->order_by('promo_id', 'desc');
        return $this->db->get('tbl_businessuser_promocode')->result_array();
    }
        
    /*
     * function to add new tbl_businessuser_promocode
     */
    function add_tbl_businessuser_promocode($params)
    {
        $this->db->insert('tbl_businessuser_promocode',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_businessuser_promocode
     */
    function update_tbl_businessuser_promocode($promo_id,$params)
    {
        $this->db->where('promo_id',$promo_id);
        return $this->db->update('tbl_businessuser_promocode',$params);
    }
    
    /*
     * function to delete tbl_businessuser_promocode
     */
    function delete_tbl_businessuser_promocode($promo_id)
    {
        return $this->db->delete('tbl_businessuser_promocode',array('promo_id'=>$promo_id));
    }
}
