<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_client_addres_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_client_addres by client_address_id
     */
    function get_tbl_client_addres($client_address_id)
    {
        return $this->db->get_where('tbl_client_address',array('client_address_id'=>$client_address_id))->row_array();
    }
        
    /*
     * Get all tbl_client_address
     */
    function get_all_tbl_client_address()
    {
        $this->db->order_by('client_address_id', 'desc');
        return $this->db->get('tbl_client_address')->result_array();
    }
        
    /*
     * function to add new tbl_client_addres
     */
    function add_tbl_client_addres($params)
    {
        $this->db->insert('tbl_client_address',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_client_addres
     */
    function update_tbl_client_addres($client_address_id,$params)
    {
        $this->db->where('client_address_id',$client_address_id);
        return $this->db->update('tbl_client_address',$params);
    }
    
    /*
     * function to delete tbl_client_addres
     */
    function delete_tbl_client_addres($client_address_id)
    {
        return $this->db->delete('tbl_client_address',array('client_address_id'=>$client_address_id));
    }
}
