<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_membership_master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_membership_master by membership_id
     */
    function get_tbl_membership_master($membership_id)
    {
        return $this->db->get_where('tbl_membership_master',array('membership_id'=>$membership_id))->row_array();
    }
        
    /*
     * Get all tbl_membership_master
     */
    function get_all_tbl_membership_master()
    {
        $this->db->order_by('membership_id', 'desc');
        return $this->db->get('tbl_membership_master')->result_array();
    }
        
    /*
     * function to add new tbl_membership_master
     */
    function add_tbl_membership_master($params)
    {
        $this->db->insert('tbl_membership_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_membership_master
     */
    function update_tbl_membership_master($membership_id,$params)
    {
        $this->db->where('membership_id',$membership_id);
        return $this->db->update('tbl_membership_master',$params);
    }
    
    /*
     * function to delete tbl_membership_master
     */
    function delete_tbl_membership_master($membership_id)
    {
        return $this->db->delete('tbl_membership_master',array('membership_id'=>$membership_id));
    }
}
