<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_business_staff_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_business_staff by staff_id
     */
    function get_tbl_business_staff($staff_id)
    {
        return $this->db->get_where('tbl_business_staff',array('staff_id'=>$staff_id))->row_array();
    }
        
    /*
     * Get all tbl_business_staff
     */
    function get_all_tbl_business_staff()
    {
        $this->db->order_by('staff_id', 'desc');
        return $this->db->get('tbl_business_staff')->result_array();
    }
        
    /*
     * function to add new tbl_business_staff
     */
    function add_tbl_business_staff($params)
    {
        $this->db->insert('tbl_business_staff',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_business_staff
     */
    function update_tbl_business_staff($staff_id,$params)
    {
        $this->db->where('staff_id',$staff_id);
        return $this->db->update('tbl_business_staff',$params);
    }
    
    /*
     * function to delete tbl_business_staff
     */
    function delete_tbl_business_staff($staff_id)
    {
        return $this->db->delete('tbl_business_staff',array('staff_id'=>$staff_id));
    }
}
