<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_staff_location_hour_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_staff_location_hour by location_hours_id
     */
    function get_tbl_staff_location_hour($location_hours_id)
    {
        return $this->db->get_where('tbl_staff_location_hours',array('location_hours_id'=>$location_hours_id))->row_array();
    }
        
    /*
     * Get all tbl_staff_location_hours
     */
    function get_all_tbl_staff_location_hours()
    {
        $this->db->order_by('location_hours_id', 'desc');
        return $this->db->get('tbl_staff_location_hours')->result_array();
    }
        
    /*
     * function to add new tbl_staff_location_hour
     */
    function add_tbl_staff_location_hour($params)
    {
        $this->db->insert('tbl_staff_location_hours',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_staff_location_hour
     */
    function update_tbl_staff_location_hour($location_hours_id,$params)
    {
        $this->db->where('location_hours_id',$location_hours_id);
        return $this->db->update('tbl_staff_location_hours',$params);
    }
    
    /*
     * function to delete tbl_staff_location_hour
     */
    function delete_tbl_staff_location_hour($location_hours_id)
    {
        return $this->db->delete('tbl_staff_location_hours',array('location_hours_id'=>$location_hours_id));
    }
}
