<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_newsletter_master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_newsletter_master by news_id
     */
    function get_tbl_newsletter_master($news_id)
    {
        return $this->db->get_where('tbl_newsletter_master',array('news_id'=>$news_id))->row_array();
    }
        
    /*
     * Get all tbl_newsletter_master
     */
    function get_all_tbl_newsletter_master()
    {
        $this->db->order_by('news_id', 'desc');
        return $this->db->get('tbl_newsletter_master')->result_array();
    }
        
    /*
     * function to add new tbl_newsletter_master
     */
    function add_tbl_newsletter_master($params)
    {
        $this->db->insert('tbl_newsletter_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_newsletter_master
     */
    function update_tbl_newsletter_master($news_id,$params)
    {
        $this->db->where('news_id',$news_id);
        return $this->db->update('tbl_newsletter_master',$params);
    }
    
    /*
     * function to delete tbl_newsletter_master
     */
    function delete_tbl_newsletter_master($news_id)
    {
        return $this->db->delete('tbl_newsletter_master',array('news_id'=>$news_id));
    }
}
