<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_category by category_id
     */
    function get_tbl_category($category_id)
    {
        return $this->db->get_where('tbl_category',array('category_id'=>$category_id))->row_array();
    }
        
    /*
     * Get all tbl_category
     */
    function get_all_tbl_category()
    {
        $this->db->order_by('category_id', 'desc');
        return $this->db->get('tbl_category')->result_array();
    }
        
    /*
     * function to add new tbl_category
     */
    function add_tbl_category($params)
    {
        $this->db->insert('tbl_category',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_category
     */
    function update_tbl_category($category_id,$params)
    {
        $this->db->where('category_id',$category_id);
        return $this->db->update('tbl_category',$params);
    }
    
    /*
     * function to delete tbl_category
     */
    function delete_tbl_category($category_id)
    {
        return $this->db->delete('tbl_category',array('category_id'=>$category_id));
    }
}
