<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_add_availibility_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_add_availibility by availibility_id
     */
    function get_tbl_add_availibility($availibility_id)
    {
        return $this->db->get_where('tbl_add_availibility',array('availibility_id'=>$availibility_id))->row_array();
    }
        
    /*
     * Get all tbl_add_availibility
     */
    function get_all_tbl_add_availibility()
    {
        $this->db->order_by('availibility_id', 'desc');
        return $this->db->get('tbl_add_availibility')->result_array();
    }
        
    /*
     * function to add new tbl_add_availibility
     */
    function add_tbl_add_availibility($params)
    {
        $this->db->insert('tbl_add_availibility',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_add_availibility
     */
    function update_tbl_add_availibility($availibility_id,$params)
    {
        $this->db->where('availibility_id',$availibility_id);
        return $this->db->update('tbl_add_availibility',$params);
    }
    
    /*
     * function to delete tbl_add_availibility
     */
    function delete_tbl_add_availibility($availibility_id)
    {
        return $this->db->delete('tbl_add_availibility',array('availibility_id'=>$availibility_id));
    }
}
