<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_message_to_busines_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_message_to_busines by message_id
     */
    function get_tbl_message_to_busines($message_id)
    {
        return $this->db->get_where('tbl_message_to_business',array('message_id'=>$message_id))->row_array();
    }
        
    /*
     * Get all tbl_message_to_business
     */
    function get_all_tbl_message_to_business()
    {
        $this->db->order_by('message_id', 'desc');
        return $this->db->get('tbl_message_to_business')->result_array();
    }
        
    /*
     * function to add new tbl_message_to_busines
     */
    function add_tbl_message_to_busines($params)
    {
        $this->db->insert('tbl_message_to_business',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_message_to_busines
     */
    function update_tbl_message_to_busines($message_id,$params)
    {
        $this->db->where('message_id',$message_id);
        return $this->db->update('tbl_message_to_business',$params);
    }
    
    /*
     * function to delete tbl_message_to_busines
     */
    function delete_tbl_message_to_busines($message_id)
    {
        return $this->db->delete('tbl_message_to_business',array('message_id'=>$message_id));
    }
}
