<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_faq_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_faq by faq_id
     */
    function get_tbl_faq($faq_id)
    {
        return $this->db->get_where('tbl_faq',array('faq_id'=>$faq_id))->row_array();
    }
        
    /*
     * Get all tbl_faq
     */
    function get_all_tbl_faq()
    {
        $this->db->order_by('faq_id', 'desc');
        return $this->db->get('tbl_faq')->result_array();
    }
        
    /*
     * function to add new tbl_faq
     */
    function add_tbl_faq($params)
    {
        $this->db->insert('tbl_faq',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_faq
     */
    function update_tbl_faq($faq_id,$params)
    {
        $this->db->where('faq_id',$faq_id);
        return $this->db->update('tbl_faq',$params);
    }
    
    /*
     * function to delete tbl_faq
     */
    function delete_tbl_faq($faq_id)
    {
        return $this->db->delete('tbl_faq',array('faq_id'=>$faq_id));
    }
}
