<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_walkin_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_walkin_user by id
     */
    function get_tbl_walkin_user($id)
    {
        return $this->db->get_where('tbl_walkin_users',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbl_walkin_users
     */
    function get_all_tbl_walkin_users()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbl_walkin_users')->result_array();
    }
        
    /*
     * function to add new tbl_walkin_user
     */
    function add_tbl_walkin_user($params)
    {
        $this->db->insert('tbl_walkin_users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_walkin_user
     */
    function update_tbl_walkin_user($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbl_walkin_users',$params);
    }
    
    /*
     * function to delete tbl_walkin_user
     */
    function delete_tbl_walkin_user($id)
    {
        return $this->db->delete('tbl_walkin_users',array('id'=>$id));
    }
}
