<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_automated_message_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_automated_message by auto_id
     */
    function get_tbl_automated_message($auto_id)
    {
        return $this->db->get_where('tbl_automated_message',array('auto_id'=>$auto_id))->row_array();
    }
        
    /*
     * Get all tbl_automated_message
     */
    function get_all_tbl_automated_message()
    {
        $this->db->order_by('auto_id', 'desc');
        return $this->db->get('tbl_automated_message')->result_array();
    }
        
    /*
     * function to add new tbl_automated_message
     */
    function add_tbl_automated_message($params)
    {
        $this->db->insert('tbl_automated_message',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_automated_message
     */
    function update_tbl_automated_message($auto_id,$params)
    {
        $this->db->where('auto_id',$auto_id);
        return $this->db->update('tbl_automated_message',$params);
    }
    
    /*
     * function to delete tbl_automated_message
     */
    function delete_tbl_automated_message($auto_id)
    {
        return $this->db->delete('tbl_automated_message',array('auto_id'=>$auto_id));
    }
}
